### ISSUE TITLE
Seeing random unit test failure at data flow

### ISSUE THREAD

**Issue by sasrin** [cloudfoundry-incubator/cf-abacus#101]
abacus-dataflow
    ✓ runs a map transform and stores its inputs and outputs (1492ms)
    1) runs a reduce transform and stores its inputs and outputs

  1 passing (2s)
  1 failing

  1) abacus-dataflow runs a reduce transform and stores its inputs and outputs:
     Uncaught TypeError: Cannot read property '0' of undefined
      at null._onTimeout (lib/test/test.js:383:49)

**Comment by jsdelfino** [comment]
Started to look into this, will use a post callback instead of a sinon spy like we do in some of the other unit tests.
