### ISSUE TITLE
fly set-pipeline error   cannot unmarshal !!seq into string

### ISSUE THREAD

**Issue by jkujovic** [cloudfoundry-incubator/cf-abacus#1025]
Hi,

I using concourse v 4.0.0 and when I try  set-pipeline deploy-pipeline.yml
I have problem with  variable in deploy-pipeline-vars.yml

for var:
db-service-instances:
  - name: service-instance-name
    plan: plan-name

I get error:
error: could not resolve old-style template vars: yaml: unmarshal errors:
  line 58: cannot unmarshal !!seq into string

I tried change this variable to:
db-service-instances: |
service-instance-name:plan-name

then I get error:
error: could not resolve old-style template vars: yaml: line 60: could not find expected ':'

or another:
db-service-instances: |
  service-instance-name:plan-name

then I get error:
error: could not resolve template vars: yaml: line 65: did not find expected ',' or '}'

Any idea? 

Thx

jan

**Comment by jkujovic** [comment]
I has bad char in manifest, my mistake

**Comment by hsiliev** [comment]
@jkujovic How did you made this work? I want to document it in the pipeline readme

**Comment by jkujovic** [comment]
Hi,

The fix for me was:
db-service-instances: !!str db-collector:standard db-meter:standard db-accumulator:standard db-aggregator:standard db-bridge:standard db-plugins:standard db-session:standard

!!str yaml directive tell that variable is string type. Maybe can be work without this direcitve and use sentence in "" or ''

Jan
