### ISSUE TITLE
problem with node": ">=8.10.0 <9.0.0",

### ISSUE THREAD

**Issue by jkujovic** [cloudfoundry-incubator/cf-abacus#1051]
Hi,

if you changed 
from     "node": ">=8.9.4 <9.0.0",
to      "node": ">=8.10.0 <9.0.0",

there is problem with   pulled godofcontainers/node-mongodb
because  latest version is 8.9.4 360 MB 8 months ago

and concourse task  build-abacus faild with error 
error abacus-replace-template@1.1.3: The engine "node" is incompatible with this module. Expected version ">=8.10.0 <9.0.0".

**Comment by hsiliev** [comment]
We bumped the node version with the latest commits.
