### ISSUE TITLE
Include BigNumber.js support inside of resource functions

### ISSUE THREAD

**Issue by BetaFood** [cloudfoundry-incubator/cf-abacus#108]
Currently, the sample formulas in abacus are using just normal calculations among numbers. This can lead into some floating point precision issues.
`0.1 * 0.2 = 0.020000000000000004`

BigNumber.js support inside of the functions/eval would help alleviate these issues in calculations.

**Comment by jsdelfino** [comment]
This will also help make the tests more reliable as I'm running into rounding errors with our performance tests (e.g. seeing usage of 74.9999999999999... when the test expects 75.)

**Comment by BetaFood** [comment]
This is finished as part of 7ca32cb7ab047f70d58bba24c955e016c80de889 and 1af35f7047ba0e299ab5e775c15864f31a9b0c63
