### ISSUE TITLE
CF Bridge overloads Abacus

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#109]
On startup the CF Bridge POSTs enormous amount of usage reports that triggers Abacus circuit breakers. On non-loaded systems this usually involves around 100 000 events/posts.

We can delay the submission of data and offload Abacus by implementing some soft of back-off logic.

**Comment by sasrin** [comment]
> On startup the CF Bridge POSTs enormous amount of usage reports that triggers Abacus circuit breakers. 

Do we know which ones are moving to open state?

> We can delay the submission of data and offload Abacus by implementing some soft of back-off logic.

I believe throttling the submissions and batching the submissions could help.. you may want to look at the performance test as an example client that submits usage using throttle and batch [1].

[1] https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/test/perf/src/test/test.js#L276-L279

**Comment by hsiliev** [comment]
Thanks for the hint. We already added a simple exponential back-off policy when the POST fail. However we'll definitely need to batch the requests as well to reduce the latency, traffic and the load on Abacus.

Is there an easy way to check all circuits? Something like the Hystrix's monitoring tools? For sure we saw an open circuit in dbclient module, but that does not identify the process/app, thresholds and all.

Even with batching we may need to address this issue by creating a sizing guide for Abacus. There is a question in this direction here: https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/Z7I74QHHVZRA43OVXO3CMC2RIDZ2BY76/

**Comment by hsiliev** [comment]
Adding batching helped to reduce the errors from Abacus. However we found out that with the default configuration we soon reached:
* OOM in Pouch (dbserver) - increased memory to 4GB
* OOM in cf-bridge - increased the memory to 2GB

**Comment by jsdelfino** [comment]
We probably need to spend some time running the performance tests and tuning the apps, including the default values for batch sizes, throttling, retries, timeouts and instance numbers, to get to a point where a client sending a peak of usage docs doesn't cause errors or timeouts.

**Comment by jsdelfino** [comment]
@hsiliev, we actually have support for Hystrix in Abacus.

@sasrin, could you point us to the work you did with Turbine and Hystrix, and maybe add a little doc describing how to set it up to monitor Abacus. Thanks.

**Comment by jsdelfino** [comment]
@sasrin, maybe create a doc/monitoring.md file...

**Comment by hsiliev** [comment]
Pushed improved version of the bridge with batching and exponential back-off is requests fail.

**Comment by hsiliev** [comment]
https://github.com/cloudfoundry-incubator/cf-abacus/commit/938dbf52ce6dfc2f9e82e3c0a61f547a422b35ab closes this bug
