### ISSUE TITLE
Monitoring guidelines

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#120]
Abacus has several circuit breakers that can be monitored using Hystrix tools. We should add a short guide on how to do this if only to hint users that this is possible.

**Comment by sasrin** [comment]
Started to document the steps with - [Document steps to monitor Abacus applications using Hystrix Dashboard](https://github.com/cloudfoundry-incubator/cf-abacus/commit/0e2f6160301c9fadac937957f383347436a8e0c7)

**Comment by jsdelfino** [comment]
Looks like with your various contributions we now have a good doc for this in monitor.md. Thanks!
Please re-open the issue if you think we need more doc on this.
