### ISSUE TITLE
Unable to use database prefix when submitted with credentials

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#125]
With prefixes, dbclient successfully resolves the database urls when we do not have any authentication information in the url. However, if we have authentication information in the url,  the password is considered as a placeholder and is replaced with undefined.

```sh
export COUCHDB=https://username:password@username.cloudant.com/prefix-:name
# results in
abacus-dbclient 789 Using db https://usernameundefined@username.cloudant.com/prefix-abacus-collector-collected-usage-0-201510 in write mode

**Comment by jsdelfino** [comment]
Fixed in f5c7afb.
