### ISSUE TITLE
Reports gathered from Partial submissions show all of the metrics of the resource.

### ISSUE THREAD

**Issue by AzureEnigma** [cloudfoundry-incubator/cf-abacus#127]
When submitting a usage with only partial metrics included in it (object storage without heavy api calls in it), the report retrieved from abacus still includes the heavy_api_calls metric and just lists it as 0 for the usage.

Submitted:

{
    "usage":[
         {
            "start":1445459051000, 
            "end":1445459051000, 
            "region":"us",
            "organization_id":"us:6dcd0fb9-ba5b-401f-b1ea-7630abc67520",
            "space_id":"f1df0c46-b12f-4641-ad29-815ff91b3ef7",
            "consumer_id":"EXTERNAL:40df7d7e-8417-01cb-b8f4-dafa8b9ed16c",
            "resource_id":"object-storage",
            "plan_id":"basic",
            "resource_instance_id":"aa393c16-c366-40af-9c68-50806fbf92e6",
            "measured_usage":[
               {
                  "measure":"storage",
                  "quantity":2684354560
               },
               {
                  "measure":"light_api_calls",
                  "quantity":2500
               }
            ]
         }
         ]
         }

And the report retrieves:

{
  "organization_id": "us:6dcd0fb9-ba5b-401f-b1ea-7630abc67520",
  "resources": [
    {
      "resource_id": "object-storage",
      "plans": [
        {
          "plan_id": "basic",
          "aggregated_usage": [
            {
              "metric": "storage",
              "windows": [
                [
                  {
                    "quantity": 0,
                    "cost": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "cost": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "cost": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "cost": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 2.5,
                    "cost": 2.5,
                    "summary": 2.5,
                    "charge": 2.5
                  }
                ]
              ]
            },
            {
              "metric": "thousand_light_api_calls",
              "windows": [
                [
                  {
                    "quantity": 0,
                    "cost": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "cost": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "cost": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "cost": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 2.5,
                    "cost": 0.075,
                    "summary": 2.5,
                    "charge": 0.075
                  }
                ]
              ]
            },
            {
              "metric": "heavy_api_calls",
              "windows": [
                [
                  {
                    "quantity": 0,
                    "cost": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "cost": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "cost": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "cost": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "cost": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ]
              ]
            }
          ],
          "windows": [
            [
              {
                "charge": 0
              }
            ],
            [
              {
                "charge": 0
              }
            ],
            [
              {
                "charge": 0
              }
            ],
            [
              {
                "charge": 0
              }
            ],
            [
              {
                "charge": 2.575
              }
            ]
          ]
        }
      ],
      "aggregated_usage": [
        {
          "metric": "storage",
          "windows": [
            [
              {
                "quantity": 0,
                "summary": 0,
                "charge": 0
              }
            ],
            [
              {
                "quantity": 0,
                "summary": 0,
                "charge": 0
              }
            ],
            [
              {
                "quantity": 0,
                "summary": 0,
                "charge": 0
              }
            ],
            [
              {
                "quantity": 0,
                "summary": 0,
                "charge": 0
              }
            ],
            [
              {
                "quantity": 2.5,
                "summary": 2.5,
                "charge": 2.5
              }
            ]
          ]
        },
        {
          "metric": "thousand_light_api_calls",
          "windows": [
            [
              {
                "quantity": 0,
                "summary": 0,
                "charge": 0
              }
            ],
            [
              {
                "quantity": 0,
                "summary": 0,
                "charge": 0
              }
            ],
            [
              {
                "quantity": 0,
                "summary": 0,
                "charge": 0
              }
            ],
            [
              {
                "quantity": 0,
                "summary": 0,
                "charge": 0
              }
            ],
            [
              {
                "quantity": 2.5,
                "summary": 2.5,
                "charge": 0.075
              }
            ]
          ]
        },
        {
          "metric": "heavy_api_calls",
          "windows": [
            [
              {
                "quantity": 0,
                "summary": 0,
                "charge": 0
              }
            ],
            [
              {
                "quantity": 0,
                "summary": 0,
                "charge": 0
              }
            ],
            [
              {
                "quantity": 0,
                "summary": 0,
                "charge": 0
              }
            ],
            [
              {
                "quantity": 0,
                "summary": 0,
                "charge": 0
              }
            ],
            [
              {
                "quantity": 0,
                "summary": 0,
                "charge": 0
              }
            ]
          ]
        }
      ],
      "windows": [
        [
          {
            "charge": 0
          }
        ],
        [
          {
            "charge": 0
          }
        ],
        [
          {
            "charge": 0
          }
        ],
        [
          {
            "charge": 0
          }
        ],
        [
          {
            "charge": 2.575
          }
        ]
      ]
    }
  ],
  "spaces": [
    {
      "space_id": "f1df0c46-b12f-4641-ad29-815ff91b3ef7",
      "resources": [
        {
          "resource_id": "object-storage",
          "plans": [
            {
              "plan_id": "basic",
              "aggregated_usage": [
                {
                  "metric": "storage",
                  "windows": [
                    [
                      {
                        "quantity": 0,
                        "cost": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "cost": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "cost": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "cost": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 2.5,
                        "cost": 2.5,
                        "summary": 2.5,
                        "charge": 2.5
                      }
                    ]
                  ]
                },
                {
                  "metric": "thousand_light_api_calls",
                  "windows": [
                    [
                      {
                        "quantity": 0,
                        "cost": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "cost": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "cost": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "cost": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 2.5,
                        "cost": 0.075,
                        "summary": 2.5,
                        "charge": 0.075
                      }
                    ]
                  ]
                },
                {
                  "metric": "heavy_api_calls",
                  "windows": [
                    [
                      {
                        "quantity": 0,
                        "cost": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "cost": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "cost": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "cost": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "cost": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ]
                  ]
                }
              ],
              "windows": [
                [
                  {
                    "charge": 0
                  }
                ],
                [
                  {
                    "charge": 0
                  }
                ],
                [
                  {
                    "charge": 0
                  }
                ],
                [
                  {
                    "charge": 0
                  }
                ],
                [
                  {
                    "charge": 2.575
                  }
                ]
              ]
            }
          ],
          "aggregated_usage": [
            {
              "metric": "storage",
              "windows": [
                [
                  {
                    "quantity": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 2.5,
                    "summary": 2.5,
                    "charge": 2.5
                  }
                ]
              ]
            },
            {
              "metric": "thousand_light_api_calls",
              "windows": [
                [
                  {
                    "quantity": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 2.5,
                    "summary": 2.5,
                    "charge": 0.075
                  }
                ]
              ]
            },
            {
              "metric": "heavy_api_calls",
              "windows": [
                [
                  {
                    "quantity": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ],
                [
                  {
                    "quantity": 0,
                    "summary": 0,
                    "charge": 0
                  }
                ]
              ]
            }
          ],
          "windows": [
            [
              {
                "charge": 0
              }
            ],
            [
              {
                "charge": 0
              }
            ],
            [
              {
                "charge": 0
              }
            ],
            [
              {
                "charge": 0
              }
            ],
            [
              {
                "charge": 2.575
              }
            ]
          ]
        }
      ],
      "consumers": [
        {
          "consumer_id": "EXTERNAL:40df7d7e-8417-01cb-b8f4-dafa8b9ed16c",
          "resources": [
            {
              "resource_id": "object-storage",
              "plans": [
                {
                  "plan_id": "basic",
                  "aggregated_usage": [
                    {
                      "metric": "storage",
                      "windows": [
                        [
                          {
                            "quantity": 0,
                            "cost": 0,
                            "summary": 0,
                            "charge": 0
                          }
                        ],
                        [
                          {
                            "quantity": 0,
                            "cost": 0,
                            "summary": 0,
                            "charge": 0
                          }
                        ],
                        [
                          {
                            "quantity": 0,
                            "cost": 0,
                            "summary": 0,
                            "charge": 0
                          }
                        ],
                        [
                          {
                            "quantity": 0,
                            "cost": 0,
                            "summary": 0,
                            "charge": 0
                          }
                        ],
                        [
                          {
                            "quantity": 2.5,
                            "cost": 2.5,
                            "summary": 2.5,
                            "charge": 2.5
                          }
                        ]
                      ]
                    },
                    {
                      "metric": "thousand_light_api_calls",
                      "windows": [
                        [
                          {
                            "quantity": 0,
                            "cost": 0,
                            "summary": 0,
                            "charge": 0
                          }
                        ],
                        [
                          {
                            "quantity": 0,
                            "cost": 0,
                            "summary": 0,
                            "charge": 0
                          }
                        ],
                        [
                          {
                            "quantity": 0,
                            "cost": 0,
                            "summary": 0,
                            "charge": 0
                          }
                        ],
                        [
                          {
                            "quantity": 0,
                            "cost": 0,
                            "summary": 0,
                            "charge": 0
                          }
                        ],
                        [
                          {
                            "quantity": 2.5,
                            "cost": 0.075,
                            "summary": 2.5,
                            "charge": 0.075
                          }
                        ]
                      ]
                    },
                    {
                      "metric": "heavy_api_calls",
                      "windows": [
                        [
                          {
                            "quantity": 0,
                            "cost": 0,
                            "summary": 0,
                            "charge": 0
                          }
                        ],
                        [
                          {
                            "quantity": 0,
                            "cost": 0,
                            "summary": 0,
                            "charge": 0
                          }
                        ],
                        [
                          {
                            "quantity": 0,
                            "cost": 0,
                            "summary": 0,
                            "charge": 0
                          }
                        ],
                        [
                          {
                            "quantity": 0,
                            "cost": 0,
                            "summary": 0,
                            "charge": 0
                          }
                        ],
                        [
                          {
                            "quantity": 0,
                            "cost": 0,
                            "summary": 0,
                            "charge": 0
                          }
                        ]
                      ]
                    }
                  ],
                  "windows": [
                    [
                      {
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "charge": 2.575
                      }
                    ]
                  ]
                }
              ],
              "aggregated_usage": [
                {
                  "metric": "storage",
                  "windows": [
                    [
                      {
                        "quantity": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 2.5,
                        "summary": 2.5,
                        "charge": 2.5
                      }
                    ]
                  ]
                },
                {
                  "metric": "thousand_light_api_calls",
                  "windows": [
                    [
                      {
                        "quantity": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 2.5,
                        "summary": 2.5,
                        "charge": 0.075
                      }
                    ]
                  ]
                },
                {
                  "metric": "heavy_api_calls",
                  "windows": [
                    [
                      {
                        "quantity": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "quantity": 0,
                        "summary": 0,
                        "charge": 0
                      }
                    ]
                  ]
                }
              ],
              "windows": [
                [
                  {
                    "charge": 0
                  }
                ],
                [
                  {
                    "charge": 0
                  }
                ],
                [
                  {
                    "charge": 0
                  }
                ],
                [
                  {
                    "charge": 0
                  }
                ],
                [
                  {
                    "charge": 2.575
                  }
                ]
              ]
            }
          ],
          "windows": [
            [
              {
                "charge": 0
              }
            ],
            [
              {
                "charge": 0
              }
            ],
            [
              {
                "charge": 0
              }
            ],
            [
              {
                "charge": 0
              }
            ],
            [
              {
                "charge": 2.575
              }
            ]
          ]
        }
      ],
      "windows": [
        [
          {
            "charge": 0
          }
        ],
        [
          {
            "charge": 0
          }
        ],
        [
          {
            "charge": 0
          }
        ],
        [
          {
            "charge": 0
          }
        ],
        [
          {
            "charge": 2.575
          }
        ]
      ]
    }
  ],
  "start": 1445459051000,
  "end": 1445459051000,
  "region": "us",
  "id": "k/us:6dcd0fb9-ba5b-401f-b1ea-7630abc67520/t/0001445808830062-0-1-0",
  "processed": 1445808830062,
  "windows": [
    [
      {
        "charge": 0
      }
    ],
    [
      {
        "charge": 0
      }
    ],
    [
      {
        "charge": 0
      }
    ],
    [
      {
        "charge": 0
      }
    ],
    [
      {
        "charge": 2.575
      }
    ]
  ]
}

**Comment by jsdelfino** [comment]
I'm not sure that's a bug. It could actually be a good thing to have these zero default values for the metrics configured on the resource.

**Comment by sinduri** [comment]
The scenario we are trying to cover is, we have a resource definition which wants to meter (storage and instance). 

If for a basic plan, the provider submits both the units, but for an advanced plan, the submits just the instance count, when we retrieve the report for that organization, we might see usage for the storage :0 and instance :3, which will be misleading. 

So it would be good not to report that metric as such.

**Comment by BetaFood** [comment]
This behavior is a result of the meter service. Specifically, the metered usage is built based off a map of all the metrics defined in a resource.
Since metrics can house more than one measure, it's probably not feasible to try to base the document off of the measures, but rather, it may be better to omit any metrics with invalid values (such as undefined or NaN?).

**Comment by jsdelfino** [comment]
@BetaFood Either that, or we may need to model which metrics are produced by which measures in the resource config to be able to cleanly determine that a metric should not be produced. In the example given here, we'd then be able to determine that no `heavy_api_calls` *metric* should be produced because the incoming usage didn't include the `heavy_api_calls` *measure*.

Another, perhaps better, option would be to allow configuration at the plan level in addition to the resource level, as IIUC what @sinduri described, he wants to omit metrics for a specific *plan*.

**Comment by jsdelfino** [comment]
Moving this to 0.0.3 as it'll require a bit more discussion and design work. Will start a discussion on the mailing list to collect community input.

**Comment by jsdelfino** [comment]
Fixed by @KRuelY's recent changes introducing metering, rating, and pricing plans, now decoupled from the original resource and provisioning plan.
