### ISSUE TITLE
cf-bridge does not handle 409 for duplicate usage submission

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#128]
Submitting duplicate usage returns 409. CF-Bridge treats 409 as error and simply retries.

The discussion on reporting duplicate usage to user is in #124

**Comment by hsiliev** [comment]
I'm currently investigating retrying the submission of usage without batching to handle 409. If a submission returns 201 batching is activated.

Seems this solves the problem but complicates the code as well.

**Comment by jsdelfino** [comment]
Yes, it complicates the code. Thanks for looking into this. I'm also looking into a better way to handle duplicates in the collector and meter services (as discussed in #129) so hopefully once that's done you won't have to do that workaround anymore.
