### ISSUE TITLE
Request header field name - Authorization vs authorization 

### ISSUE THREAD

**Issue by sasrin** [cloudfoundry-incubator/cf-abacus#137]
Are request header field names case-sensitive or case-insensitive?

**Comment by sasrin** [comment]
According to [1]

HTTP header fields, which include general-header (section 4.5), request-header (section 5.3), response-header (section 6.2), and entity-header (section 7.1) fields, follow the same generic format as that given in Section 3.1 of RFC 822 [9]. Each header field consists of a name followed by a colon (":") and the field value. **Field names are case-insensitive.** The field value MAY be preceded by any amount of LWS, though a single SP is preferred. Header fields can be extended over multiple lines by preceding each extra line with at least one SP or HT. Applications ought to follow "common form", where one is known or indicated, when generating HTTP constructs, since there might exist some implementations that fail to accept anything beyond the common forms.

[1] http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html

**Comment by jsdelfino** [comment]
Correct they're case-insensitive. You may want to check if express already handles that for you in its transcription of the headers into an object with properties, or if you need to go through all the headers until you find a match with /authorization/i (i for is ignoring the case).

**Comment by jsdelfino** [comment]
@sasrin is that still an issue? Thanks

**Comment by sasrin** [comment]
Tested following variations to access header authorization field value  

```
req.headers.authorization
req.headers.Authorization
req.get('authorization')
req.get('Authorization')
```

with following curl options

-H "AUThorization: test"
-H "Authorization: test"
-H "authorization: test"

_req.headers.Authorization_ always returned _undefined_ and all other variations returned correct values all the time.

So concluding that the express takes care converting all header field names into all lowercase property names.

**Comment by sasrin** [comment]
Since we are using _req.headers.authorization_  to access the authorization header field, closing this issue as not a bug.
