### ISSUE TITLE
re-meter/re-rate usage

### ISSUE THREAD

**Issue by sinduri** [cloudfoundry-incubator/cf-abacus#145]
In a scenario where a service is already metered/accumulated/aggregated and rated, we would want to re do the pipeline for a subset of the usage such as (by org/service/service-instance /month etc)

It would be needed in cases such as when there was a defect in the getting the price or if a resource provider is onboarding a resource and will have to change definition.

**Comment by sinduri** [comment]
A scenario would be, after submitting the usage, in the account service plugin, we identified the account and the currency from the account object and rated to that currency. And later(most likely outside of the slack window), it was found that the currency code on the account was incorrect and fixed and now we would like to fix the rated usage as well for that account.

**Comment by jsdelfino** [comment]
Once your usage has been rated (even with an incorrect currency), and has appeared in usage reports (which can be obtained in real time), or has appeared on a bill sent to a customer, I think the simplest and cleanest way to compensate for the erroneous rating would be to submit  compensating instances of that usage (maybe even with negative numbers to offset an overcharge for example), or even simpler, submit a 'correction' usage doc containing a metric carrying the charge adjustment.

Would that work?

**Comment by jsdelfino** [comment]
No more comments on this one in the last 10 days, so I'm going to assume that everybody is happy with what I suggested in my last comment. Please reopen if more discussion is needed. Thanks.
