### ISSUE TITLE
Extending the abacus pipeline

### ISSUE THREAD

**Issue by sinduri** [cloudfoundry-incubator/cf-abacus#146]
Currently, the way we are pulling account -level data is fetch all the reports for all the organizations and do the aggregation to the account at the REST API level

We do not want to do this and include additional processing steps to the pipeline specifically after the rate at the organization, to do rating at the account level. Essentially we want to extend the pipeline

**Comment by jsdelfino** [comment]
@sasrin is currently moving the execution of the rating functions to the aggregator service. Once that's done you'll be able to configure the aggregator service's 'sink' to point to your account level rating service.

**Comment by sasrin** [comment]
Delivered as part of #184.
