### ISSUE TITLE
Resource definition - Different metrics formula for different plan.

### ISSUE THREAD

**Issue by KRuelY** [cloudfoundry-incubator/cf-abacus#153]
Hi,

Currently the pricing config in account-stub has plans in it(which will allows different plans to have different prices). For example object-storage has one plan called 'basic'.

On the other side, the object-storage resource definition in provisioning-stub does not use any plan in it. This would not create any problem if all plans are assumed to use the same meter, accumulate, rate, summarize, and charge functions. 

In some situation, different plan might have different functions. Example for object-storage:
plan basic: no incremental model( #152  ). plan super: use incremental model. Or where different plan have certain discounts / disregarding a metric in the rate function (plan super will have x gb storage free while basic is not.)

We might not face this problem now, but it is very possible in the future.

Any thoughts? Thanks

**Comment by jsdelfino** [comment]
We'll need to add a plan_id to the resource and price configs and also pass that plan_id through the APIs that retrieve them.

**Comment by BetaFood** [comment]
This is now in with c619c2f5212bd2debecd4986956fb316582f2423

The resource config structure has changed from
```javascript
{
	"resource_id":"",
	"effective":0,
	"metrics":[],
	"measures":[]
}
```

to

```javascript
{
	"resource_id":"",
	"effective":0,
	"plans": [{
		"plan_id":"",
		"metrics":[],
		"measures":[]
	}]
}
```
