### ISSUE TITLE
Units in Reports

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#154]
The organization report shows the names of the aggregated quantities without the units. It would be good to have both the names and the units for each metric in the report.

**Comment by jsdelfino** [comment]
IMO adding the units to all aggregated and accumulated usage docs would unnecessarily bloat them (as opposed to just having a side configuration of the units if you need to display these units in your UI for example).

For that reason, I'm not planning to implement this change, so I'm closing the issue for now.

If anybody wants to submit a pull request with the changes to implement this and clear evidence that they're not causing a significant performance degradation, then please feel free to reopen this issue with the pull request. Thanks!
