### ISSUE TITLE
Question on graphQL format

### ISSUE THREAD

**Issue by midoblgsm** [cloudfoundry-incubator/cf-abacus#157]
Hi,
I'am working on a swagger description for Abacus API and found that the operation:
```GET /v1/metering/aggregated/usage/graph/:query```
returns 200 to indicate success with a usage summary report JSON document.
But I didn't find any JSON description for the returned document. Do you have this description in another doc, or is it a typo and the API returns just a graph file?
Thanks

**Comment by jsdelfino** [comment]
With GraphQL the response contains the fields you've asked for in the query... so there's not going to be a fixed JSON schema for the response, unless you want to write a JSON schema where every field is optional. You could do that but I'm not sure if that'd be very useful. Do you absolutely need a JSON schema for your Swagger description?

**Comment by jsdelfino** [comment]
@midoblgsm Any more comments or questions on this?

**Comment by maximilien** [comment]
@jsdelfino the current description allows for any object so should match the intent of the API.

/cc @midoblgsm let's try it that way and see how far we go with some tests brokers

**Comment by jsdelfino** [comment]
OK makes sense. Closing for now, please reopen later if there's problems with that approach.
