### ISSUE TITLE
Need to upgrade to Babel 6

### ISSUE THREAD

**Issue by jsdelfino** [cloudfoundry-incubator/cf-abacus#163]
Getting the following deprecation warning:
npm WARN deprecated babel-core@5.8.33: Babel 5 is no longer being maintained. Upgrade to Babel 6.

**Comment by jabrena** [comment]
Hi,

The whole project is using Babel?

**Comment by jsdelfino** [comment]
@jabrena Yes we're using Ecmascript 6 and Babel.

**Comment by jsdelfino** [comment]
Upgraded to Babel 6 in 9797889.
