### ISSUE TITLE
BOSH job takes 16 mn to push apps to CF

### ISSUE THREAD

**Issue by jsdelfino** [cloudfoundry-incubator/cf-abacus#164]
The BOSH release errand job contributed in #129 takes a very long time (16 mn in my test env) to deploy the Abacus apps to CF, as it doesn't parallelize the staging and starts like our other deployment scripts do. @rajkiranrbala described a possible solution to this problem in #129.

**Comment by jsdelfino** [comment]
Not so much of a problem right now so moving to a different milestone.

**Comment by rajkiranrbala** [comment]
I tried to push the applications in parallel. However on BOSH Lite, some of the applications fail with "Staging Error: No available stagers"

**Comment by hsiliev** [comment]
The same is true when using 'npm run cfpush' or 'npm run cfstage', then 'npm run cfstart'

The staging resources might be limited on real CF systems as well. We might need to limit the parallel push/stage processes.

**Comment by hsiliev** [comment]
Bosh release is deleted with 1.1.0 as we do not use it productively and no longer support it actively. All this made it look outdated and non-working.
