### ISSUE TITLE
Failed build (local)

### ISSUE THREAD

**Issue by piotrprzybylski** [cloudfoundry-incubator/cf-abacus#174]
With the commit d9e337de33936a2ce0a183e2571e37e1d12de682, the local build fails with the following error:

piotrp@ubuntu:~/dev/nov/cf-abacus$ node -v
v0.12.7
piotrp@ubuntu:~/dev/nov/cf-abacus$ npm -v
2.11.3

> node_modules/abacus-authserver-stub: npm test
< node_modules/abacus-authserver-stub: npm test

> abacus-authserver-stub@0.0.2-rc.2 test /home/piotrp/dev/nov/cf-abacus/node_modules/abacus-authserver-stub
> eslint && mocha

/home/piotrp/dev/nov/cf-abacus/node_modules/abacus-authserver-stub/src/test/test.js
  43:11  error  Expected indentation of 8 space characters but found 10  indent
  44:11  error  Expected indentation of 8 space characters but found 10  indent
  47:11  error  Expected indentation of 8 space characters but found 10  indent
  54:11  error  Expected indentation of 8 space characters but found 10  indent
  59:11  error  Expected indentation of 8 space characters but found 10  indent
  64:11  error  Expected indentation of 8 space characters but found 10  indent
  65:9   error  Expected indentation of 6 space characters but found 8   indent

✖ 7 problems (7 errors, 0 warnings)

npm ERR! Test failed.  See above for more details.

**Comment by jsdelfino** [comment]
Did you actually have to modify code to fix the lint issues? If that's the case you may want to try this:
```
npm cache clean
npm run rebuild # from the abacus dir
```
as I'm guessing you may be running with outdated dependencies.

**Comment by piotrprzybylski** [comment]
After I updated to 3e6ea259476c3f674364bd1f2809edc900a3a642 and cleaned up the cache, the problem was resolved.
