### ISSUE TITLE
Identify what pricing was used to rate usage

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#175]
Is it better to have the accountId to be included as a part of the rated usage doc, to identify what pricing group was applied while the  aggregated usage doc was rated?

**Comment by jsdelfino** [comment]
Identifying what pricing was applied to rate the usage would make a lot of sense to me. I'm not sure that adding the account id to the usage doc achieves that goal though, as the pricing could evolve over time or be shared across multiple accounts for example. Also, an org belongs to an account so adding the account id on top of the org id which is already in the doc doesn't really provide any useful info as I understand it. So, instead I'd suggest to add an id to the price config, and include that id in the rated usage doc.

**Comment by jsdelfino** [comment]
I changed the issue subject to reflect the described requirement

**Comment by jsdelfino** [comment]
The id of the pricing plan used to rate usage is now included in the rated usage docs.
