### ISSUE TITLE
Abacus submodule READMEs lack usage details

### ISSUE THREAD

**Issue by csaroff** [cloudfoundry-incubator/cf-abacus#176]
I've been using many of the abacus submodules such as [abacus-retry](https://www.npmjs.com/package/abacus-retry), [abacus-request](https://www.npmjs.com/package/abacus-retry), [abacus-babel](https://www.npmjs.com/package/abacus-retry).  Some of these modules have relatively self explanatory usages, relying heavily on the documentation of the modules that they wrap in order to explain what they do and how to use them.  abacus-request is good example of this.

For some though, it is not obvious what they are for or how to use them ([abacus-partition](https://www.npmjs.com/package/abacus-partition) for example).  Every popular, open source npm module that I've used had an exhaustive or nearly exhaustive README detailing what the module was for and how to use it.

Even the modules which have the same API as the modules that they wrap should minimally contain details on the differences between the original module and it's wrapper.

For example, abacus-request could contain details about how it automatically parses JSON strings if they are json parsable.

__Original request__
```javascript
const request = require('request');
request('json-returning-url.com/api/getJSON', function(error, response, body) {
  // Need to run JSON.parse on the response body
  const info = JSON.parse(body);
});

```
__abacus-request__
```javascript
const request = require('abacus-request');
// Notice missing body in parameter list
request('json-returning-url.com/api/getJSON', function(error, response) {
  // No need to run JSON.parse
  const info = response.body
});
```

I think that improving the depth of the README's would be really helpful in improving the popularity of the abacus submodules.  I would use more of them myself if I didn't need to slosh through the code + tests to figure out how they worked.

**Comment by jsdelfino** [comment]
+1 for better READMEs, I'm marking this as open for contribution as well if you'd like to submit pull requests for these improvements. I'd suggest to keep the README informative enough to motivate a user to try the module out, but high level enough to gently push that user to read the source code, as that'll always be the reference, and a great way for that user to transition from 'external' user to active code contributor for the module.

**Comment by jsdelfino** [comment]
Nobody has stepped up to contribute any improvements to the READMEs yet so closing this issue for now, suggesting that folks submit pull requests to improve the individual READMEs instead.
