### ISSUE TITLE
Re-organize and normalize the usage aggregation data model

### ISSUE THREAD

**Issue by sasrin** [cloudfoundry-incubator/cf-abacus#183]
We need to re-organize and normalize the data model of the usage aggregations used by the reporting service to store usage from different consumers in different documents linked together to help control the size of the reports from big organizations.

Corresponding Pivotal Tracker User Story [#107598654] (https://www.pivotaltracker.com/story/show/107598654)

**Comment by jsdelfino** [comment]
This has been implemented. Usage for individual consumers is now stored in individual docs.
