### ISSUE TITLE
abacus-dataflow, generator functions in ikey and okeys

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#185]
The abacus-dataflow module has the reducer and the mapper objects which accepts functions that returns the keys. However it does not support generator functions. Can this be modified so that it can support generator functions as well?

**Comment by rajkiranrbala** [comment]
@jsdelfino I have a situation where i need to use async functions to infer the keys and times from the docs. I was able to change the dataflow module and all the applications in the pipeline to have generator functions for the keys and time. Do you have any suggestions to use async functions for keys?

**Comment by jsdelfino** [comment]
@rajkiranrbala the keys and times are normally derived from the input doc (without any dependencies on external context not present in the input doc). Can you give a bit more info here to help us understand why you'd need an async call here to derive the key/time from the input doc?

**Comment by rajkiranrbala** [comment]
@jsdelfino  I want do an account level aggregation. I am using the output document from org level aggregator as the input doc for account level aggregator. The org level aggregated doc contains organization_id which will be the input key for the reducer and the account_id will be the output key(s). In order to map the organization_id to the account_id, I need to query the account stub (if the mapping is not found in cache). I suggested including the account_id in the rated usage doc for the same purpose https://github.com/cloudfoundry-incubator/cf-abacus/pull/178 .

**Comment by jsdelfino** [comment]
OK I understand now. I think it's better to include the account id in the aggregated usage doc, as the idea of the key functions is that they should be able to produce the key from the document only without any other side context data. I will port pull request #178 to the latest code and I'm closing this issue as with that we won't need to make the key functions async.
