### ISSUE TITLE
Organization rating as a function of rating at the accumulator

### ISSUE THREAD

**Issue by sinduri** [cloudfoundry-incubator/cf-abacus#188]
When resource instance level rating comes into play, we would have to allow visibility of the instance level rating at organization level rating, in addition to just the org aggregated usage. 

For ex, the resource provider might provide discounts at the instance level, in which case the rating at the org level would be just a sum of the rated costs of all the instances.

**Comment by jsdelfino** [comment]
Could you give a more concrete example here maybe? That'll help us understand how to satisfy requirement, assuming it's not possible to satisfy it with the current set of accumulation, aggregation, rate and charge functions. Thanks!

**Comment by sinduri** [comment]
An example of it would be a resource measuring "DEVICES" and defining a plan which gives 100 DEVICES free per instance. 

In that case, the rate function at the instance level would be (accumulated_devices_per_instance -100)*price.

And the rate function at the organization/aggregation level would be (sum of costs of all the instances in that plan)

**Comment by jsdelfino** [comment]
I was waiting a bit to see if you were going to come up with a solution too, as I believe this should be pretty easy to do with the current code :)

IIUC each instance has 100 free devices and devices are paid on top of that. As you've probably seen with runtime usage metering for example, metrics and costs do not have to be just simple numbers, they can also be objects (typically with multiple numbers) that you can design to represent situations like this one.

For example you could use an object structure like this:
{
  free_devices: 99
  paid_devices: 0
}
then later
{
  free_devices: 100
  paid_devices: 5
}

That structure would be carried along the usage accumulation, and the several levels of aggregation, allowing you to rate the correct number of paid devices at each level (including the organization level). I think this would also allow you to give more useful info to your customers as you'll be able to show the detailed split of free vs paid devices at each level... including their numbers and costs.

Makes sense? BTW what I'm proposing here is just one of the many solutions to this, we can get creative as there are potentially other ways to represent the free/paid categorization that you're trying to implement.

HTH

**Comment by jsdelfino** [comment]
Closing as the question has been answered. Please reopen later if needed.
