### ISSUE TITLE
Allow configurable time and key separator in the abacus-dbclient

### ISSUE THREAD

**Issue by piotrprzybylski** [cloudfoundry-incubator/cf-abacus#19]
The separator between key and time elements of the uri is fixed to '-'. In some cases, using different character would be desirable, for example if keys already contain '-' therefore the separator should be configurable through the environment property.

**Comment by jsdelfino** [comment]
Using '-' as a separator doesn't work well with UUIDs for example which already contain '-' so I'm going to change that '-' to a '/' like we had initially, as this is a natural separator in URI paths.
