### ISSUE TITLE
abacus-express uses body-parser strict mode

### ISSUE THREAD

**Issue by csaroff** [cloudfoundry-incubator/cf-abacus#192]
I'm not sure if this is by design, but abacus-express uses the(default) strict mode of [body-parser's json function](https://github.com/expressjs/body-parser#strict). [1]

I was wondering if there are plans to make this configurable, or to change the abacus-express default to strict=false.

[1] https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/utils/express/src/index.js#L599

**Comment by jsdelfino** [comment]
I didn't have any plans to make this configurable, but can you help me understand why you'd want to turn strict mode off?

**Comment by csaroff** [comment]
Hey, yeah.  My use case is that I'd like my API to accept a string instead of an array or object.

**URL**
`/user/:guid/position`

**Method**
`PUT`

**Body**
`"Manager"`

**Comment by csaroff** [comment]
Thanks for the update!
