### ISSUE TITLE
Cost as Metered Units

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#193]
I was thinking about a situation where the service provider decides to submit the cost instead of metered usage. In such a situation a resource definition to accept cost as metered units might work. However what if the service provider decides to submit usage for a given time window, say last 1 month? How could this be handled?

**Comment by jsdelfino** [comment]
To do that try to define a 'cost' metric and submit usage with a start and end times set to the begin and end of the month.

**Comment by jsdelfino** [comment]
Closing as I've answered the question. Please reopen later if the suggested solution doesn't work.
