### ISSUE TITLE
How do we handle rating plan change for rate based usage submission 

### ISSUE THREAD

**Issue by sinduri** [cloudfoundry-incubator/cf-abacus#195]
The issue we want to address is with rate based usage submissions such as the runtime submission and a change in the rating plan/ price plan since the usage was last submitted.

An example of it is, App1 was started and running since the 2nd of the month and the runtime resource provider submits a  usage of 1GB with a { consuming: 2, consumed:0, since: '2016-01-02'}, at the point of the submission we associate this usage with a rating plan (gold) and price plan (gold-v1). Now when any of these plans change the accumulators and aggregator need to be made aware, so that the accumulation and aggregations happen to those tuples.

**Comment by jsdelfino** [comment]
I'm not sure I understand the scenario you're describing. Are you thinking about changing the price of usage after the service has been used and that usage submitted and processed?

**Comment by sinduri** [comment]
Yes, when the rating plan or the price changes after the usage has been submitted and processed.

**Comment by jsdelfino** [comment]
There are probably multiple solutions to this:

a) submit new usage when the pricing plan or rating plan changes, to start new usage accumulation and rating with the new rating and pricing 

b) define your price as an object recording the history of prices at different times during the month, allowing your rating function to apply the prices effective at different times

c) implement logic to handle rating and pricing changes in your charge function

Thoughts?

**Comment by jsdelfino** [comment]
I thought a bit more about this and I think that given that a combination of (b) and (c) should work well. Given that the rating and charge functions are produced and returned by the account plugin (aka stub) service, that account plugin can leverage its knowledge of the account (as it's passed the account id) and the evolution of its state over time (or the evolution of the prices applicable to that account) to return rating and charge function that will apply the correct pricing and charge over time.

Thoughts?

**Comment by jsdelfino** [comment]
Closing as the question has been answered with several proposed solutions. Please reopen if the proposed solutions don't meet the initial requirement. Thanks.
