### ISSUE TITLE
oauth module usage

### ISSUE THREAD

**Issue by csaroff** [cloudfoundry-incubator/cf-abacus#197]
I started looking into using the abacus oauth module for making api requests to cloud foundry and I ran into a bit of confusion about its usage.

I have an application which will make API requests to a cloud foundry instance.  The application will supply an oauth token in each of these requests.  Ideally, I'd like to cache the oauth token that I'm using in these requests in order to save a lot of API calls, but I certainly don't want to wrap all of my code in a [big callback](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/utils/oauth/src/test/test.js#L338).

I'm wondering if the following code is an appropriate way to use oauth.cache or if there is a better way to handle the callback ugliness.

```javascript
const systemToken = require('abacus-oauth').cache(authServer, myId, mySecret);

// My function that calls cloud foundry and requires and oauth token
const myFunction = (req, res, next) => {
  const functionContents = (header) => {
    // Do stuff with the header
  };
  systemToken() 
  ? functionContents(systemToken()) 
  || systemToken.start(err => functionContents(systemToken()));
});
```

Let me know if i'm way off base here.

**Comment by jsdelfino** [comment]
Look at how abacus-oauth is used in lib/aggregation/aggregator/src/index.js for example

The token setup there is much simpler than the code you're showing in your example:
1. call oauth.cache(...), then token.start(), proactively when your app starts;
2. start() will run a periodic background refresh of your token, so calling token() will always return a fresh token.

HTH

**Comment by jsdelfino** [comment]
Also, about wrapping your code in a callback, that's life with Node.js :) ... You will need to wait for the first token to be obtained from the OAuth server anyway before you proceed with using that token, and that can only be async as it requires network communication with that server, hence a callback. The approach I've described in my previous comment mitigates that a bit as the requirement for a callback moves from the middle of your business logic to your app startup logic (which usually requires other callbacks anyway at startup time if it's using Express, needs to set up connections to databases etc).

**Comment by jsdelfino** [comment]
@csaroff Did that answer your questions? Thanks

**Comment by csaroff** [comment]
@jsdelfino 

It does answer my question, but I don't see where you wait for token.start to finish in the abacus code.  When you [call start](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/aggregation/aggregator/src/index.js#L545) it looks racey.

Thanks for the help.

**Comment by jsdelfino** [comment]
Good catch :) I'll look at this closer and see how to fix it.

**Comment by jsdelfino** [comment]
Closing this one as #289 has been opened to report the potential racing condition in the OAuth token initialization code.
