### ISSUE TITLE
Limit the amount of parallel cf pushes

### ISSUE THREAD

**Issue by jcscottiii** [cloudfoundry-incubator/cf-abacus#206]
Depending on the computer resources running a local cloud foundry via bosh-lite, cfpush can be very burtal on the CPU and as a result the apps will fail to deploy at all because CF components will start to time out. 
Maybe have a `-jX` option or straight `--sequential` option to help with this.
cc: @danparsons

**Comment by jsdelfino** [comment]
Makes sense. Will look into it, unless somebody else beats me to it with a pull request :)

**Comment by hsiliev** [comment]
Parallel pack and push quickly exhaust the open files limit and makes it hard to run this automated in Docker based CI like Concourse.

I'm currently investigating the use of `xargs -P $JOBS`
