### ISSUE TITLE
Error running integration tests

### ISSUE THREAD

**Issue by jsdelfino** [cloudfoundry-incubator/cf-abacus#21]
I'm not able to run the integration tests.

The following steps:
```
npm run build
npm run itest
```
cause the following error:
```
npm run itest

> cf-abacus@0.0.1-dev.3 itest /Users/jsdelfino/Desktop/github/cf-abacus
> export THROTTLE=1 && foreach itest node_modules/:name npm run itest --

> node_modules/abacus-usage-collector-itest: npm run itest
< node_modules/abacus-usage-collector-itest: npm run itest

> abacus-usage-collector-itest@0.0.1-dev.3 itest /Users/jsdelfino/Desktop/github/cf-abacus/node_modules/abacus-usage-collector-itest
> mocha --command

Testing...


  abacus-usage-collector-itest

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "itest"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! abacus-usage-collector-itest@0.0.1-dev.3 itest: `mocha --command`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the abacus-usage-collector-itest@0.0.1-dev.3 itest script 'mocha --command'.
npm ERR! This is most likely a problem with the abacus-usage-collector-itest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --command
npm ERR! You can get their info via:
npm ERR!     npm owner ls abacus-usage-collector-itest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jsdelfino/Desktop/github/cf-abacus/node_modules/abacus-usage-collector-itest/npm-debug.log


npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "itest"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! cf-abacus@0.0.1-dev.3 itest: `export THROTTLE=1 && foreach itest node_modules/:name npm run itest --`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cf-abacus@0.0.1-dev.3 itest script 'export THROTTLE=1 && foreach itest node_modules/:name npm run itest --'.
npm ERR! This is most likely a problem with the cf-abacus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     export THROTTLE=1 && foreach itest node_modules/:name npm run itest --
npm ERR! You can get their info via:
npm ERR!     npm owner ls cf-abacus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jsdelfino/Desktop/github/cf-abacus/npm-debug.log
```

I'd suggest to include these integration tests in the main build to make sure we are all able to run them at all times and don't break them without realizing it (on Travis we should probably create a Travis build matrix to keep the current build reporting fast, build with unit tests only first, then build with the integration tests in a second step).

**Comment by jsdelfino** [comment]
The tests were failing because the Abacus services being tested couldn't bind to their tcp ports as I already had instances of the services running on my machine.

I'd suggest to make the tests use ephemeral port numbers instead as this issue will prevent multiple builds to run in parallel, and multiple tests within a build to run in parallel as well.

**Comment by sasrin** [comment]
Committed few changes(not all are related, but i think it is controversial) to get integrations tests in the main travis build at my fork, Could you review and provide ur comments.

https://github.com/sasrin/cf-abacus/commit/0c17dc605949d82537a738e4d1c6213dc6ed8233

https://github.com/sasrin/cf-abacus/commit/da069d6e167222530b1164c773f2f38a234f14c8

https://github.com/sasrin/cf-abacus/commit/9592ec7918a5b4a29ef1e082d3370574df3124af

https://github.com/sasrin/cf-abacus/commit/11269569fdfa6a1082cca32aa72dfb91132f03c5

**Comment by jsdelfino** [comment]
I've added some comments to the individual commits.

**Comment by sasrin** [comment]
Added Integration tests to travis build.

Need to work on how to use ephemeral ports while starting the applications for testing purpose. Is this support needed only for testing scenarios or even for a normal scenario?

**Comment by jsdelfino** [comment]
I was requesting this for testing, to allow concurrent build executions to use different ports.

**Comment by jsdelfino** [comment]
All integration tests are now running in the Travis builds without problems, and the ports used by all the Abacus services can be configured externally to accommodate various deployment environments.

I also realize that my initial suggestion to use ephemeral ports would not be convenient as the services wouldn't know each other's ports anyway, so I think that this issue is not relevant anymore at this point...

Closing it, please feel free to reopen if you disagree.
