### ISSUE TITLE
Usage with an error will block other usages from being passed to meter

### ISSUE THREAD

**Issue by KRuelY** [cloudfoundry-incubator/cf-abacus#233]
When we're submitting 5 usages at once, and one of the usage has an error, it will not let the other 4 passes. I'm suspecting that this is caused by the recent changes that I made to the collector. I'm currently working on the fix.

**Comment by jsdelfino** [comment]
The fundamental issue here is that the current API doesn't have a proper way to report individual usage doc processing success or error. I'm going to change the API as follows:
- submit a single usage doc per API call
- support API call batching like we do for all the other API calls we support in Abacus

**Comment by jsdelfino** [comment]
I'm actually not convinced that resource providers will get significant performance gains from batching the calls to the service collector API, so I'm not going to add a description of the batching support to the doc right away. We can always add that description later if needed.

**Comment by jsdelfino** [comment]
Will commit the change to the collector API shortly.
