### ISSUE TITLE
zip not specified as a requirement

### ISSUE THREAD

**Issue by prysmakou** [cloudfoundry-incubator/cf-abacus#239]
Please mention zip as a requirement.

**Comment by jsdelfino** [comment]
Thanks for reporting this.

I think it'd be nice to actually remove that dependency on the zip executable and instead change our cfpack tool to use one of the many Node.js zip modules available out there.

Thoughts?

**Comment by hsiliev** [comment]
With the removal of cfpack we now no longer use zip
