### ISSUE TITLE
How to get destination address for https://api.ng.bluemix.net 

### ISSUE THREAD

**Issue by naveensf** [cloudfoundry-incubator/cf-abacus#24]
Actually i am giving destination address like as below can you help how to get destination address 

abacus.json
[ 
  {"protocol":"all","destination":"127.0.0.1"}
]

command:
cf create-security-group abacus abacus_group.json

error:
Server error, status code: 403, error code: 10003, message: You are not authorized to perform the requested action

**Comment by sasrin** [comment]
Run the following command to find application instances IP addresses
```
CF_TRACE=true cf app <APP_NAME>
```
 
BTW, I see that you are getting 403 - Forbidden when trying to create a security group. If you are working on bluemix environment, you should be able to skip creating security groups and use public routes to get the applications talk to each other.

**Comment by jsdelfino** [comment]
@naveensf are you still having issues with this? Did @sasrin's answer help?

**Comment by sasrin** [comment]
Will close this issue sometime tomorrow unless there's an update. We can always reopen it later if needed.

**Comment by sasrin** [comment]
No update so assuming there is no issue at this point. Please reopen if this is still a valid issue.
