### ISSUE TITLE
Time window bounds intersect with the bounds of adjacent time windows

### ISSUE THREAD

**Issue by BetaFood** [cloudfoundry-incubator/cf-abacus#253]
Using 2016-01-01T00:00:00.000Z as an example.

If we want to get the bounds of January 1st for the date scale, it would return:
```json
{
  "from": "2016-01-01T00:00:00.000Z",
  "to": "2016-01-02T00:00:00.000Z"
}
```

the bounds for December 31st for the date scale is as follows:
```json
{
  "from": "2015-12-31T00:00:00.000Z",
  "to": "2016-01-01T00:00:00.000Z"
}
```

With a date of 2016-01-01T00:00:00.000Z, it would fall within the bounds of January 1st first, but it would also fall within the bounds of December first assuming a condition like
```javascript
if( time < from || time > to)
  return null
```

I'm wondering if the time window bounds calculation should return the end of the current day rather than the beginning of the last day for the to time.
ie: Return
```
"2016-01-01T23:59:59.999Z"
```
rather than
```
"2016-01-02T00:00:00.000Z"
```

Or should we leave it as is.

**Comment by jsdelfino** [comment]
How about keeping the time windows with the current bounds, but using the following expression to determine if a time t is inside a given time window:
```
const inside = t >= from && t < to;
```

**Comment by jsdelfino** [comment]
Converting the above expression to the negative form you had, that gives us the following:
```
const outside = t < from || t >= to;
```

**Comment by BetaFood** [comment]
I think I like that approach. The bounds still return the absolute bounds, but the user will be able to specify how to use those bounds like what you've specified earlier.

bed13e8265b8f54266219fde0f571616e072dee7 follows this method, so I think we can close the issue until further need.
