### ISSUE TITLE
Size of dependent node modules too big

### ISSUE THREAD

**Issue by vidyarthis** [cloudfoundry-incubator/cf-abacus#257]
I am using Abacus as a dependent node module for a rating application.
The size of just node modules is 573 MB this cause issues when we try
to push the application on cloud. 

This was one of the comments to give some background of what the issue can be.

**If you've been using some of the abacus submodules(abacus-request, abacus-express, etc), we've been noticing an explosion in the size of the modules in version >=0.0.4.  We have it tracked it down to the new version of babel that is being used and some extra polyfills that are being included.**

**Comment by jsdelfino** [comment]
I just rebuilt Abacus from scratch (including all Abacus apps and all Abacus util modules) and node_modules for **all** of Abacus (not just abacus-request and abacus-express) is just under 140Mb.

Also, I'm not sure about where the comment about an explosion in the size of the Abacus modules is coming from, and what it's actually saying as 'new version of babel' and 'some extra polyfills' are a bit too vague...

Closing this for now until there is evidence that a specific Abacus module is causing a reproducible problem.
