### ISSUE TITLE
aggregator and accumulator unit tests occasionally fail due to timing issues

### ISSUE THREAD

**Issue by BetaFood** [cloudfoundry-incubator/cf-abacus#26]
When running the unit tests for aggregator and accumulator. Occasionally the test case will fail with either the wrong number of post calls or the data being incomplete at the time of assertion. This happens occasionally during the travis build as well.

Below is a log snippet of the aggregator test.

> node_modules/abacus-usage-aggregator: npm test
> abacus-usage-aggregator@0.0.1-dev.3 test /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-usage-aggregator
> eslint && mocha
Testing...
Running Istanbul instrumentation on ../abacus-request/lib/index.js
Running Istanbul instrumentation on ../abacus-transform/lib/index.js
Running Istanbul instrumentation on ../abacus-yieldable/lib/index.js
Running Istanbul instrumentation on ../abacus-debug/lib/index.js
Running Istanbul instrumentation on ../abacus-events/lib/index.js
Running Istanbul instrumentation on ../abacus-lrudown/lib/index.js
Running Istanbul instrumentation on ../abacus-cluster/lib/index.js
Running Istanbul instrumentation on lib/index.js
Running Istanbul instrumentation on ../abacus-webapp/lib/index.js
Running Istanbul instrumentation on ../abacus-express/lib/index.js
Running Istanbul instrumentation on ../abacus-vcapenv/lib/index.js
Running Istanbul instrumentation on ../abacus-perf/lib/index.js
Running Istanbul instrumentation on ../abacus-hystrix/lib/index.js
Running Istanbul instrumentation on ../abacus-router/lib/index.js
Running Istanbul instrumentation on ../abacus-dbclient/lib/index.js
Running Istanbul instrumentation on ../abacus-partition/lib/index.js
Running Istanbul instrumentation on ../abacus-batch/lib/index.js
Running Istanbul instrumentation on ../abacus-retry/lib/index.js
Running Istanbul instrumentation on ../abacus-breaker/lib/index.js
Running Istanbul instrumentation on ../abacus-throttle/lib/index.js
Running Istanbul instrumentation on ../abacus-urienv/lib/index.js
Running Istanbul instrumentation on ../abacus-seqid/lib/index.js
Running Istanbul instrumentation on ../abacus-lock/lib/index.js
Running Istanbul instrumentation on ../abacus-aggregation-db/lib/index.js
Running Istanbul instrumentation on ../abacus-resource-config/lib/index.js
Running Istanbul instrumentation on ../abacus-eval/lib/index.js
Running Istanbul instrumentation on ../abacus-resource-config/lib/formula.js
  abacus-usage-aggregator
    ✓ constructs aggregated usage for an organization
    1) aggregates usage for an organization
  1 passing (2s)
  1 failing
  1) abacus-usage-aggregator aggregates usage for an organization:
      Uncaught AssertionError: expected 2 to equal 1
      + expected - actual
      -2
      +1
      
 >     at null._onTimeout (lib/test/test.js:731:57)

**Comment by sasrin** [comment]
Adding back the batch stub to avoid errors related to timing issue with batch processing.

**Comment by jsdelfino** [comment]
@sasrin see my comment on https://github.com/cloudfoundry-incubator/cf-abacus/commit/805e2dd3a505909d65ac85cc190664a20256d596.

Let's continue the discussion here and see if there's a way to keep the batching.
