### ISSUE TITLE
Webhooks should be authenticated

### ISSUE THREAD

**Issue by jsdelfino** [cloudfoundry-incubator/cf-abacus#261]
We've started discussing this topic in pull request #254, which introduces an HMAC signing of Webhook POST payloads using a shared secret as a way for the POST recipient to verify that the POST is coming from the Webhook that was actually subscribed to.

I'm moving the discussion here for increased visibility within the project and to make it easier for others to contribute to it.

My initial comment on the HMAC proposal:
> How does this secret + HMAC security mechanism fit with the OAuth security model we typically use everywhere else in Abacus and CF in general?

@csaroff response:
> A publisher should not send a subscriber its oauth token. Oauth tokens should be secret and should only be shared with a trusted application, correct?

**Comment by jsdelfino** [comment]
@csaroff, I'm not sure what you meant by **its OAuth token** in 'A publisher should not send a subscriber its OAuth token'.

I would agree that a service should not POST **any** OAuth token or an OAuth token containing scopes carrying too much authorization for example to an untrusted URL (a resource server, using the OAuth terminology), as that resource server could then use that token and its scopes to perform undesirable actions on other resource servers on the platform for example... but I don't see that scenario as different from any other POST to a (potentially compromised and therefore untrusted) resource server.

If the token you POST to a resource server only contains an identity and a set of scopes applicable only to that resource server (i.e. a JWT token allowing that resource server to verify that you're who you say you are, and that you're authorized to actually make that POST and carry the underlying action on that resource server), then I don't see why that token couldn't be shared with that resource server...

What I'm describing here is what we've been doing in Abacus so far (following what CF does in general with OAuth). Unless I'm missing something, I think that could work as well for the Webhooks we're trying to add to Abacus.

Thoughts?

P.S. I'd like @piotrprzybylski to chime in as well if possible as he has been working on our OAuth support in the past.

**Comment by csaroff** [comment]
> @csaroff, I'm not sure what you meant by its OAuth token in 'A publisher should not send a subscriber its OAuth token'.

In hindsight, I realize how vague this is.  What I meant was: "a service should not POST any OAuth token or an OAuth token containing scopes carrying too much authorization for example to an untrusted URL."

> If the token you POST to a resource server only contains an identity and a set of scopes applicable only to that resource server (i.e. a JWT token allowing that resource server to verify that you're who you say you are, and that you're authorized to actually make that POST and carry the underlying action on that resource server)

Allow me to diagram this for better understanding.  A publisher, P, sends messages to subscribers(resource servers) A, B, and C.  Along with each message, the publisher will send an OAuth token to each subscriber.  

```
    P
   /|\  
  A B C
```

This leads me to a few questions.
1. Do A, B, C all receive the same token?
2. Who issues tokens here?  Who verifies them?

The only efficient OAuth solution that I can think of is that each resource server is its own token authority. This means that A, B and C must all be able to issue OAuth tokens in a uniform way to the publisher, P, or supply their OAuth secret and algorithm to P in advance so that P may generate tokens for each one by itself.

Thoughts?

**Comment by jsdelfino** [comment]
> 1. Do A, B, C all receive the same token?
I'd start there, would that be a problem?

> 2. Who issues tokens here?
CF UAA issues the token, like for all other REST calls that we want to secure in CF, we get a token from UAA.

> Who verifies them?
The recipient verifies the token it receives, easy to do with a JWT library if it's a standard JWT token.

> The only efficient OAuth solution that I can think of is that each resource server is its own token authority.
Not needed as we have UAA for that, which can serve standard JWT tokens used and efficiently verified by multiple resource servers. 

Makes sense?

**Comment by csaroff** [comment]
> The recipient verifies the token it receives, easy to do with a JWT library if it's a standard JWT token.

A, B, C can verify the token with a *public key*.  UAA can sign a token with a *private key*.  I was under the mistaken assumption that JWT only supported symmetric encryption.

> Not needed as we have UAA for that, which can serve standard JWT tokens used and efficiently verified by multiple resource servers.

UAA holds onto the private key and generates jwt's with it.  UAA publicizes their public key and any subscriber can verify token signatures with that.

Let me know if I understood correctly here.

**Comment by jsdelfino** [comment]
AFAIK that's correct, JWT tokens can be signed using public/private key pairs.

**Comment by jsdelfino** [comment]
So do we have consensus on what to do with this?

I've not seen any objections from anyone (incl. @piotrprzybylski who I had pinged to review this) so if there's no objections I'd like to go with the approach discussed here.

**Comment by csaroff** [comment]
I was looking at the [UAA docs](https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst#get-the-token-signing-key-get-token_key) to find some info about retrieving a public key.  It appears that UAA is not required to use asymmetric encryption to sign jwt's.  What happens if your UAA instance is only setup to support symmetric encryption?

As an example, I attempted to find the public key for bluemix, but it seems that bluemix UAA isn't set up to support asymmetric encryption.

Thoughts?

**Comment by piotrprzybylski** [comment]
The JWT specification (https://tools.ietf.org/html/rfc7519#page-16) only requires HMAC SHA-256 algorithm to be implemented to sign the message (or token), the other algorithms are either recommended or optional. 
It follows from the JWS specification (https://tools.ietf.org/html/rfc7515#section-10.5) that shared key is used - same key to sign and validate the signature.

**Comment by jsdelfino** [comment]
Correct, both symmetric and asymmetric keys can be used.

**Comment by csaroff** [comment]
If your UAA instance is using symmetric encryption, then each subscriber would need to know the encryption secret **or** the subscribers would need to ask UAA if the jwt is valid.  If there are many incoming events, it could become expensive to make many API calls to UAA.  

One possible solution would be to have each subscriber cache valid tokens and ensure that the webhooks module also cached its own token.  I'm not sure how this would impact the new CF work into [revokable tokens](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/RRAN36QJDT3CF6K27W6PLRCTYPFU5FKS/) though.

**Comment by jsdelfino** [comment]
> If your UAA instance is using symmetric encryption, then each subscriber would need to know the encryption secret or the subscribers would need to ask UAA if the jwt is valid. If there are many incoming events, it could become expensive to make many API calls to UAA.

Correct, but not a problem AIUI. Symmetric encryption is used when all parties are trusted (and can therefore be trusted with the key). In environments where not all parties are trusted, asymmetric encryption should be used.

> One possible solution would be to have each subscriber cache valid tokens and ensure that the webhooks module also cached its own token.

Having a requester cache an OAuth token is common practice (you get a token from UAA and present it in outgoing interactions while it's valid). I wouldn't recommend to cache tokens to skip their validation in the recipient however.

Again, the bottom line is that symmetric encryption should only be used inside a circle of trusted parties, I'm not sure we need to get out of our way with some complicated caching mechanism or call UAA each time to work around that simple fact: if you can't trust your subscribers, then just use a public/private key pair and asymmetric encryption.

**Comment by csaroff** [comment]
> Correct, but not a problem AIUI. Symmetric encryption is used when all parties are trusted (and can therefore be trusted with the key). In environments where not all parties are trusted, asymmetric encryption should be used.

Let's say that a particular uaa instance has been set up using symmetric encryption.  The CF operators are tied in to the use of that type of signature validation and cannot change to asymmetric encryption.  Wouldn't this case provide an example of where UAA cannot be used  to facilitate this exchange?

If a UAA instance is tied in to use symmetric encryption, webhook subscribers will be unable to efficiently validate tokens.

**Comment by jsdelfino** [comment]
> If a UAA instance is tied in to use symmetric encryption, webhook subscribers will be unable to efficiently validate tokens.

I'm not following... Sorry. Unless I'm missing something, this is just business as usual with how symmetric encryption works. Parties using it need to have the shared key to encrypt and decrypt. If that doesn't meet your particular security requirements, then configure UAA to use asymmetric encryption instead. I don't think we should reinvent a whole lot of encryption mechanisms in a web hook utility when we already have well supported and well understood symmetric and asymmetric encryption mechanisms at hand from UAA, and already used for all the other flows (GETs, POSTs that are not web hooks etc) between the same services that will use these web hooks.

Closing for now unless there is a compelling argument in favor of not using the encryption already used in all the other Abacus service interactions. Please reopen if I mis-understood the issue at hand here.
