### ISSUE TITLE
The /log route is not secured by SECURED

### ISSUE THREAD

**Issue by danparsons** [cloudfoundry-incubator/cf-abacus#262]
The /log route available in all abacus apps to provide real-time logging configuration changes is not secured by the SECURED env var. This is a potential attack vector, and at least in my own installation, enabling debug logging produces so much traffic that it occasionally crashes our central logging system.

**Comment by danparsons** [comment]
cc @jcscottiii

**Comment by jsdelfino** [comment]
The /log routes are now secured when SECURED=true, requiring an OAuth token with an abacus.debug scope.

**Comment by jsdelfino** [comment]
I also renamed /log to /debug in 1b60a9d to be more consistent with the abacus-debug module name and DEBUG env variable.
