### ISSUE TITLE
Report queries using graphql don't work for all kinds of quantities/costs

### ISSUE THREAD

**Issue by BetaFood** [cloudfoundry-incubator/cf-abacus#263]
Opening an issue to discuss resolving this problem.

Currently, we have graphql support in abacus. However, due to the strongly typed nature, this doesn't quite work on all possible metrics. The current report schemas assign a GraphQLFloat to both the cost and quantity. This definitely is not always the case as seen in something like the memory metric from our linux-container sample. The cost and quantity in that metric are objects.

Using the queries from the reporting unit tests
```javascript
        // Query with no sub selections in quantity
        const query1 = '{ resource_instance(organization_id: ' +
          '"org", consumer_id: "con", resource_instance_id: "ins", ' +
          'plan_id: "basic", metering_plan_id: "basic-test-metering-plan", ' +
          'rating_plan_id: "basic-test-rating-plan", pricing_plan_id: ' +
          '"test-pricing-basic", time: 1456185600000) { organization_id, ' +
          'consumer_id, resource_instance_id, plan_id, ' +
          'accumulated_usage { metric, windows { quantity }}}}';

        // Query with sub selections in quantity
        const query2 = '{ resource_instance(organization_id: ' +
          '"org", consumer_id: "con", resource_instance_id: "ins", ' +
          'plan_id: "basic", metering_plan_id: "basic-test-metering-plan", ' +
          'rating_plan_id: "basic-test-rating-plan", pricing_plan_id: ' +
          '"test-pricing-basic", time: 1456185600000) { organization_id, ' +
          'consumer_id, resource_instance_id, plan_id, ' +
          'accumulated_usage { metric, windows { quantity { consumed }}}}}';
```

In the first query, since, an object is not a float, GraphQL returns null as the result. The second query, causes GraphQL to return with a list of errors since the subselection itself was never defined in the schema and thus an invalid query.

**Comment by BetaFood** [comment]
One possible way of achieving with a slight change to the schema is utilizing a list of key/value pairs for quantity/cost. Using:
```JSON
{
  "consuming": 5,
  "consumed": 0,
  "since": 1456871328000
}
```
as an example, this could easily be represented as:
```javascript
[
['consuming', 5],
['consumed', 0],
['since', 1456871328000]
]
```

I think there's a couple of things to consider here though:
* If the quantity/cost is changed to a list of key/value pairs, how would we go about returning a flat scalar like some metrics return right now?
* This won't account for an even more nested structure

To accommodate for the 2nd point, I'm wondering if having an input like this would work:
```javascript
[
['consuming', 'now', 5],
['consuming', 'then', 1],
['consumed', 'now', 200],
['consumed', 'then', 0]
]
```
which would result in:
```JSON
{
  "consuming": {
    "now": 5,
    "then": 1
  },
  "consumed": {
    "now": 200,
    "then": 0
  }
}
```

And potentially, a scalar could be represented as
```javascript
[[null, 500]]
```

Since aggregator would be the one writing these docs, odd inputs that mix the various scenarios detailed above together shouldn't come up as actual data.

Thoughts?

**Comment by jsdelfino** [comment]
Fixing this by adding an new ```anyType``` type (mapped to an ```anyOf``` JSON type and a ```GraphQLScalarType``` GraphQL type) to our schema module, then changing the types of usage ```quantity``` and ```cost``` to that new ```anyType```.

**Comment by jsdelfino** [comment]
See commits e27cb03, 2d48ea1 and 9641607 for the code changes.
