### ISSUE TITLE
CF bridge routes are not secured when SECURED=true

### ISSUE THREAD

**Issue by jsdelfino** [cloudfoundry-incubator/cf-abacus#269]
The following routes into the CF bridge app:
```
/v1/cf/bridge
/batch
```
are not secured when SECURED=true.

When the SECURED env variable is true, these routes should require an OAuth token containing an abacus.usage.read scope, and reject unauthorized requests with an HTTP 401 status.

**Comment by hsiliev** [comment]
I'm currently re-factoring the bridge and as part of this I will remove the endpoint providing statistics. I will add the use of `perf` and a debug interval timer that will log statistics similar to this one: https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/utils/couchclient/src/index.js#L272-L280
