### ISSUE TITLE
GraphQL schema doc doesn't include recent schema changes

### ISSUE THREAD

**Issue by jsdelfino** [cloudfoundry-incubator/cf-abacus#271]
The GraphQL schema doc in doc/api.md doesn't include the recent schema changes (in particular the changes that introduced time windows.) That documentation needs to be updated to match the latest schema.

**Comment by betafood** [comment]
I believe this was actually fixed by 77588ec4ee13440b17a2783f80c3f469ff17de6e and acb0b742781f5cc5540d0e3d1dfed87896b3f7fd but I never closed this issue. Everything should be up-to-date with the current structure. Closing this now.
