### ISSUE TITLE
abacus-request provides no defaults method.

### ISSUE THREAD

**Issue by csaroff** [cloudfoundry-incubator/cf-abacus#272]
The popular request library that abacus-request is based on currently provides a method, [defaults](https://github.com/request/request#requestdefaultsoptions), which returns a new request object with the given options set as default for each call to request.  abacus-request should implement this method to allow module consumers to do things like set the default http method to post.

```javascript
const request = require('abacus-request').defaults({ method: 'post' });
```

or to set default http headers.

```javascript
const request = require('abacus-request').defaults({
  headers: {'x-token': 'my-token'}
});
```

**Comment by jsdelfino** [comment]
The Abacus request module also uses request.defaults internally, so I'm not sure about the effects of other calls to request.defaults on top of that (in particular I'm wondering if that'll still allow a shared connection pool to be used by all instances of Abacus request...) If somebody wants to provide an implementation of the defaults function I'll be happy to review it but I'll want to see some tests showing that these defaults can be combined with the internal Abacus request defaults.

**Comment by jsdelfino** [comment]
Closing this issue until somebody contributes an acceptable pull request for it. Please reopen if you feel like contributing such a pull request. Thanks!
