### ISSUE TITLE
Retrieving latest accumulated usage from the abacus-accumulator-accumulated-usage

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#274]
I have some questions on how the Accumulator works. Does the processed time stamp on the accumulator accumulated database represent the time at which the usage is processed? Let say the incoming usage from metering is logged at t1, t2, t3, then does it guarantee that it is processed in that order?

I am asking this question for we query the accumulator accumulated usage to see the usage of instances. We filter with the processed time stamp so that we get the accumulated at a point in time. However when we submit usage for a single instance and single consumer in batches, we saw that there is a mismatch between the processed time stamp and and the actual order in which it was processed. 

Here is the data from the accumulated usage for an instance ordered based on their processed times and the actual order in which it was processed based on the current and previous values in their quantities and also the processed field value.

```js
k/.../t/0001457395200000/0001457395500000 // Actually Processed Second at 1457494683507
{
  "previous": {
    "sum": 100,
    "count": 1,
    "avg": 100
  },
  "current": {
    "sum": 200,
    "count": 2,
    "avg": 100
  }
}


k/.../t/0001457395200005/0001457395500005 // Actually Processed Fourth at 1457494683509
{
  "previous": {
    "sum": 700,
    "count": 3,
    "avg": 233.33333333333334
  },
  "current": {
    "sum": 750,
    "count": 4,
    "avg": 187.5
  }
}


k/.../t/0001457481600000/0001457481900000 // Actually Processed First at 1457494683506
{
  "current": {
    "sum": 100,
    "count": 1,
    "avg": 100
  }
}


k/.../t/0001457481600005/0001457481900005 // Actually Processed Third at 1457494683508
{
  "previous": {
    "sum": 200,
    "count": 2,
    "avg": 100
  },
  "current": {
    "sum": 700,
    "count": 3,
    "avg": 233.33333333333334
  }
}
```
If I need to find the latest usage for March I query with the following options

```js
{
 startKey: '/k/.../t/0001459468799999/z',
 endKey: '/k/.../t/0001456790400000',
 descending: true,
 limit: 1,
 include_docs:true
}
```

What I get is the doc with key  ***k/.../t/0001457481600005/0001457481900005*** but what I expect to see ***k/.../t/0001457395200005/0001457395500005***

**Comment by BetaFood** [comment]
The timestamp in a document in accumulated-accumulated usage is not actually the processed time, but a combination of the usage's start & end time. In terms of accumulator, the input database(accumulator-metered) has the timestamp as processed time.

**Comment by jsdelfino** [comment]
Also, IIUC the way you're scanning that DB to determine the usage at a given time, it is highly dependent on the Abacus internal data format (which may evolve over time.) It'd be cleaner to implement this as a new API of Abacus, so I'd suggest to open a separate Github issue requesting the feature you need to that effect. Then (you with a pull request) or somebody else can implement the proper addition to Abacus providing that feature.

**Comment by jsdelfino** [comment]
I'm going to adjust the setting of the processed time field a bit to make that time closer to the actual processing time and production of output doc. I'll also add a processed_id field which could be used to filter or sort output docs by time. On the other hand, Ben is working on a proper implementation of the API which I believe you were trying to implement here. I'll let Ben comment on that separately.

**Comment by BetaFood** [comment]
8d3c2775707581815b24b335a8e4e6395748a0e3 adds an endpoint to the report where the document retrieved is based on the processed time of the organization report. The endpoint is as follows:
```
/v1/metering/organizations/:organization_id/resource_instances/:resource_instance_id/consumers/:consumer_id/plans/:plan_id/metering_plans/:metering_plan_id/rating_plans/:rating_plan_id/pricing_plans/:pricing_plan_id/aggregated/usage/:time
```

**Comment by jsdelfino** [comment]
I believe that @betafood's changes fixed that issue. Please reopen if that's not the case. Thanks
