### ISSUE TITLE
Abacus Hystrix and Eureka endpoints are not secured

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#276]
We expose /hystrix.stream and /health endpoints that are not secured. They expose a lot of information about the internals of Abacus pipeline.

IMHO they should be secured with abacus.system token, but this will break Eureka and Turbine.

More around monitoring secure Abacus installation:
https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/doc/monitor.md#secured-installation

**Comment by hsiliev** [comment]
Can we simply disable the endpoints (via environment variable for instance) until we find a better approach for monitoring?

**Comment by KRuelY** [comment]
I looked at turbine's [github](https://github.com/Netflix/Turbine/commit/0e924058aa4d1d526310206a51dcf82f65274d58) and it seems that the latest pull request is enabling basic auth to turbine. What we can do is secure the /hystrix.stream with basic auth.

**Comment by hsiliev** [comment]
Latest dashboard and Eureka also support basic auth, so it seems we can use basic for healthcheck and stream endpoints.

**Comment by KRuelY** [comment]
Okay I think securing them with basic auth is the way to go. The problem with turbine is we're using version 1.x, or at least that's what we have in the tutorial. The basic auth is only in the turbine version 2.x.

**Comment by KRuelY** [comment]
#287 made it so that /healthcheck and /hystrix.stream is only accessible by passing a basic authentication.

From the basic token, Abacus will get the bearer token from authorization server and authorize the user if the user has abacus.system.read. Closing.
