### ISSUE TITLE
Retrying unprocessed usage records

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#277]
I had a situation where my aggregator crashed and restarted quite a number of times. Though all the requests to collector returned with a status code 201, not all of them reached the end of the pipeline. Is there any mechanism to retry the records that were not processed? Also can the status code be changed from 201 to 408 in a case a request did not go through the end of the pipeline?

**Comment by jsdelfino** [comment]
AIUI this is the same issue as #245. When #245 gets fixed you'll get an error status when usage doesn't reach the end of the Abacus pipeline.
