### ISSUE TITLE
Data flow posting all output documents to the SINK

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#278]
With the changes in aggregator to detect duplicate usage docs, there are three docs that are generated for every accumulated doc. If a SINK is configured, all the three documents are posted to the SINK URL. Not all documents need to be posted to the SINK. Can the data flow module be modified that it can look for a certain key to determine if a document needs to be posted to SINK or not?

**Comment by jsdelfino** [comment]
Closing this issue as a solution has been described in #278.
