### ISSUE TITLE
Plan API not documented

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#282]
The REST calls in https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/plugins/provisioning/src/index.js#L328-L412 are not documented in the API doc.

**Comment by KRuelY** [comment]
Should be solved by 
0eb00b1ee89edf320cde2ac4b5b1e85a262d1759 and a2ead66ca59ad840f73858f3b42e0e727a647759.
