### ISSUE TITLE
Resource instance report API not documented

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#283]
The resource instance report API in https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/aggregation/reporting/src/index.js#L710-L722
is not documented.

**Comment by betafood** [comment]
4baf972e0e7e3f8fec0ae14c0c6f6db3ad4901dc should address this but only the english documentation was updated.

**Comment by jsdelfino** [comment]
Thanks for the fix. I'm going to close this issue and open a different one reporting the fact that our Japanese doc is outdated, since it's now missing more things than just this doc of the resource instance report API.
