### ISSUE TITLE
URL Encoding URL Parameters

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#285]
Some of the metering, rating and pricing plan that we use contain '/' in their ids. When these ids are passed as url parameters without encoding, it leads to a whole new path and results in a 404 while querying for the plan definition documents. To avoid this, the url parameters needs to be encoded.

**Comment by jsdelfino** [comment]
Can you provide a test showing what part of the Abacus code exhibits that issue? Thanks!

**Comment by rajkiranrbala** [comment]
I prefixed all the metering plans with '/k/'. The changes I made are in the following commit https://github.com/rajkiranrbala/cf-abacus/commit/e7919df5ce7dc53e72011bf3831813423a611c4b

The unit test for provisioning will fail for it passes the values without encoding the url parameter component

```sh

  abacus-request 4296 Sending GET request http://localhost:56175/v1/metering/plans//k/basic-object-storage '' +6ms
  abacus-request 4296 Sending GET request http://localhost:56175/v1/rating/plans/object-rating-plan '' +1ms
  abacus-request 4296 Sending GET request http://localhost:56175/v1/pricing/plans/object-pricing-basic '' +1ms
  abacus-request 4296 Received GET response 404 { error: 'Not found' } +23ms

abacus-provisioning-plugin
    ✓ returns resource instance info by org/space/app/resource/plan/instance (253ms)
    1) returns available metering, rating and pricing plans
    ✓ returns the type of a resource
    validating basic-analytics  metering plan
        validated basic-analytics  metering plan
    validating basic-object-storage  metering plan
        validated basic-object-storage  metering plan
    validating standard-object-storage  metering plan
        validated standard-object-storage  metering plan
    validating basic-linux-container  metering plan
        validated basic-linux-container  metering plan
    validating standard-linux-container  metering plan
        validated standard-linux-container  metering plan
    validating test-metering-plan  metering plan
        validated test-metering-plan  metering plan
    ✓ validates all test metering plans
    ✓ validates creation of new metering plans (206ms)
    ✓ validates creation of new rating plans (98ms)
    ✓ validates creation of new pricing plans (107ms)


  6 passing (780ms)
  1 failing

  1) abacus-provisioning-plugin returns available metering, rating and pricing plans:

      Uncaught AssertionError: expected 404 to equal 200
      + expected - actual

      -404
      +200
      
      at lib/test/test.js:128:33
      at Object.callback (/Users/rajkiranrbala/Projects/OpenSource/cf-abacus/node_modules/abacus-throttle/lib/index.js:17:44)
      at /Users/rajkiranrbala/Projects/OpenSource/cf-abacus/node_modules/abacus-request/lib/index.js:46:120
      at Request._callback (/Users/rajkiranrbala/Projects/OpenSource/cf-abacus/node_modules/abacus-request/lib/index.js:43:215)
      at Request.self.callback (/Users/rajkiranrbala/Projects/OpenSource/cf-abacus/node_modules/request/request.js:199:22)
      at Request.<anonymous> (/Users/rajkiranrbala/Projects/OpenSource/cf-abacus/node_modules/request/request.js:1036:10)
      at IncomingMessage.<anonymous> (/Users/rajkiranrbala/Projects/OpenSource/cf-abacus/node_modules/request/request.js:963:12)
      at _stream_readable.js:908:16
```

**Comment by jsdelfino** [comment]
AIUI this will be much more problematic that it looks at first glance...

- the encoding of variables participating in the composition of URLs should probably be done in the abacus-request module to avoid polluting all the business logic with encoding calls;
- URLs returned to clients should have their variable parts encoded as well as clients won't be able to distinguish between the parts of the URL that need to be encoded and the parts of the URL that can stay as is;
- CouchDB clients that need to work with doc ids composed out of variables containing slashes will need to do the same.

My recommendation at this point is to either avoid slashes in ids or encode them in the first place when you initially store them in your DB, as you'll then be able to work with a consistent representation of these ids from end to end.

If you still want to do partial encoding of ids containing slashes, please submit a pull request, after ensuring that it works end to end without causing more issues. I'm going to close this issue until somebody is able to reopen it with a proper pull request. Thanks!
