### ISSUE TITLE
Abacus releases should be reproducible

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#293]
Currently we only tag the releases, without fixing the dependencies. Therefore it is not easy to checkout old version (say 0.0.3) and build it. Sometimes this is not even possible due to the open ranges used for module dependencies.

We should publish the exact versions that we used to validate and release Abacus for each released version.

I believe we can do this with `npm shrinkwrap` to fix the dependencies, then store the `npm-shrinkwrap.json` in a `release` (or the `etc`) directory for future use. This file will be versioned by git, so checking out a specific release will also download the exact set of dependencies.

**Comment by jsdelfino** [comment]
I was planning to do this for the next release (which I'd like to cut next week during the CF summit) but I'm not sure we'll be able to use npm shrinkwrap yet for that release, as I believe folks were running into errors running npm shrinkwrap. I'll try and see if these errors are still there.
