### ISSUE TITLE
CF Event Retention

### ISSUE THREAD

**Issue by piotrprzybylski** [cloudfoundry-incubator/cf-abacus#30]
## CF Event Retention

There maybe a need to retain app usage events used for calculating usage. For example if 
 the usage calculation is used for billing, there maybe an audit requirement, or there maybe 
 a need to recreate usage calculation at the end of the billing cycle. 
The Cloud Foundry keeps the usage events, however the retention period is configurable, 
(as mentioned at https://www.cloudfoundry.org/how-to-bill-on-cloud-foundry/). It defaults 
to 31 days but maybe shorter and it may not be possible to extend it to the time required 
for the reasons mentioned above. 

## Possible Solution

The possible approach is to persist the CF events before processing
them in the `cf-bridge`. In that scenario, the first step could be to read the CF events, 
log them to the DB and then invoke `cf-bridge` with that event set. The persistence layer could 
be part of the bridge application or a different component responsible for persistence 
and then invoking `cf-bridge` through the rest endpoint.

**Comment by hsiliev** [comment]
If we have a flow of time-based usage events to Abacus, wouldn't we have the history of the usage as well? We should then be able to recreate  the billing cycle. 

Indeed we will be missing the real data, but the usage reports will have most of the important data.

**Comment by piotrprzybylski** [comment]
Yes, there would be history of submissions of usage, you would not have the source of submitted data, which may be required in some cases.

**Comment by hsiliev** [comment]
Trying to understand the rationale behind the proposal. What do you mean by "source" here? Things like org, space and data center are already part of the usage report.

**Comment by piotrprzybylski** [comment]
Source in that case is uniquely identifiable Cloud Foundry App Usage Event.

**Comment by hsiliev** [comment]
I see. So it is mostly about auditing and keeping history.

I like the idea of having an intermediate DB that stores the usage events. We are currently struggling to separate the concerns in `cf-bridge`. I wonder if we can split it in 2 (or even 3) micro-services that can:
- guarantee that events are in correct order (initial purge can make started events appear after stopped ones)
- transfer elder events from CF CCDB to the auditing DB
- report the usage (current `cf-bridge` minus the 1m old `after_guid` logic)

**Comment by piotrprzybylski** [comment]
Yes, I think separation would be the right approach, something similar to other abacus components. I think the purge would be rather infrequent (as discussed separately) so it could be combined with the service that retrieves events from CF and adds them to auditing DB (in the right order - elder events). The second service would be current `cf-bridge` submitting usage. It could get the events from the DB or expose REST api to let the first service pass the events directly.

**Comment by sasrin** [comment]
It's good to keep the CF events in a log db before submitting usage data to the usage collector and also log what has been submitted as well. That way we will have consistency across all our applications and would help us to generalize generalize the application flow.

**Comment by jsdelfino** [comment]
Last comment on the this was 8 days ago and there seem to be some consensus on the approach.
Closing the discussion for now, please reopen later if needed.
