### ISSUE TITLE
Abacus cli tools should be written in es6 

### ISSUE THREAD

**Issue by csaroff** [cloudfoundry-incubator/cf-abacus#302]
I was looking through some of the code for the abacus cli tools and it seems that it was all [written in es5](https://github.com/cloudfoundry-incubator/cf-abacus/blob/772fbf03c1c1d34b81fcd6fb320b45d07d68c52e/tools/mocha/src/index.js#L5).  There's even a comment in each of the files saying "Implemented in ES5 for now".

I was just wondering what was the reasoning behind this?  Is there any reason that the cli tools can't be written in es6 and transpiled back to es5 like the rest of the abacus modules?

**Comment by jsdelfino** [comment]
One of the reasons was to minimize the amount of dependencies required to bootstrap the whole dev environment. If you feel like converting them to ES6 and are able to do so without introducing any complications in the bootstrapping of the dev env, please feel free to submit a pull request. If you're not planning to submit a pull request soon, then please let me know and I'll close the issue (as leaving an issue that nobody is planning to fix anytime soon is not really useful). Thanks!

**Comment by csaroff** [comment]
Thanks for the response.  I was more curious than anything else as I'm currently writing a few node command line tools.
