### ISSUE TITLE
abacus-dbclient does not go to every bucket for querying for range. 

### ISSUE THREAD

**Issue by rohitvyavahare** [cloudfoundry-incubator/cf-abacus#308]
I am trying to query db with following query : 

```javascript
db.allDocs({
  include_docs: true,
  startkey: 't/' + startTime + '/k/',
  endkey:   't/' + endTime + '/k/zzzzzzzzzzzzzzzzzzz',
  descending: false
})
```

The query tries to get all keys from that specific time period, but it only goes to dbs which have keys in bucket one. 
When I turned on debug logs, it retrieves the empty key from  't/' + startTime + '/k/' and map it to bucket 1. 
Is this the expected behavior? 
As I am inserting into the db, the bucket function takes care of where to put that key with the time stamp. Shouldn't it work same way when I am querying the db? 

Here are the debug logs : 

``` bash
  abacus-dbclient 72278 Getting a list of docs { include_docs: true,
  startkey: 't/1459454474367/k/',
  endkey: 't/1460318474367/k/zzzzzzzzzzzzzzzzzzz',
  descending: false } +24ms
  abacus-dbclient 72278 Extracted key  from t/1459454474367/k/ +0ms
  abacus-dbclient 72278 Extracted time 1459454474367 from t/1459454474367/k/ +0ms
  abacus-dbclient 72278 Extracted time 1460318474367 from t/1460318474367/k/zzzzzzzzzzzzzzzzzzz +0ms
  abacus-partition 72278 Partitioning key , time range [ '1459454474367', '1460318474367' ], operation read +1ms
  abacus-partition 72278 Mapped time 1459454474367 to period 16891 +0ms
  abacus-partition 72278 Mapped time 1460318474367 to period 16901 +0ms
  abacus-partition 72278 Mapped key  to bucket 1372 +0ms
```

**Comment by rajkiranrbala** [comment]
Can you say how you initialize the db. The number of databases through which the query is spanned is dependent on the partitioning function.

**Comment by rohitvyavahare** [comment]
Hello Raj , thanks for reply.

Here is the snippet of initialization of db.
I am using partitioner from abacus db-partition module

``` javascript 
 const partitioner = partition.partitioner(partition.bucket, partition.period, partition.forward, partition.balance);
 let db = dbclient(
          partitioner,
          dbclient.dburi(dbUrl ? dbUrl : '', prefix),
          function(uri, opt, cb) {
           dbclient.dbcons(uri, opt, cb);
         });
```

I think that , if you see debug logs I posted in issue, allDocs query wrapper is extracting empty key from query and mapping it to 1372 bucket which is limiting its span.

**Comment by KRuelY** [comment]
Hi,

The key(/k/:key) is used to control which db partition gets queried. Without a key, the expectation would be to query from all db partitions, but the current implementation that we have does not support this capability.

You can submit a pull request to add this capability, where you have to go to all the db partitions and queried all docs between t1 and t2, combined the results, and sort the results. But 

The range query we implemented is pulling all docs between t1 and t2 in the db partition pointed by the result of resolving the key using the partitioning function.

I'm not sure what the use case is, but consider not using partition if your use case is to get all docs from all partitions or comes up with partitioning function that will group certain keys(or not use the key,but something else) together? Maybe this is easier for your use case.

**Comment by rohitvyavahare** [comment]
@KRuelY , Thank you for a reply.
