### ISSUE TITLE
Time Windows - Supporting accumulation function - MAX for an adhoc window

### ISSUE THREAD

**Issue by sasrin** [cloudfoundry-incubator/cf-abacus#31]
Trying to collect the use cases that we need to support so that we can discuss possible solutions based on the requirements:

Use case 1:  A storage service provider wants to charge a customer based on the current storage consumption.

Use case 2: An API service provider wants to charge a customer based on the # of calls made to an API.

**Comment by sasrin** [comment]
Use case 1: A storage service provider wants to charge a customer based on the current storage consumption.

Since this is a storage service, the service provider can not create an artificial time boundaries in which the provider can reset the quantity to zero at the beginning of the boundary.

Given the following accumulated/aggregated usage quantities - assuming that the usage quantities may go up and down based on the customer adding data or deleting data. 

Time | seconds q | minutes q | hour q | day q | month q | year q | forever q
-------|----------------|---------------|----------|-----------|-------------|---------|-----------
01:01:10 | 3 | 3 | 3 | 3 | 3 | 3 | 3 | 3
01:01:13 | 4 | 4 | 4 | 4 | 4 | 4 | 4 | 4
01:01:15 | 7 | 7 | 7 | 7 | 7 | 7 | 7 | 7
01:01:17 | 3 | 7 | 7 | 7 | 7 | 7 | 7 | 7
01:01:18 | 5 | 7 | 7 | 7 | 7 | 7 | 7 | 7
01:01:19 | 4 | 7 | 7 | 7 | 7 | 7 | 7 | 7


*Case A: For an adhoc window starting from 01:01:11 to 01:01:16, we expect the quantity be equal to 7. as that is the maximum consumption for that window*

*Case B: For an adhoc window starting from 01:01:16 to 01:01:20, we expect the quantity be equal to 5. as that is the maximum quantity we got inside that window*

**Comment by sasrin** [comment]
**Problem**

How would you find the max value for _Use case 1 - Case B_

**Proposed approach**

- Add an additional window(at the following usage records table, it's named as ‘q') to the existing windows list to store a set of current maximum values, or  
- Use the forever window to store the proposed values, or 
- Remove all other windows and use the forever window with the proposed values

Time | seconds q | minutes q | hour q | day q | month q | year q | forever q | q
-------|----------------|---------------|----------|-----------|-------------|---------|------------|------
01:01:10 | 3 | 3 | 3 | 3 | 3 | 3 | 3 | 3
01:01:13 | 4 | 4 | 4 | 4 | 4 | 4 | 4 | 4
01:01:15 | 7 | 7 | 7 | 7 | 7 | 7 | 7 | 7
01:01:17 | 3 | 7 | 7 | 7 | 7 | 7 | 7 | 7, 3
01:01:18 | 5 | 7 | 7 | 7 | 7 | 7 | 7 | 7, 5
01:01:19 | 4 | 7 | 7 | 7 | 7 | 7 | 7 | 7, 5, 4
01:01:20 | 5 | 7 | 7 | 7 | 7 | 7 | 7 | 7, 5, 5
01:01:21 | 6 | 7 | 7 | 7 | 7 | 7 | 7 | 7, 6
01:01:22 | 7 | 7 | 7 | 7 | 7 | 7 | 7 | 7, 7
01:01:23 | 5 | 7 | 7 | 7 | 7 | 7 | 7 | 7, 7, 5
01:01:24 | 8 | 8 | 8 | 8 | 8 | 8 | 8 | 8
01:01:25 | 0 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 0
01:01:26 | 1 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 1
01:01:27 | 2 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 2
01:01:28 | 3 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 3
01:01:29 | 4 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 4
01:01:30 | 5 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 5
01:01:31 | 4 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 5, 4
01:01:32 | 3 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 5, 4, 3
01:01:33 | 2 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 5, 4, 3, 2
01:01:34 | 1 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 5, 4, 3, 2, 1
01:01:35 | 0 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 5, 4, 3, 2, 1, 0
01:01:36 | 2 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 5, 4, 3, 2, 2
01:01:37 | 1 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 5, 4, 3, 2, 2, 1 
01:01:38 | 5 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 5, 5
01:01:39 | 3 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 5, 5, 3
01:01:40 | 6 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 6
01:01:41 | 8 | 8 | 8 | 8 | 8 | 8 | 8 | 8, 8
01:01:43 | 9 | 9 | 9 | 9 | 9 | 9 | 9 | 9
01:01:47 | 8 | 9 | 9 | 9 | 9 | 9 | 9 | 9, 8
01:01:58 | 10 | 10 | 10 | 10 | 10 | 10 | 10 | 10
01:01:59 | 16 | 16 | 16  | 16 | 16 | 16 | 16 | 16
01:02:00 | 13 | 16 | 16 | 16 | 16 | 16 | 16 | 16, 13
01:02:01 | 12 | 16 | 16 | 16 | 16 | 16 | 16 | 16, 13, 12 
01:02:03 | 15 | 16 | 16 | 16 | 16 | 16 | 16 | 16, 15
01:02:05 | 17 | 17 | 17 | 17 | 17 | 17 | 17 | 17
01:02:10 | 21 | 21 | 21 | 21 | 21 | 21 | 21 | 21
01:02:12 | 28 | 28 | 28 | 28 | 28 | 28 | 28 | 28
01:02:30 | 17 | 28 | 28 | 28 | 28 | 28 | 28 | 28, 17
01:03:27 | 4 | 28 | 28 | 28 | 28 | 28 | 28 | 28, 17, 4
01:03:54 | 2 | 28 | 28 | 28 | 28 | 28 | 28 | 28, 17, 4, 2
02:01:25 | 5 | 28 | 28 | 28 | 28 | 28 | 28 | 28, 17, 5
02:01:26 | 78 | 78 | 78 | 78 | 78 | 78 | 78 | 78
02:01:27 | 100 | 100 | 100 | 100 | 100 | 100 | 100 | 100
03:01:24 | 25 | 100  | 25 | 100 | 100 | 100 | 100 | 100, 25
03:01:25 | 12 | 100 | 25 | 100 | 100 | 100 | 100 | 100, 25, 12

**Queries**
- Ascending with less than or equal to end of a window and greater than start of a window , limit 1 => first record in the window
- Descending with less than or equal to end of a window and greater than start of a window, limit 1 => last record in the window

**Pseudocode to find a max value for a given window**

```
delta(first, last) =>
  If length of q at the last record is longer than that of the first record, 
    Then truncate the q at the last record to the same length as of the first record.
  Start with 0th index, 
     Find the first non-matching q value at the last record  or 
     Just get the q value of the last index at the last record
```
**Pros**
- Can find the max value for all kinds of windows(fixed, sliding and ad-hoc).
- Needs two queries and retrieves one record for each query.

**Cons**
- If metered quantity keeps going down then the quantity array grows at O(n)
- We store previous and current quantities, so the quantity array would grow at O(2n)

**Example windows and their max values**

start |  end | first, last and max q
------|----------|----------
01:01:11 | 01:01:11  |  not a valid window
01:01:11 | 01:01:12  |  no records = 0
01:01:11 | 01:01:16  |  4  and  7  =  7
01:01:11 | 01:01:17  |  4  and  7, 3  =  7
01:01:11 | 01:01:21  |  4  and  7, 6  =  7
01:01:11 | 01:01:22  |  4  and  7, 7  =  7
01:01:11 | 01:01:23  |  4  and  7, 7, 5  =  7
01:01:11 | 01:01:24  |  4  and  8  =  8
01:01:11 | 01:02:01  |  4  and  16, 13, 12  =  16
01:01:11 | 03:01:25  |  4  and  100, 25, 12  =  100     
| |
| |
| |
01:01:16 | 01:01:16  |  not a valid window
01:01:16 | 01:01:17  |  7, 3  and 7, 3  =  3
01:01:16 | 01:01:18  |  7, 3  and  7, 5  =  5
01:01:16 | 01:01:19  |  7, 3  and  7, 5, 4  =  5
01:01:16 | 01:01:20  |  7, 3  and  7, 5  =  5
01:01:16 | 01:01:21  |  7, 3  and  7, 6  =  6
01:01:16 | 01:01:22  |  7, 3  and  7, 7  =  7
01:01:16 | 01:01:23  |  7, 3  and  7, 7, 5  =  7
01:01:16 | 01:01:24  |  7, 3  and  8  =  8
01:01:16 | 01:01:25  |  7, 3  and  8, 0  =  8
01:01:16 | 01:01:32  |  7, 3  and  8, 5, 4, 3  =  8
01:01:16 | 01:01:35  |  7, 3  and  8, 5, 4, 3, 2, 1, 0  =  8
01:01:16 | 01:02:10  |  7, 3  and  21  =  21
01:01:16 | 03:01:25  |  7, 3  and  100, 25, 12  =  100
| |
| |
| |
01:01:17 | 01:01:18  |  7, 5  and  7, 5  =  5
01:01:17 | 01:01:19  |  7, 5  and  7, 5, 4  =  5
01:01:17 | 01:01:20  |  7, 5  and  7, 5  =  5
01:01:17 | 01:01:23  |  7, 5  and  7, 7, 5  =  7
| | 
| |
| |
01:01:33 | 01:01:34 | 8, 5, 4, 3, 2, 1 and 8, 5, 4, 3, 2, 1 = 1
01:01:33 | 01:01:35 | 8, 5, 4, 3, 2, 1 and 8, 5, 4, 3, 2, 1, 0 = 1
01:01:33 | 01:01:36 | 8, 5, 4, 3, 2, 1 and 8, 5, 4, 3, 2, 2 = 2
01:01:33 | 01:01:37 | 8, 5, 4, 3, 2, 1 and 8, 5, 4, 3, 2, 2, 1 = 2
01:01:33 | 01:01:38 | 8, 5, 4, 3, 2, 1 and 8, 5, 5 = 5
01:01:33 | 01:01:39 | 8, 5, 4, 3, 2, 1 and 8, 5, 5, 3 = 5
01:01:33 | 01:01:40 | 8, 5, 4, 3, 2, 1 and 8, 6 = 6
01:01:33 | 01:01:41 | 8, 5, 4, 3, 2, 1 and 8, 8 = 8
01:01:33 | 01:01:43 | 8, 5, 4, 3, 2, 1 and 9 = 9
01:01:33 | 01:01:47 | 8, 5, 4, 3, 2, 1 and 9, 8 = 9
01:01:33 | 01:01:58 | 8, 5, 4, 3, 2, 1 and 10 = 10

**Comment by jsdelfino** [comment]
I still need to think about this a bit more, but I'm not sure that it's going to be very convenient to define schemes like that for every single Math function (e.g. max, min, avg, median etc) and the combination of Math functions that resource providers may want to use to accumulate usage.

**Comment by sasrin** [comment]
Agree with this and we are going to read more about the problem before proceeding further on this.

**Comment by sasrin** [comment]
As the discussion is moving to time windows, closing this topic and will reopen if needed.
