### ISSUE TITLE
Need a way to use abacus rated usage data be fed to an Analytics platform like Apache spark or hadoop cluster.

### ISSUE THREAD

**Issue by vidyarthis** [cloudfoundry-incubator/cf-abacus#316]
At the moment there are APIs which can be used to fetch rated usage for each account every day to build this dataset. If we could provide some native support in the base code to meet this need, e.g. at the end of pipeline when a usage record is processed we push the JSON for rated usage to a persistent store. 

NOTE: This would not work for the scenario for runtime usage where the usage records are not submitted frequently we calculate usage based on state of the application as START/STOP boundaries. The data warehouse would have to handle runtime calculation using consumed/consuming semantics outside as part of daily data update for such instances.

**The data in Analytics platform should be capable of running queries for daily/weekly/monthly usage #s including quantity/cost at account/organization/space/instanceORapplication level. **

**Comment by rajkiranrbala** [comment]
@vidyarthis 
You can configure the application's sink to alter the pipeline. If you are interested in extending the pipeline then you need to configure the SINK and AGGREGATOR_SINK_APPS variables before starting the end point. [L520-L525](https://github.com/cloudfoundry-incubator/cf-abacus/blob/7fe8d8b461bd1ed5d6e9df0bfe0a6a569f0ab375/lib/aggregation/aggregator/src/index.js#L520-L525)

1. `SINK` says which host to post to. 
2. `AGGREGATOR_SINK_APPS` is required if you are distributing the requests based on they key. This parameter is optional.
3. `/v1/metering/aggregated/usage` is the path to which the data will be posted.


```
#This woud post the documents to http://example.com/v1/metering/aggregated/usage
export SINK=http://example.com
npm run start
```

**Comment by hsiliev** [comment]
@rajkiranrbala Added your explanation to https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/doc/conf.md#extending-abacus-pipeline

**Comment by jsdelfino** [comment]
Looks like the question has been answered by Raj so closing the issue as no further action is needed at this point.
