### ISSUE TITLE
Posting to multiple sink services.

### ISSUE THREAD

**Issue by KRuelY** [cloudfoundry-incubator/cf-abacus#321]
Is it necessary for dataflow to have the ability to post to multiple sink services?

For example: accumulator only post to the sink, aggregator. There might be a need to post the result of accumulator to an analytic service or any other services.

The post should be different from the sink, it should be a "post and forget" instead of post and wait for a response.

**Comment by rajkiranrbala** [comment]
This would address https://github.com/cloudfoundry-incubator/cf-abacus/issues/316

**Comment by jsdelfino** [comment]
I'd suggest to implement this in a separate component, and a separate service too. IIUC you're looking for a sort of fan-out service that takes an input and posts it to multiple targets. That's a very different pattern from the current dataflow map/reduce/groupBy patterns, which are all centered around running business logic to apply of map or reduce transformation to an input.
