### ISSUE TITLE
Endpoints to retrieve resource instances contributing to organization usage.

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#322]
I have a situation where I need to retrieve the organization's aggregated usage along with all the accumulated usage that contributed to the  org's usage. Though there is an endpoint to fetch the accumulated usage report, the database is queried for the org aggregated usage to get the list of accumulated usage ids. If the accumulated usage ids can be exposed as a part of the report or through a separate endpoint, that id can be directly used to fetch the report making one less call to the database.

**Comment by jsdelfino** [comment]
In which report would you like to see the accumulated usage ids? Are you talking about the aggregated usage report?

**Comment by rajkiranrbala** [comment]
A separate endpoint that would give the accumulated usage report of all the instances in an org at time t. i submitted a pull request https://github.com/cloudfoundry-incubator/cf-abacus/pull/325 for this.

**Comment by jsdelfino** [comment]
Couldn't that be integrated in the aggregated usage report instead? The current reporting strategy is to avoid a proliferation of different endpoints and instead have an object tree under one report that can be queried efficiently using GraphQL (allowing you to select the bits you want under that object tree.)

**Comment by rajkiranrbala** [comment]
I didn't think about that. Seems like a good idea. I can integrate that with the organization report.

**Comment by jsdelfino** [comment]
Closing as looks like the next step is to submit a pull request integrating the additional data in the existing organization report.
