### ISSUE TITLE
abacus-eureka-plugin application issue

### ISSUE THREAD

**Issue by Pratibha-28** [cloudfoundry-incubator/cf-abacus#323]
Below is logs of cf logs abacus-eureka-plugin --recent

OUT    ... 27 more
OUT 2016-05-13 11:40:33,321 WARN  com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient:129 [DiscoveryClie
nt-HeartbeatExecutor-0] [execute] Request execution failure
OUT 2016-05-13 11:40:33,325 ERROR com.netflix.discovery.DiscoveryClient:836 [DiscoveryClient-HeartbeatExecutor-0] [renew] Disco
veryClient_EUREKA/19ijfvagab7 - was unable to send heartbeat!
OUT com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
OUT    at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:111
)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.ja
va:89)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:9
2)
OUT    at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.ja
va:89)
OUT    at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:827)
OUT 2016-05-13 11:40:43,304 INFO  com.netflix.discovery.DiscoveryClient:807 [DiscoveryClient-InstanceInfoReplicator-0] [registe
r] DiscoveryClient_EUREKA/19ijfvagab7: registering service...
OUT 2016-05-13 11:40:43,308 ERROR com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient:83 [DiscoveryCli
ent-InstanceInfoReplicator-0] [execute] Request execution error
OUT com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused
OUT    at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
OUT    at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123)
OUT    at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
OUT    at com.sun.jersey.api.client.Client.handle(Client.java:652)
OUT    at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
OUT    at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
OUT    at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570)                                    [65/1968]
OUT    at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.register(AbstractJerseyEurekaHttpClient.
java:56)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:5
9)
OUT    at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHtt
pClient.java:73)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56
)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:5
9)
OUT    at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.executeOnNewServer(RedirectingEurekaHttp
Client.java:118)
OUT    at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java
:79)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56
)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:5
9)
OUT    at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:119
)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56
)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:5
9)
OUT    at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56
)
OUT    at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:810)
OUT    at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:103)
OUT    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
OUT    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
OUT    at java.lang.Thread.run(Thread.java:745)
OUT Caused by: java.net.ConnectException: Connection refused
OUT    at java.net.PlainSocketImpl.socketConnect(Native Method)
OUT    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
OUT    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
OUT    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
OUT    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
OUT    at java.net.Socket.connect(Socket.java:589)                                                                    [22/1968]
OUT    at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
OUT    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
OUT    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
OUT    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
OUT    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
OUT    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
OUT    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
OUT    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:115)
OUT    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
OUT    at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173)
OUT    ... 29 more
OUT 2016-05-13 11:40:43,310 WARN  com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient:129 [DiscoveryClie
nt-InstanceInfoReplicator-0] [execute] Request execution failure
OUT 2016-05-13 11:40:43,310 WARN  com.netflix.discovery.DiscoveryClient:812 [DiscoveryClient-InstanceInfoReplicator-0] [registe
r] DiscoveryClient_EUREKA/19ijfvagab7 - registration failed Cannot execute request on any known server
OUT com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
OUT    at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:111
)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56
)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:5
9)
OUT    at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56
)
OUT    at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:810)
OUT    at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:103)
OUT    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
OUT    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
OUT    at java.lang.Thread.run(Thread.java:745)
OUT 2016-05-13 11:40:43,310 WARN  com.netflix.discovery.InstanceInfoReplicator:107 [DiscoveryClient-InstanceInfoReplicator-0] [
run] There was a problem with the instance info replicator
OUT com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
OUT    at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:111
)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56
)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:5
9)
OUT    at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56
)
OUT    at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:810)
OUT    at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:103)
OUT    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
OUT    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
OUT    at java.lang.Thread.run(Thread.java:745)
OUT 2016-05-13 11:40:43,310 WARN  com.netflix.discovery.InstanceInfoReplicator:107 [DiscoveryClient-InstanceInfoReplicator-0] [
run] There was a problem with the instance info replicator
OUT com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
OUT    at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:111
)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56
)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:5
9)
OUT    at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
OUT    at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56
)
OUT    at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:810)
OUT    at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:103)
OUT    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
OUT    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
OUT    at java.lang.Thread.run(Thread.java:745)
ERR Instance (index 0) failed to start accepting connections
2016-05-13T07:40:58.82-0400 [App/0]      ERR
2016-05-13T07:40:58.82-0400 [API/0]      OUT App instance exited with guid 00e664b1-b79e-4620-b3e5-e7230d80999a payload: {"cc_partition"=>"default", "droplet"=>"00e664b
1-b79e-4620-b3e5-e7230d80999a", "version"=>"a52b481b-693b-43bf-ab27-fea472cd8a3d", "instance"=>"59b37ce306734647a2bff9ed95cfa8f8", "index"=>0, "reason"=>"CRASHED", "exi
t_status"=>-1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1463139658}
OUT Removing crash for app with id 00e664b1-b79e-4620-b3e5-e7230d80999a
OUT Stopping app instance (index 0) with guid 00e664b1-b79e-4620-b3e5-e7230d80999a
OUT Stopped app instance (index 0) with guid 00e664b1-b79e-4620-b3e5-e7230d80999a
abacus-eureka-plugin app is failing very frequently.
abacus-eureka-plugin         started           0/1  

while doing curl to app url throwing error 404
curl --compressed abacus-eureka-plugin.(cf apps domain)/eureka/v2/apps
404 Not Found: Requested route ('abacus-eureka-plugin.cf apps domain') does not exist.

port 9990 has been set to abacus-eureka-plugin app as a env variable

**Comment by Pratibha-28** [comment]
Below is content of cf-abacus/lib/plugins/eureka/manifest.yml 
applications:
- name: abacus-eureka-plugin
  host: abacus-eureka-plugin
  path: ../../../../eureka/eureka-server/build/libs/eureka-server-1.4.7-SNAPSHOT.war
#  path: .cfpack/app.zip
  buildpack: https://github.com/cloudfoundry/java-buildpack.git
  instances: 1
  memory: 1G
  disk_quota: 1G
  env:
    CONF: default
    DEBUG: e-abacus-*
    DB: abacus-pouchserver
    PORT: 9990
    NODE_MODULES_CACHE: false
    SECURED: false
    JBP_CONFIG_TOMCAT: "{tomcat: { context_path: eureka }}"
    # JWTKEY:
    # JWTALGO:

**Comment by rajkiranrbala** [comment]
> while doing curl to app url throwing error 404
> curl --compressed abacus-eureka-plugin.(cf apps domain)/eureka/v2/apps
> 404 Not Found: Requested route ('abacus-eureka-plugin.cf apps domain') does not exist.

There are no routes that match /eureka/v2/apps
The routes defined are 
```
GET /eureka/v2/apps/:app/:instance
POST /eureka/v2/apps/:app
DELETE /eureka/v2/apps/:app/:instance
```

> port 9990 has been set to abacus-eureka-plugin app as a env variable

Are you running the locally or on cf?
If you are running on cf, the app runs on the port specified by `VCAP_APP_PORT` and is accessible only by the route mapped to the app.

> Below is content of cf-abacus/lib/plugins/eureka/manifest.yml 
> applications:
> 
> name: abacus-eureka-plugin host: abacus-eureka-plugin path: ../../../../eureka/eureka-server/build/libs/eureka-server-1.4.7-SNAPSHOT.war # path: .cfpack/app.zip buildpack: https://github.com/cloudfoundry/java-buildpack.git instances: 1 memory: 1G disk_quota: 1G env: CONF: default DEBUG: e-abacus-* DB: abacus-pouchserver PORT: 9990 NODE_MODULES_CACHE: false SECURED: false JBP_CONFIG_TOMCAT: "{tomcat: { context_path: eureka }}" # JWTKEY: # JWTALGO:

From your manifest file, looks like you are not deploying the abacus-eureka-plugin but you are deploying the actual Eureka server with environment variables for abacus-eureka-plugin. You might want to check Eureka server's documentation

**Comment by jsdelfino** [comment]
@rajkiranbala, @Pratibha-28: From the stack trace, this looks like an error in the Netflix Eureka (Java) code.

IIUC what you're trying to do here, you've deployed a real Eureka server (as opposed to the little Eureka stub we have in Abacus) under app name abacus-eureka-plugin. That is a valid scenario. Our Eureka plugin stub is just there to simulate a real Eureka for testing without requiring to set up a real Eureka server. In production, you'll obviously want to use a real Eureka server, and again looks like that's what you're doing here. I'd only suggest to maybe name that Eureka app differently than abacus-eureka-plugin to avoid any confusion, but that's only a suggestion.

That being said, if there's an error in the Eureka server Java code, this issue should be opened again the Netflix Eureka server project instead :)

**Comment by jsdelfino** [comment]
@Pratibha-28 is this still an issue? I'm planning to close the issue soon as it's not something that will require a code change in Abacus anyway.

**Comment by rajkiranrbala** [comment]
@Pratibha-28 I am closing this issue now. Please reopen if you are facing issues with Abacus Eureka Plugin.
