### ISSUE TITLE
windows friendly folder names

### ISSUE THREAD

**Issue by parampavar** [cloudfoundry-incubator/cf-abacus#326]
The folder names like "node-couchdb:0.12" in /etc/concourse/docker do not git clone/checkout in Windows OS because the char ":" is not supported in Windows
Please fix this

**Comment by parampavar** [comment]
Hi,
Thanks for fixing the folder names.
I am not able to "npm run build" now, and see the following error
`
23 error Failed at the cf-abacus@0.0.5 build script 'etc/versions && npm run bootstrap && npm run babel && npm install && npm test'.
`
NOTE: I have the latest versions of node and npm. Please check the attached 
[npm-debug.log.txt](https://github.com/cloudfoundry-incubator/cf-abacus/files/291986/npm-debug.log.txt)

log

**Comment by hsiliev** [comment]
Can you please retry with node.js 5.11.1?

**Comment by parampavar** [comment]
Still the same 
[npm-debug-withNode5.11.1..log.txt](https://github.com/cloudfoundry-incubator/cf-abacus/files/294208/npm-debug-withNode5.11.1.log.txt)

**Comment by hsiliev** [comment]
Just tried to run the build with git-bash, cygwin and command prompt. Unfortunately none of these seem to work out of the box .

The problem surfacing and breaking the build is that etc/versions cannot be run. The actual problem, however is the use of *NIX scripting (including, but not limited to stuff like shebangs, env, bash, awk, sed, etc.).

Abacus is: 
* developed on Linux & Mac
* tested mainly on linux (https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/.travis.yml#L3-L7)
* running productively on CF's Ubuntu linux stemcells 

This means we don't know how much effort supporting Windows is and do we want to do this at all at the current moment.

You can create a bug/enhancement requesting Windows support. Hopefully there will be some demand so we can prioritize the issue.
