### ISSUE TITLE
Add Support for Separate Time Windows

### ISSUE THREAD

**Issue by BetaFood** [cloudfoundry-incubator/cf-abacus#33]
Been slowly working on implementing this design from @jsdelfino of supporting more than just day time windows in the usage.

To allow accumulation, aggregation, rating, and reporting of data across more time windows than just a day.

We will follow a model of storing the quantity:

Time | Seconds | Minutes | Hours | Days | Months | Year | Forever
-------|-------------|-----------|---------|--------|-----------|--------|------------- 
1420070400000 | 1 | 1 | 1 | 1 | 1 | 1 | 1
1420070430000 | 1 | 2 | 2 | 2 | 2 | 2 | 2
1420070520000 | 1 | 1 | 4 | 4 | 4 | 4 | 4
1420074000000 | 1 | 1 | 1 | 120 | 120 | 120 | 120
1420156800000 | 1 | 1 | 1 | 1 | 2880 | 2880 | 2880 | 2880

Quantity will store the usage incurred at that time in the window within the last second, last minute, last hour, last day, last month, last year, and forever.

Changes will have to happen at accumulator, aggregator, rate, and report.

Changes that I'm in the process of doing to reach this are:
* Quantity from a single object to a 7-length array of objects
  * The array will always be ordered in the following way: `[second, minute, hour, day, month, year, forever]`
  * Usage will be accumulated across those 7 time windows
* The state document will change its partitioning logic
  * Instead of partitioning to a db of [prefix]-YYYYMM-X, the state document will go to a db of [prefix]-X
* Lookup can be done by using the log documents
  * Given a time T, pick the latest document that has usage reported before the time T from the log
  * Currently in accumulator for instance, we have the logid as ` const alogid = dbclient.kturi(k, [day(u.end), seqid()].join('/'));` which may be problematic in doing this query logic in anything smaller than a day window. However, this id may be important for recovery, so we will need to figure out the cleanest way to do this.

**Comment by sasrin** [comment]
Db name is currently formatted using  [name]-PP-YYYYMM  and shouldn't the new db name be formatted using [name]-PP-VV -  where PP is the partition, VV is the document schema version as an epoch and YYYYMM is year and month as an epoch.

**Comment by jsdelfino** [comment]
Yes IMO using [name]-PP-VV would make more sense.

**Comment by BetaFood** [comment]
In terms of following this design with accumulator and aggregator, it was changing the quantity to a 7-length array.

When we get to rate, instead of making an equivalent 7-length array for costs. It'd be better to keep all the values associated with that quantity in one object(similar to the current and previous quantities in accumulator). Since it wouldn't make sense to just call it quantity despite having cost. Here's what the structure would most likely look like in terms of aggregated_usage:

`
{
  aggregated_usage: [
    {
      metric: 'memory',
      windows: [{
        cost: 0,
        quantity: 0
      },
      {
        cost: 0,
        quantity: 0
      },
      {
        cost: 1,
        quantity: 1
      },
      {
        cost: 24,
        quantity: 24
      },
      {
        cost: 720,
        quantity: 720
      },
      {
        cost: 8640,
        quantity: 8640
      },
      {
        cost: 86400,
        quantity: 86400
      }]
    }
  ]
}
`

**windows** would be holding the new quantity and cost in a 7-length array. Since charge & summary will also be added to this object during the report, the name ought to accommodate. At the risk of sounding redundant, would **usage** or **usage_amount** work here better, or is there other terms that would make more sense?

Thoughts? Suggestions?

**Comment by jsdelfino** [comment]
This was discussed on cf-dev there: https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/6MLMZX646V5MGAHMWQX4GXDACCMMOSOC/

**Comment by BetaFood** [comment]
Closing this since this design was implemented as part of this commit 5a985b9abb4f17e97da5d0d13f662ed89ada2ec1
