### ISSUE TITLE
abacus-aggregator-aggrgated-usage db size

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#337]
We were running Abacus for a month and we found that the size of abacus-aggregator-aggregated-usage was significantly huge when compared to the other databases. Observing the documents in the database we found the following

The top level document (org aggregated document) has a consumers array in every space and a resource instances array. Every time an accumulated usage is processed, all the arrays are copied and only two objects (consumer and resource instance) in the array are updated. As the number of resource instances and consumers increase in a given org, the array size increases causing the size of the document to increase.
To address this, we can do the following

  1.  Remove the resource instances array from the org aggregated document and create an additional document that just contains the reference to the accumulator accumulated document. The id of the document will be of the format   `/k/organization_id/resource_instance_id/consumer_id/plan_id/metering_plan_id/rating_plan_id/pricing_plain_id/t/seqid`.

  2. Remove the consumers array in every space. We already have a consumer aggregated document. We can do a range query to pick the last aggregated document

  3. For reporting purposes we need to have the list of all consumers and resource instances contributing to an organization's usage. For this we create two documents, one for consumer and one for resource instance with a _tk_ id with time being the beginning of month. 
    -  For consumers create a document with id `/t/beginning_of_month/k/organization_id/space_id/consumer_id`
    -  For resource instances create a document with id `/t/beginning_of_month/k/organization_id/resource_instance_id`

In order to query over a time range with multiple keys the dbclient must be modified so that it can search over multiple partitions.

**Comment by jsdelfino** [comment]
We discussed this today and Raj is going to implement a much simpler solution. We realized that a lot of space is wasted by doc ids (and to a lesser degree by the space ids) in the consumer array entries. Both the doc ids and space ids can be inferred from the document context (since the org id, space id, and processed time are already in the document) so we can simply remove these fields from the consumer array entries.

**Comment by jsdelfino** [comment]
@rajkiranrbala is this entirely fixed now? Can I close the issue or do you still have work to do to reduce the size of the resource instance array entries as well? Thanks.

**Comment by jsdelfino** [comment]
Closing as this has been fixed by the recent changes to the aggregated usage data model and the new usage sampling capability.

**Comment by jsdelfino** [comment]
Looks like the aggregated usage DB still contains a copy of accumulated usage for each resource instance. I'll fix that shortly.
