### ISSUE TITLE
Retrieving latest document using abacus-dbclient

### ISSUE THREAD

**Issue by piotrprzybylski** [cloudfoundry-incubator/cf-abacus#34]
Is there a specific query to pass to allDocs to retrieve the latest document from the db?  The id of the last document is unknown - for example when it was created using abacus-seqid. 

The following query 
    db.allDocs({
      startkey: 't/0001443852297863',  // value in the future
      endkey: 't/0001442852297863\uffff',  // recommended at http://pouchdb.com/api.html#batch_fetch
      descending: true,
      include_docs: true,
      limit: 1
    },
 fails with error:
     TypeError: Cannot read property '1' of null
      at key (lib/index.js:19:297)
      at rangeOp (lib/index.js:60:14)
      at Object.allDocs (lib/index.js:77:1)
      at Context.<anonymous> (lib/test/test.js:30:8)

Removing start/end key returns empty array as expected as the right partition/period cannot be found.

**Comment by jsdelfino** [comment]
The dbclient key() function https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/utils/dbclient/src/index.js#L52 expects a format like /k/.../t/... or /t/.../k/...

Looks like you're missing the /k/ part in your keys.

**Comment by piotrprzybylski** [comment]
Yes, the key is not specified because key is unknown. I would like to query to retrieve the most recent document added to db.

**Comment by jsdelfino** [comment]
> I would like to query to retrieve the most recent document added to db.

From which db partition? That key is used to control which db partition gets queried. Without a key, all db partitions would have to be queried... It doesn't look like this is supported by the current implementation, but it should be possible to add that capability if you'd like to try, although I doubt that blindly querying all partitions will perform very well.

I don't know the details of your data model, but an alternative would be to adjust your data model to not have to query a (potentially big or growing) number of db partitions to figure out the latest doc you stored... That may be easier.

**Comment by piotrprzybylski** [comment]
I agree that the search cannot be through all partitions, but if search was limited to specific number of partitions e.g. the partition corresponding to the current and maybe previous period it could be acceptable.

**Comment by jsdelfino** [comment]
By partition I meant a partition derived from a key (representing by a ```k/:key``` in your doc id), as opposed to a time or period of time (represented by a ```t/:time``` in your doc id).

Ranges queries currently work with a range expressed like 'range between t1 and t2 for a given key k' where k is mapped to a db partition by the partitioning function you've chosen to use with your particular db.

Like I said before you may be able to add some code to dbclient to run range queries over a set of db partitions, and then sort and assemble the results ordered by time.

If on the other hand you actually know the db partition you'd like to run the query on (but maybe you don't have a specific key to pass to target that partition) then you can always your own custom partitioning function that just takes the partition id in place of a key.

Hope that helps.

**Comment by jsdelfino** [comment]
No code change required at this point and the question has been addressed.
