### ISSUE TITLE
Secure REST endpoints

### ISSUE THREAD

**Issue by sasrin** [cloudfoundry-incubator/cf-abacus#35]
Need to secure REST endpoints.

**Goals**

- Only Resource Providers can submit usage records.
  - Resource Providers can submit usage records only for their resources.
- In case of processing errors, only an authorized user can reprocess usage records that are not yet processed. 
- Only authorized users can view usage reports.
  - Authorized users can view only their usage reports. 

See Pivotal Tracker  - [Abacus APIs need to be secured](https://www.pivotaltracker.com/story/show/101701306)

**Comment by sasrin** [comment]
**Design Constraints**

- Follow Cloud Foundry user authentication and authorization model.
- Do not _locally_ store user credentials and their roles.
- Do not ask for user credentials to do the authorization.

**Comment by sasrin** [comment]
Moving the discussions to cf-dev mailing list:

[[cf-dev] [abacus] Securing REST endpoints using OAuth bearer access token] (http://cf-dev.70369.x6.nabble.com/cf-dev-abacus-Securing-REST-endpoints-using-OAuth-bearer-access-token-tt2015.html)

Will use this issue/enhancement to just deliver the code.

**Comment by jsdelfino** [comment]
Implemented in v0.0.2-rc.1
