### ISSUE TITLE
Incorrect resolution of SINK url

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#360]
The dataflow module resolves the SINK url based on the keys of the output documents. This would result in a concurrency issue as the same entity group might be processed in different sink apps. 

For example lets consider two resource instances with ids `a278edbb-5fad-4395-bd74-f1599aca745e` and `0dc143c1-d88e-4d07-afd0-1ce6973d8649` in organization `a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27` with two instances of aggregator in the pipeline. 

If the accumulator produces the output documents with ids  
1. `k/a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27/a278edbb-5fad-4395-bd74-f1599aca745e/external:bbeae239-f3f8-483c-9dd0-de6781c38bab/basic/basic-object-storage/object-rating-plan/object-pricing-basic/t/0001467759632668` (SINK Partition 0) 
2.  `k/a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27/0dc143c1-d88e-4d07-afd0-1ce6973d8649/external:bbeae239-f3f8-483c-9dd0-de6781c38bab/basic/basic-object-storage/object-rating-plan/object-pricing-basic/t/0001467759632668` (SINK Partition 1)

each of them gets processed by different instances of aggregator causing the aggregation for org `a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27` to happen in parallel and might result in concurrency issues.

Update:
@jsdelfino  has already submitted a pull request https://github.com/cloudfoundry-incubator/cf-abacus/pull/359 to address this problem

**Comment by jsdelfino** [comment]
Pull request #359 adds the ability to optionally set on a dataflow two new functions (```sink.keys``` and ```sink.times```) that can produce sink partitioning keys/times separate from the dataflow's output keys/times. 

That pull request also makes use of that new capability in the meter, accumulator and aggregator services to configure keys/times that will address the correct sink partitions.

Note that I have not been able to reproduce the problem reported in this issue, even with various combinations of our perf tests, and that's the main reason why it's just a pull request at this point (I understand the theory behind the concurrency problem described by Raj's but have not seen evidence of it). So, before merging pull request #359 the team will need to effectively show evidence of the problem, probably with a new specific test, and ensure that the changes actually fix it.

**Comment by rajkiranrbala** [comment]
Pull request https://github.com/cloudfoundry-incubator/cf-abacus/pull/363 includes tests for running into concurrency issues and patch from pull request https://github.com/cloudfoundry-incubator/cf-abacus/pull/359 solves the issue.

**Comment by rajkiranrbala** [comment]
Resolved with https://github.com/cloudfoundry-incubator/cf-abacus/commit/a4d28325ba8ab1d9d91ce9fcfeab7cea2fd08433
