### ISSUE TITLE
Duplicate Detection while extending the Pipeline

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#364]
For the apps that follow the aggregator, currently there is no fool proof way to detect duplicates. If the duplicate detection doc id can be included as a part of aggregated docs, then we can use that information to detect duplicates while extending the pipeline.

**Comment by rajkiranrbala** [comment]
@jsdelfino and I discussed yesterday and came to a conclusion that we should include start, end, consumer_id, resource_instance_id and organization_id that in the org aggregated documents, so that the information can be used to identify the duplicates for apps that are being used to extend the pipeline,

**Comment by jsdelfino** [comment]
Fixed by PR #365
