### ISSUE TITLE
Differentiating runtime resource usage from service resource usage in the report

### ISSUE THREAD

**Issue by sinduri** [cloudfoundry-incubator/cf-abacus#37]
The report currently we reports the aggregated usage by resource, but we would like to have a way to identify that the resource usage is for a runtime/service.

**Comment by jsdelfino** [comment]
Abacus doesn't make any strong assumptions on the contents of your resource_ids. They just have to be valid URIs, and for the metering and aggregation logic they just identify resources, we don't really know if these resources are buildpacks, services provisioned by a CF service broker, external services provisioned separately, or entirely different types of resources...

Don't you already know if the resources you're working with are buildpacks, services or something else? Service providers and the runtime usage collectors know what kind of resources they're dealing with for sure...

**Comment by jsdelfino** [comment]
Any more comments on this?

**Comment by sinduri** [comment]
Yes, when we onboard the resources to the abacus, we will know they are services/runtimes, but at the report time I dont know how I can group a set of resources as services/runtimes/containers. 

Do you suggest to store a mapping of the resource_id to the service/runtime somewhere else and after fetching the report, do a look up in that mapping?

**Comment by jsdelfino** [comment]
> Do you suggest to store a mapping of the resource_id to the service/runtime somewhere else and after fetching the report, do a look up in that mapping?

If I had to do this myself as an integrator of Abacus, that's one of the options I'd look into. I would probably need to retrieve many other aspects of each resource anyway (its description, additional info about it, its creation date/time, whatever icon needs to be used for it etc) to present a nice view of each resource to my users.

Abacus is a metering service giving you usage and cost, basically numbers, for the resources incurring usage over a period of time. It is not a general repository for all the info about all the resources you've provisioned in the Cloud.

I also mentioned that Abacus resource_instance_ids are URIs. If you wanted to structure these resource_instance_id URIs to avoid collisions between ids produced by different (provisioning) domains (CF runtime and service providers, container providers, other types of resource providers) my advice would be to come up with a URI scheme like ```/runtime/<buildpack-id>```, ```/service/<cf-service-id>```, ```/otherstuff/<some-other-id>``` etc for example.

Such a URI scheme (again this is just an example) may help you organize your ids in a way that'd be convenient for you (although again I'm really not sure why you wouldn't have all the necessary info about your resources from your various resource provisioning systems way before you actually get an Abacus usage report).

**Comment by jsdelfino** [comment]
Any more discussion needed here? Doesn't look like this requires any code change in Abacus, so unless new data is provided to change that I'll close that issue in a day or two.

**Comment by sinduri** [comment]
We will explore the proposed solution and get back if we run into any issues.

**Comment by jsdelfino** [comment]
Sounds good. Closing for now, please reopen if needed later.
