### ISSUE TITLE
missing previous_running_instances in test metering plan

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#373]
previous_running_instances measure is missing in the test metering plan. 

https://github.com/cloudfoundry-incubator/cf-abacus/blob/04b4d6b37953e311a5f55a462e9e2624dd520782/lib/plugins/provisioning/src/plans/metering/test-metering-plan.js

https://github.com/cloudfoundry-incubator/cf-abacus/blob/04b4d6b37953e311a5f55a462e9e2624dd520782/lib/plugins/provisioning/src/plans/metering/basic-linux-container.js

https://github.com/cloudfoundry-incubator/cf-abacus/blob/04b4d6b37953e311a5f55a462e9e2624dd520782/lib/plugins/provisioning/src/plans/metering/standard-linux-container.js

**Comment by KRuelY** [comment]
Fixed in f0858cf36d1be039967708ca740ada50d25c763a and 7cbe1694a1c42ac76b96ce43c368fbbe934a3397
