### ISSUE TITLE
Names for ids in the report

### ISSUE THREAD

**Issue by sinduri** [cloudfoundry-incubator/cf-abacus#39]
The abacus report returns aggregated and rated usage by the ids. Shouldn't we include names with ids for the the entities in the report?

Can we enhance the reporting api to do a name-to-id look up before the returning the response?

**Comment by jsdelfino** [comment]
I thought about this today and my advice would be to keep these names out of the Abacus APIs for a number of reasons:

- they're not in the usage data submitted by the resource providers in the first place;

- storing the names of the entities referenced by usage data (and potentially other info like descriptions etc) with each usage doc would use a lot of space, and wouldn't be of a great value as the referenced entities can potentially be renamed after usage submission anyway;

- any cloud management UI obviously needs names for all the entities it displays, but that really doesn't have anything to do with metering and Abacus (e.g. a development tool UI, a management console, etc would need the names of an org, a space, an app as well);

- the good news is that CF already provides nice APIs to get the names of all the CF entities (and additional info as well, pretty much everything you'd like to display along these entities)... so I'm not sure why we'd duplicate that capability in Abacus.

That being said, if somebody can think of a way to improve the current Abacus APIs to make them easier to use without introducing significant problems (e.g. new requirements on resource providers to send the names, significant performance issues, or inconsistencies with -- or duplication of -- the existing CF APIs) and can volunteer to implement these improvements, I'll be happy to review any pull requests.

**Comment by jsdelfino** [comment]
No code change required at this point and the question has been addressed.

**Comment by sinduri** [comment]
Can we hook up the reporter api to fetch names for ids from a naming service(which could be using cf itself) and augment the report with the names?

**Comment by jsdelfino** [comment]
I'm not sure I understand what you meant by 'hook up the report API to fetch names for ids'. Can you elaborate a bit on what you have in mind?

**Comment by sinduri** [comment]
Upon further discussion, it seems abacus is not the right place to store the names or other details.
It should be the service to just produce the usage and cost numbers and a directory service which maintains all the relevant information for each entity would be the correct approach.

We will look into exploring that option of getting the report from abacus and augmenting it with names on the client side.

**Comment by jsdelfino** [comment]
OK looks like a reasonable resolution.
