### ISSUE TITLE
Runtimes api endpoint 404

### ISSUE THREAD

**Issue by johnmcteague** [cloudfoundry-incubator/cf-abacus#4]
The API docs mention a runtimes api endpoint (for apps) yet we get a HTTP 404 when hitting it. A quick scan of the code suggests it has not been implemented.

Is the goal to use the other endpoints for apps, given that metrics are generic enough that an application/services split may not be necessary? Having looked at what cf-abacus does (and I like it a lot, I think we can get huge benefit from it) , making things just a little more abstract and not having a hard apps/services split in the model (and perhaps also not forcing the model to mirror CF so tightly) would make it more flexible as we try to build a cloud platform featuring not just CF, but other runtimes also (much like Bluemix)

**Comment by jsdelfino** [comment]
> The API docs mention a runtimes api endpoint (for apps) yet we get a HTTP 404 when hitting it.  A quick scan of the code suggests it has not been implemented.

Yes, the code doesn't yet implement all the APIs listed in the doc. The idea here is to evolve the APIs and implementation together with the community over time.

> Is the goal to use the other endpoints for apps, given that metrics are generic enough that an application/services split may not be necessary

One goal is to get that kind of feedback and ideas from the community, so this is good feedback :smiley: 

We had that applications/services split in our initial implementation for Bluemix, and that's one of the main reasons why we still have it in the doc. Then, as the service usage APIs evolved over time to support more service providers, they became more generic and you're right that they could easily be used for runtimes too now.

For example -- just brainstorming here -- if we renamed 'service_id' to a more abstract 'resource_id' or made it a service_id | runtime_id choice in the schemas, and with a few other minor adjustments (we'd have to work out the details) we could probably make the same API work for runtimes as well.

**Comment by jsdelfino** [comment]
Check the comments in eede09f which describe how we've now combined service usage and runtime usage into a single (simpler) API. Let us know if this does what you had in mind or if you have any more ideas on this.
