### ISSUE TITLE
Add provisioning plans section to resource provider guide

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#417]
Resource provider guide describes plans, but does not mention what are the steps to add a new plan:
* add the plan files under https://github.com/cloudfoundry-incubator/cf-abacus/tree/master/lib/plugins/provisioning/src/plans
* change the provisioning plug-in mapping in the code: https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/plugins/provisioning/src/index.js#L75-L92

We can also document that Abacus will return 404 from `"x-app-name":"abacus-provisioning-plugin"` in case it cannot find a plan by `resource_type` and provisioning `plan_id`:
```
{"message":{"statusCode":404,"headers":{"x-powered-by":"Express","vary":"X-HTTP-Method-Override","x-process-id":"11191","x-uptime":"6588.827","x-heap-used":"26035080","x-node-version":"v6.3.1","x-app-name":"abacus-provisioning-plugin","x-app-version":"0.0.6-dev.7","x-app-index":"0","x-instance-id":"11191","x-instance-index":"0","x-response-time":"1.147ms","etag":"W/\"102-kqoiD7G1kWUwwzzXWZsfZg\"","date":"Thu, 01 Sep 2016 18:54:03 GMT","connection":"keep-alive"}},"statusCode":404,"headers":{"x-powered-by":"Express","vary":"X-HTTP-Method-Override","x-process-id":"11191","x-uptime":"6588.827","x-heap-used":"26035080","x-node-version":"v6.3.1","x-app-name":"abacus-provisioning-plugin","x-app-version":"0.0.6-dev.7","x-app-index":"0","x-instance-id":"11191","x-instance-index":"0","x-response-time":"1.147ms","etag":"W/\"102-kqoiD7G1kWUwwzzXWZsfZg\"","date":"Thu, 01 Sep 2016 18:54:03 GMT","connection":"keep-alive"}}
```

**Comment by KRuelY** [comment]
The mapping(simple lookup object) and the plans(require file) in the plugins are just the example, and what is important is the endpoints in [api.md](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/doc/api.md) is implemented. We are expecting the resource provider to come up with their own implementation of the plugins. We could write a documentation on how to add new plan in the example app plugins using the steps mentioned though. One extra step:

- Change the account plug-in mapping in the code: https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/plugins/account/src/index.js#L49-L67
