### ISSUE TITLE
Cost per resource instance

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#43]
There is a situation where I will have to obtain the cost for running each resource instance. The report apis available provides cost incurred at resource level. Is there any resource instance level reports that can be generated?

**Comment by jsdelfino** [comment]
You're correct that the reports do not include the usage _cost_ (and the corresponding _charge_) at the resource instance level. There are probably multiple ways to do that, including:

- additions to the aggregator and rating services to _'aggregate'_ usage and cost at the resource instance level (I've put _'aggregate'_ in quotes here as resource instances being the smallest entity we can get usage for, this wouldn't actually be an _'aggregation'_);

or

- the addition of rating on accumulated usage at the resource instance level, before aggregation, and of an API returning that accumulated usage as well as the corresponding cost and charge for a given resource instance;

We could discuss the details of these designs here if you'd like to try to add these capabilities.

Also note that (independent of which design you pick) AIUI the computed costs and charges would probably only be approximations, as factors like prorating, clip rating, overage fees or discounts for example would usually not participate in the calculation of the cost of usage at the level of individual resource instances. My understanding is that these kinds of adjustments typically apply to a total usage summary instead.

That leads me to a related question, just to make sure... Do you really need the __cost__ at the resource instance level or just the usage?

**Comment by rajkiranrbala** [comment]
In my case, I need the cost for running each resource instance. We can have a discussion and I can try implementing them.

As of the two ways that you mentioned and more ways that could possibly arise, should there be a way for a user to pick a strategy of the multiple strategies to accumulate/aggregate/rate the usage?

**Comment by jsdelfino** [comment]
OK sounds good.

With respect to allowing the user (i.e. a resource provider) to select a strategy for accumulation, aggregation and rating, there's already a lot of flexibility as the resource provider can define whatever meter, accumulate, aggregate etc functions for each resource. I'm not sure what else would be needed on top of that.

**Comment by jsdelfino** [comment]
> In my case, I need the cost for running each resource instance.

OK, I was asking because if you only needed the accumulated usage without the cost, that would be much simpler to implement for you as that accumulated usage (without the cost) is already there in the accumulated usage db.

FWIW, the implementation of an API to get the usage from that db would just have to do a simple db range query to get the latest accumulated usage doc before a selected time.

**Comment by rajkiranrbala** [comment]
For now I am trying to retrieve the resource instance level usage per day. When I checked the databases I see that the abacus-accumulated-usage-0-0 database contains resource instance level accumulations. However I see that the accumulation happens forever and no new records are created for different time periods. Is this the intended behavior?

**Comment by jsdelfino** [comment]
Yes until time window based accumulation is implemented. See my response to #54.
