### ISSUE TITLE
Aggregator duplicate detection fails

### ISSUE THREAD

**Issue by KRuelY** [cloudfoundry-incubator/cf-abacus#434]
Omitting start in accumulator would create different combination of duplicate documents for aggregator. 
https://github.com/cloudfoundry-incubator/cf-abacus/blob/5bba8b47f20eeee8337539e657a945fe08de37ef/lib/aggregation/accumulator/src/index.js#L202

Keeping the first usage's start as the accumulated usage start does not makes any sense because usages can come out of order. Consider u1 with start & end = t1 and u2 with start & end = t2 where t2 > t1. if u2 comes in followed by u1, the accumulated doc will have start = t2 and end = t1.

Problem arises when the conditions below are met:
1. Retries happen.
2. More than 1 usage for the same org are going to be retried.

When those usages are retried, the order of how the submissions are processed might not be in the same sequence, which would produce different combination of start and end than what was previously posted to the aggregator. Aggregator's duplicate detection would fails because it was different from what was previously posted, and it will aggregate the usage. This would results in incorrect aggregation.

Further discussion: start and end should always be the same. We should not have two different fields, 'start' and 'end', to represent event time / time where usages are collected. Thoughts?

**Comment by betafood** [comment]
About the start and end fields, I believe those existed for a similar purpose that time-based metrics now solve. I personally would agree to just having something like "event-time" to describe usage. Like you've stated, start and end seem to always be the same, but if there is a clear and distinct case where they need to be different, then I wouldn't mind them staying.
