### ISSUE TITLE
abacus-learning tests fail

### ISSUE THREAD

**Issue by dlapiduz** [cloudfoundry-incubator/cf-abacus#436]
I've been having issues running `npm run build` locally with node v6.3.1 and npm 3.10.3.

The issue is that it can't find some packages like this:

```

> abacus-batch@0.0.6-dev.8 test /Users/diegolapiduz/src/cf/cf-abacus/node_modules/abacus-batch
> mocha

Testing...
module.js:442
    throw err;
    ^

Error: Cannot find module 'abacus-yieldable'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/diegolapiduz/src/cf/cf-abacus/node_modules/abacus-batch/src/test/test.js:6:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/diegolapiduz/src/cf/cf-abacus/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
npm ERR! Test failed.  See above for more details.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

If I add the specific package to the module it works but it seems like something is not right. Has anyone run into anything like this before?

I am a node newb so please forgive me if I am missing something obvious.

**Comment by rajkiranrbala** [comment]
@dlapiduz 

Can you please share the exact build steps that you followed? Usually, this works

```
git clone git@github.com:cloudfoundry-incubator/cf-abacus.git cf-abacus
cd cf-abacus
npm run build
```

Just in case if you are modifying any files after building then you have to do a rebuild.

```
# This will remove any files that are not tracked by git. 
# Make sure to commit all new files added to the project
npm run rebuild
```

**Comment by dlapiduz** [comment]
@rajkiranrbala I tried running it with a new version of node/npm plus a fresh clone, now it is failing on a test:

```
 abacus-learning
    ✓ encodes values into labels
    ✓ vectorizes feature sets
    ✓ predicts classes using a linear perceptron model
    1) implements computation graphs with backprop
    ✓ predicts labels using a NN computation graph (4671ms)
    ✓ predicts classes from features using a basic NN model (6212ms)
    ✓ predicts classes from embeddings using a basic NN model (17039ms)
    ✓ predicts sequences using a recurrent NN model (54982ms)
    ✓ predicts sequences using a LSTM NN model (12260ms)


  8 passing (2m)
  1 failing

  1) abacus-learning implements computation graphs with backprop:

      AssertionError: expected { '0': 0.7615941559557649,
  '1': 0.964027580075817,
  '2': 0.9950547536867306,
  '3': 0.9993292997390669,
  '4': 0.999909204262595,
  '5': 0.9999877116507956 } to deeply equal { '0': 0.7615941559557649,
  '1': 0.9640275800758169,
  '2': 0.9950547536867305,
  '3': 0.999329299739067,
  '4': 0.9999092042625951,
  '5': 0.9999877116507956 }
      + expected - actual

      -{"0":0.7615941559557649,"1":0.964027580075817,"2":0.9950547536867306,"3":0.9993292997390669,"4":0.999909204262595,"5":0.9999877116507956}
      +{"0":0.7615941559557649,"1":0.9640275800758169,"2":0.9950547536867305,"3":0.999329299739067,"4":0.9999092042625951,"5":0.9999877116507956}
      
      at Assertion.assertEqual (/Users/diegolapiduz/src/cf/cf-abacus/node_modules/chai/lib/chai/core/assertions.js:485:19)
      at Assertion.ctx.(anonymous function) [as equal] (/Users/diegolapiduz/src/cf/cf-abacus/node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Context.<anonymous> (lib/test/test.js:134:38)

```

**Comment by hsiliev** [comment]
Hey @dlapiduz, I tried with
```bash
etc/versions
OS Darwin SOFM33780462A 16.0.0 x64
Node v6.7.0
Npm 3.10.7
```
and the build runs fine. 

Can you reproduce the failure above? What's the output of `etc/versions`?

**Comment by KRuelY** [comment]
I occasionally see similar error. There are times where the test would fail because it cannot find a module. This doesn't happens all the time, and it seems that it happens because not all the modules are built before the tests are run.

The abacus learning test would occasionally fail too, and I notice that they're off by 0.000000000000000x. Need to understand more about the abacus learning before I can safely say that we can round the value in the expect.

**Comment by dlapiduz** [comment]
@hsiliev changing the versions to the ones you have worked. Maybe we should document what versions of node/npm work and which ones dont.

**Comment by hsiliev** [comment]
@dlapiduz @KRuelY I think the tests are flaky. Cannot tell if this is caused by node version, rounding or something else. The fact is that after updating from node 5 to 6 they fail less frequently, but this might mean this is caused by some time-out as I can see that latest versions are faster.

**Comment by hsiliev** [comment]
With node 7.0.0 the tests fail each time. It seems as a rounding issue.

**Comment by hsiliev** [comment]
The learning tests can run in node 7 with the changes in https://github.com/cloudfoundry-incubator/cf-abacus/pull/448

Noticed that the `abacus-learning predicts labels using a NN computation graph` tests fail.

**Comment by jsdelfino** [comment]
Thanks for looking into this! It's a bit weird for Math.exp() to give different results on node v7 though...
