### ISSUE TITLE
Exposing abacus-rated-usage-log as events

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#44]
If the records in the abacus-rated-usage-log database is exposed similar to cloud foundry events, it would help in scenarios where the usage of resources needs to be monitored

**Comment by jsdelfino** [comment]
+1 to that.

We don't have that kind of API yet but we have a user story in our tracker for it [1].

The idea would be to have an API maybe similar to the future CF notification API that's been recently discussed on the cf-dev mailing list \[2\] (although we'll first need to see what that new CF notification API will look like to understand if a similar pattern will apply here).

This work is not high priority for now but as you can see in \[1\] it is on the roadmap in our tracker.

[1] https://www.pivotaltracker.com/story/show/101098050
[2] https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/ASQNCWYWR6SG4MVJHE2E6YUZLUFJPNVG/

**Comment by jsdelfino** [comment]
Superseded by issue #161. Will continue to discuss and track the related work in #161 instead.
