### ISSUE TITLE
abacus-learning fails sporadically

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#449]
The abacus-learning tests fail sporadically. This happens when the tests are run on a loaded CPU core, so I guess this is due to some synchronization issues.

We might consider using generator functions in learning.

Note: The tests were failing due to different result in Math.exp (see #436)

**Comment by jsdelfino** [comment]
Thanks for reporting this. Will take a look weekend.

**Comment by hsiliev** [comment]
Deleted the code. We should get back to this when we have a better idea how v2 pipeline will look like.
