### ISSUE TITLE
Can we set different prices for different customers?

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry-incubator/cf-abacus#45]
How do the pricing rules work, can we set different prices for different customers?

**Comment by jsdelfino** [comment]
The pricing is currently loaded from a simple JSON configuration file, but the intent is to convert that to a service that an integrator of Abacus can implement to control what price is used for a particular resource, plan, organization, time (as prices evolve over time), country, currency etc.

That service will need to implement a REST API that Abacus will call to get the price to use to rate the usage. So, yes, with that you'll be able to return a different pricing per customer (i.e. per organization).

We've been focusing more on usage metering than rating as rating got integrated only very recently but that pricing service should make its way to the code soon.

**Comment by jsdelfino** [comment]
The question was answered. Please re-open if more discussion is needed.
