### ISSUE TITLE
Bloom filter bugs

### ISSUE THREAD

**Issue by KRuelY** [cloudfoundry-incubator/cf-abacus#453]
There is current bug that will affect correctness, and it happens in abacus-dedupe and dataflow. When dataflow app with dedupe restarts, the bloom filters would not be persisted. When dataflow app starts, it will start a new bloomfilter: This means that all duplicate submissions would be marked as non duplicate, and it would be accumulated to the usage doc. then it would throw 409 due to duplicate when posting the duplicate document to the db.

In order for dataflow to utilize bloomfilter, dataflow needs do to multiple things:
1. Dataflow needs to find a way to persist the bloom filter that it is using periodically.
2. During dataflow starts, dataflow needs to fetch the bloom filter that it was using.
3. Dataflow needs to fetch all the docs that came in between the last time it persist and app starts, and add their ids to the bloom filter.

For couchclient, we can store the bloom filter to db(1), and use view to fetch (3). It seems that this is something that we have to add to the dbclient. We don't really have any clear solution now, and this is still open for discussion. In the meantime, I'm going to disable the use of bloom filter in dataflow.

https://github.com/cloudfoundry-incubator/cf-abacus/pull/452

**Comment by hsiliev** [comment]
Can you elaborate a bit on (3)? Why do we need a view? Is it because we need to filter/reduce the number of docs to scan? If this is the case perhaps we can add this filtering logic in dbclient. If I get this right we should be able to use [Map-Reduce](https://docs.mongodb.com/manual/aggregation/#map-reduce) aggregation pipelines in Mongo to achieve the same as the views in Couch .

**Comment by hsiliev** [comment]
We removed bloom filters from dedupe and now use only cache. This might be slower, but there is no good way to ensure we have up-to-date filter in all instances of meter/accumulator.
