### ISSUE TITLE
Can we configure e.g. a trial period?

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry-incubator/cf-abacus#46]
Can we configure e.g. a trial period, where the first 10 resources, 100 hours*GB or 5 weeks of usage are free for new customers?

**Comment by jsdelfino** [comment]
Abacus allows you to completely control how usage and costs are accumulated over time, and aggregated at various levels inside an organization using Javascript functions that you can define yourself for each resource, so yes you should be able to implement that kind of logic.

We are actually in the middle of implementing time windows (sec, min, hour, day, month, year) for usage accumulation so when that's in place it'll be even easier to do it.

Another thing to consider is that Abacus doesn't do billing/invoicing. We meter, aggregate and rate usage to produce usage and charge summary reports that can then be fed to a billing system. Your particular billing system can eventually decide to apply discounts or 'just make it free for that customer' for example on top of the usage and rating data that Abacus provided.

**Comment by jsdelfino** [comment]
The question was answered and added to an FAQ as well. Please re-open if more discussion is needed.
