### ISSUE TITLE
Is there an API to cancel or correct entries?

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry-incubator/cf-abacus#47]
Is there an API to cancel or correct entries, e.g. delete a start/stop pair of an app, because it was decided a particular customer should not be charged for that are that particular time? (E.g. because an app was accidentally started by the operator)

**Comment by jsdelfino** [comment]
Our current strategy is to have the service or runtime provider submit compensating usage (e.g. if that service provider thinks it has submitted too much GB hours for example, he can always compensate that with a negative/credit usage later). If there's a mistake, it's compensated later, we don't rewrite history, for many reasons including auditing, potentially legal reasons etc...

The other thing to consider is that even if there was a way to rewrite history, that wouldn't handle the cases where the mistaken usage would have already been shown to the customer (as customers are typically able to see their usage in close to real time) or, even more difficult... the cases where that usage would have already been billed to that customer (e.g. the mistake happened on 08/31 23:30pm and only got discovered on 09/01 after a bill was produced and sent to the customer...)

**Comment by jsdelfino** [comment]
The question was answered and added to an FAQ as well. Please re-open if more discussion is needed.
