### ISSUE TITLE
Drop hard codes ignoring SSL validation

### ISSUE THREAD

**Issue by sharms** [cloudfoundry-incubator/cf-abacus#477]
Validating ssl is already a parameter which can be specified for other operations, but for some reason drop hardcodes this to false.

https://github.com/cloudfoundry-incubator/cf-abacus/blob/6c97fc8782693998c8b3a82376213152d7d2f906/lib/utils/mongoclient/src/index.js#L906

**Comment by hsiliev** [comment]
See also #411 for https on `SECURED=true`
