### ISSUE TITLE
Is s Service Provider implementation to retrieve app usage from CF in scope or out of scope for Abacus?

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry-incubator/cf-abacus#48]
The diagram in the github project readme has a Service Provider on the left, which gives the impression CF operators have to develop this component themselves to push data to Abacus, and this is not part of Abacus. Yet you are developing a prototype?
What is the status of the prototype when completed? Will it be an unsupported example/reference implementation, or will it be treated as a core component of Abacus and maintained accordingly?

**Comment by jsdelfino** [comment]
> The diagram in the github project readme has a Service Provider on the left, which gives the impression CF operators have to develop this component themselves to push data to Abacus, and this is not part of Abacus.

Correct, a service provider decides what service it provides (e.g. I'm providing a hosted CouchDB or MongoDB service database for example), the kind of usage data that makes sense for that service (e.g. GB of storage, number of docs in the DB etc) and can then push that usage to Abacus using the Abacus usage submission API, from whatever code or automated process the service provider decides to use for that.

The code that pushes service specific usage data to Abacus can be developed by whoever has an interest in integrating that service with Abacus (the service provider, the guy who's deploying Abacus, an interested 3rd party, the Abacus team itself etc).

> Yet you are developing a prototype?

The Abacus team is developing a component that pushes CF app runtime usage events to Abacus. That's for app runtime metering (different from any 3rd party service, although it uses the same usage submission API). We thought it'd be a good idea to have that included in Abacus as app usage is a core CF capability (as opposed to the many 3rd party services and their variations out there).

>What is the status of the prototype when completed? Will it be an unsupported example/reference implementation, or will it be treated as a core component of Abacus and maintained accordingly?

The prototype is starting to take a really good shape (we should probably update the README doc to add it to the Abacus overview diagram as well). We also have a set of user stories in Pivotal tracker \[1\] to track that runtime metering work as a core component of Abacus. Feel free to review or comment on them.

[1] https://www.pivotaltracker.com/epic/show/2013844

**Comment by jsdelfino** [comment]
The question was answered. Please re-open if more discussion is needed.
