### ISSUE TITLE
Clarify service providers can submit usage of non-CF resources (e.g. IaaS resources like VMs)

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry-incubator/cf-abacus#49]
The readme on github described Abacus as providing "usage metering and aggregation for Cloud Foundry (CF) services". I believe it also allows submitting usage for non-CF resources (like IaaS VMs), which is an important requirement for IBM Bluemix. Could you update the readme to explain that this use case is indeed envisioned and supported, and add documentation (with example) how? (with a suggestion how to map to CF specific orgs)

**Comment by jsdelfino** [comment]
Any service provider that wants to push usage to Abacus for the services (and more generally resources, including app runtimes, containers, etc) it provides can do that by using the Abacus usage submission API. The resource you submit usage for doesn't necessarily have to be provisioned by a CF service broker, it can be anything you want, provisioned the way you want.

For Abacus to be able to process usage data for a particular type of resource you just need to provide a definition of the types of measurements and metrics relevant to that resource (eg. my resources are CouchDB or MongoDB databases, or Linux containers, and their metrics are GB of storage and memory), and optionally provide a set of Javascript functions or formulas that will be used to meter, accumulate and aggregate those metrics.

Once you've done that you can start submitting usage data for instances of your resources. Usage data needs to include a resource_id (e.g. CouchDB, MongoDB, Linux-container... you can pick these ids yourself), a resource_instance_id (e.g your DB name or some id for an instance of your Linux container) and the measurements representing the usage incurred by that resource instance (e.g. 10GB of DB storage, 2GB of memory). Abacus will then process your usage data, meter and aggregate it for you.

Usage data is also expected to reference things like organization_id, space_id etc allowing you to aggregate your resources under organizations, spaces (or similar concepts that you'd like to map to organizations and spaces, e.g. department or team and dev/test/prod environments). That categorization and mapping are left as an exercise to the integrator of Abacus, but in my experience these two levels of aggregation have proven generic enough to fit how most people organize their Cloud resources.

**Comment by jsdelfino** [comment]
We should probably update the docs at some point with an overview of how to define resources and configure Abacus to recognize them.

**Comment by jsdelfino** [comment]
The question was answered. Please re-open if more discussion is needed.
