### ISSUE TITLE
Resource instance usage summary report not working

### ISSUE THREAD

**Issue by yulianedyalkova** [cloudfoundry-incubator/cf-abacus#502]
When trying to make a call to the [following endpoint](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/doc/api.md#resource-instance-usage-summary-report) I always get the following error:

{
  "error": "notfound",
  "message": "Not found"
}

Going a bit through the code, I found out that this endpoint does not exist any more (It got changed [here](https://github.com/cloudfoundry-incubator/cf-abacus/commit/6885b2794ae14e4de0e4bbd8b154c164e68ac820) and [here](https://github.com/cloudfoundry-incubator/cf-abacus/commit/1aa84a34ebc8eb47675af0d1ff8ae95e662897fd#diff-b9978e2211c333f449b22ac959d89ad5)), but the documentation stayed the same. I managed to get the resource instance usage summary report using [this endpoint](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/aggregation/reporting/src/index.js#L800) but it is neither tested in the integration tests nor documented.

**Comment by hsiliev** [comment]
Documented the new format of the endpoint with https://github.com/cloudfoundry-incubator/cf-abacus/commit/157d92cc6469e378dda7b614bb6c9d230b296322
