### ISSUE TITLE
Usage of moment().utc() in Abacus

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#530]
Instead of `moment.utc(<ms>)` we use `moment(<ms>).utc()` in several places.

For example:
https://github.com/cloudfoundry-incubator/cf-abacus/blob/f0e0d1caaf7b60f13b54127d53e33d9ffd92fed3/lib/utils/carryover/src/index.js#L43
https://github.com/cloudfoundry-incubator/cf-abacus/blob/ed6d23f31c7d39ef8788e8e150de850c50228ca8/lib/aggregation/reporting/src/index.js#L500
https://github.com/cloudfoundry-incubator/cf-abacus/blob/ed6d23f31c7d39ef8788e8e150de850c50228ca8/lib/aggregation/aggregator/src/index.js#L115

**Comment by KRuelY** [comment]
The start and end you posted: 1485900000000 is actually 2017-01-31T22:00:00.000Z in UTC.

**Comment by hsiliev** [comment]
We use the wrong date in several places. For example:
https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/cf/renewer/src/index.js#L194

Instead of `moment.utc()` we use `moment().utc()`

I think we can add this in the eslint plugin we already have for Date.
