### ISSUE TITLE
Run abacus on node 7

### ISSUE THREAD

**Issue by stoyanr** [cloudfoundry-incubator/cf-abacus#539]
To take advantage of new features in node, we should run abacus on node 7 rather than node 6. This would enable us for example to get rid of babel (see #538). As a prerequisite, we should ensure that the build process works correctly with this version of node, which is currently not the case (see #534).

**Comment by hsiliev** [comment]
6.10 is LTS so most companies would prefer it over 7. Abacus now runs without babel on node 6.10 and can be started on node 7

Since we can use any version >6.10 I'm closing this issue
