### ISSUE TITLE
While installing submodule's dependencies getting error

### ISSUE THREAD

**Issue by naveensf** [cloudfoundry-incubator/cf-abacus#55]
Actually i want to metering application in bluemix for that i choose cf-abacus.

While installing submodule's dependencies getting error

Error:

npm ERR! notarget No compatible version found: abacus-dbclient@'file:../../utils/dbclient'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1-dev.1","0.0.1-dev.2","0.0.1-dev.3"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 3.13.0-61-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/opteamize/Documents/cf-abacus-master/lib/metering/collector
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ETARGET
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/opteamize/Documents/cf-abacus-master/lib/metering/collector/npm-debug.log
npm ERR! not ok code 0

**Comment by rajkiranrbala** [comment]
Did you try 
```sh
$ npm run build
```

**Comment by jsdelfino** [comment]
Did that answer your question?

**Comment by jsdelfino** [comment]
No response so closing for now. Please reopen if needed.
