### ISSUE TITLE
How can I get the latest version of cf-abacus dependencies such as abacus-request and abacus-retry

### ISSUE THREAD

**Issue by canhvu** [cloudfoundry-incubator/cf-abacus#57]
I am using abacus* modules from my component.

In the package.json file, I have the following ones:

"dependencies": { "abacus-request": "0.0.1-dev.2", "abacus-retry": "0.0.1-dev.2",

}

That says that getting "abacus-request" and "abacus-retry" is depending on a special version. If I would like to get the latest version of these, how can I configure my package.json to do that?

Thanks, Canh

**Comment by jsdelfino** [comment]
Try this:
```
"abacus-request": "0.0.1-dev"
```

**Comment by jsdelfino** [comment]
Please reopen if the suggestion doesn't work for you.

**Comment by canhvu** [comment]
Hi Sebastien, 
I have tried "abacus-request": "0.0.1-dev" and it did not work.
However, I modify a little bit to "abacus-request": "^0.0.1-dev"  (adding ^ at the front), then it works.

Thank you, Sebastien
Canh

**Comment by jsdelfino** [comment]
You are correct, I had missed the leading "^" in my suggestion. Thanks for catching that.

We actually use "^" everywhere in the Abacus project. Most Node projects do that too, and that's the default format generated by npm install --save <module> as well.
