### ISSUE TITLE
Load Resource/Price Definitions Automatically

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#58]
It would be good to have all the resource definitions in the resources directory loaded without updating the code in the configuration file.

**Comment by jsdelfino** [comment]
The goal is to provide a REST API to allow resource providers to post their resource configs to Abacus, so the current code is temporary and will be replaced when we implement that API. See this tracker for updates on that work: https://www.pivotaltracker.com/story/show/101019374

**Comment by rajkiranrbala** [comment]
For the immediate requirement we have I am planning to automatically load the definitions from the resource directory and then I am going to implement the API.

**Comment by jsdelfino** [comment]
@rajkiranrbala I started to work on this. The provisioning stub service will implement a GET API allowing the other services to get the resource config for a particular resource_id and time (as resource configs can evolve over time, you can then get the correct version to use to process an event at a given time).

As an integrator of Abacus, you will need to implement and deploy a version of that provisioning service specific to your particular integration environment and configure the other Abacus services to point to it.

I'll comment here again once the changes I've started to work are in place. I'm hoping that you'll be able to use that Abacus provisioning service stub as an example / starting point to implement your own version of that service.

**Comment by jsdelfino** [comment]
@rajkiranrbala Commits 0ac7d24 and 99a660a add a sample implementation of the resource config API to the provisioning stub service. All the other Abacus services have been adjusted to now retrieve their resource configs using that API. I will adjust the API doc later today but in the meantime you can use that provisioning service as an starting point for your own implementation of that API.

**Comment by jsdelfino** [comment]
There's now two APIs allowing an integrator of Abacus to provide Abacus with externally managed resource configs and pricing:
- resource config API, used by Abacus to retrieve the resource metering config for each resource, see the provisioning service stub for a sample implementation of that API;
- price config API, used by Abacus to retrieve the resource pricing data, see the account service stub for a sample implementation of that API. 

Descriptions of these two APIs have been added to Abacus API doc.
