### ISSUE TITLE
Issue with the demo client

### ISSUE THREAD

**Issue by rjain-pivotal** [cloudfoundry-incubator/cf-abacus#6]
I believe this could be a dependency or documentation issue. 

trying to run 'npm run demo' results in 

cf-abacus rjain$ npm run demo

> cf-abacus@0.0.1 demo /Users/rjain/code/monitoring/cf-abacus
> bin/demo

> cf-abacus-demo-client@0.0.1 demo /Users/rjain/code/monitoring/cf-abacus/node_modules/cf-abacus-demo-client
> mocha

sh: mocha: command not found

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "demo"
npm ERR! node v0.12.0
npm ERR! npm  v2.13.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! cf-abacus-demo-client@0.0.1 demo: `mocha`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the cf-abacus-demo-client@0.0.1 demo script 'mocha'.
npm ERR! This is most likely a problem with the cf-abacus-demo-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha
npm ERR! You can get their info via:
npm ERR!     npm owner ls cf-abacus-demo-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rjain/code/monitoring/cf-abacus/node_modules/cf-abacus-demo-client/npm-debug.log

**Comment by rjain-pivotal** [comment]
After installing mocha, I am getting some other errors

> cf-abacus@0.0.1 demo /Users/rjain/code/monitoring/cf-abacus
> bin/demo


> cf-abacus-demo-client@0.0.1 demo /Users/rjain/code/monitoring/cf-abacus/node_modules/cf-abacus-demo-client
> mocha

/Users/rjain/code/monitoring/cf-abacus/node_modules/cf-abacus-demo-client/test/graphql.js:5
const request = require('cf-abacus-request');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/rjain/code/monitoring/cf-abacus/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/rjain/code/monitoring/cf-abacus/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/Users/rjain/code/monitoring/cf-abacus/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/Users/rjain/code/monitoring/cf-abacus/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "demo"

**Comment by jsdelfino** [comment]
Can you point me to the version you're using?

Did you do an npm install in the root cf-abacus dir first and did that work?

Is npm test in the root cf-abacus dir working for you?

**Comment by rjain-pivotal** [comment]
node version : 0.12.7
npm version : 2.11.3
cf-abacus - I have the latest master version pulled from git repo, I synced
it today morning.

>>Did you do an npm install in the root cf-abacus dir first and did that
work?
I did npm install in the root

npm test doesn't work

I am getting the following errors on npm run test
=====

/Users/rjain/code/monitoring/cf-abacus/node_modules/cf-abacus-aggregation-db/test/test.js:5

const dbclient = require('cf-abacus-dbclient');

^^^^^

SyntaxError: Use of const in strict mode.

    at exports.runInThisContext (vm.js:73:16)

    at Module._compile (module.js:443:25)

    at Object.Module._extensions..js (module.js:478:10)

    at Module.load (module.js:355:32)

    at Function.Module._load (module.js:310:12)

    at Module.require (module.js:365:17)

    at require (module.js:384:17)

    at
/Users/rjain/code/monitoring/cf-abacus/node_modules/mocha/lib/mocha.js:192:27

    at Array.forEach (native)

    at Mocha.loadFiles
(/Users/rjain/code/monitoring/cf-abacus/node_modules/mocha/lib/mocha.js:189:14)

    at Mocha.run
(/Users/rjain/code/monitoring/cf-abacus/node_modules/mocha/lib/mocha.js:422:31)

    at Object.<anonymous>
(/Users/rjain/code/monitoring/cf-abacus/node_modules/mocha/bin/_mocha:398:16)

    at Module._compile (module.js:460:26)

    at Object.Module._extensions..js (module.js:478:10)

    at Module.load (module.js:355:32)

    at Function.Module._load (module.js:310:12)

    at Function.Module.runMain (module.js:501:10)

    at startup (node.js:129:16)

    at node.js:814:3

npm ERR! Test failed.  See above for more details.


==================



npm lint doesn't work ( I had to manually do npm install eslint before
trying npm lint)

I am getting the following errors on npm lint (seems the options to run
lint are not correct)

========

< node_modules/cf-abacus-yieldable: npm run lint


> cf-abacus-yieldable@0.0.1 lint
/Users/rjain/code/monitoring/cf-abacus/node_modules/cf-abacus-yieldable

> eslint


eslint [options] file.js [file.js] [dir]


Options:

  -h, --help                  Show help

  -c, --config path::String   Use configuration from this file

  --rulesdir [path::String]   Use additional rules from this directory

  -f, --format String         Use a specific output format - default:
stylish

  -v, --version               Outputs the version number

  --no-eslintrc               Disable use of configuration from .eslintrc

  --env [String]              Specify environments

  --ext [String]              Specify JavaScript file extensions - default:
.js

  --plugin [String]           Specify plugins

  --global [String]           Define global variables

  --rule Object               Specify rules

  --ignore-path path::String  Specify path of ignore file

  --no-ignore                 Disable use of .eslintignore

  --ignore-pattern String     Pattern of files to ignore (in addition to
those in .eslintignore)

  --no-color                  Disable color in piped output

  -o, --output-file path::String  Specify file to write report to

  --quiet                     Report errors only - default: false

  --stdin                     Lint code provided on <STDIN> - default: false

  --stdin-filename String     Specify filename to process STDIN as

  --init                      Run config initialization wizard - default:
false

======





On Fri, Jul 31, 2015 at 11:14 PM, Jean-Sebastien Delfino <
notifications@github.com> wrote:

> Can you point me to the version you're using?
>
> Did you do an npm install in the root cf-abacus dir first and did that
> work?
>
> Is npm test in the root cf-abacus dir working for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry-incubator/cf-abacus/issues/6#issuecomment-126854651>
> .
>



-- 
Rajesh Jain
Sales Engineering, Pivotal
e:rajesh.jain@pivotal.io <rajesh.jain@pivotal.io> | m: 2487900082 | t:
@rjain15

**Comment by jsdelfino** [comment]
This file from the log you posted:

> /Users/rjain/code/monitoring/cf-abacus/node_modules/cf-abacus-aggregation-db/test/test.js

doesn't exist in master (see there https://github.com/cloudfoundry-incubator/cf-abacus/tree/master/lib/aggregation/db).

You may have a mix of older and latest modules under \<cf-abacus\>/node_modules as npm install doesn't update local module dependencies in an already populated node_modules.

If that's the case that will really confuse the build since we recently moved the source files under src/ directories for example.

Can you try the following to start clean:
```
remove <cf-abacus>/node_modules
remove any other <cf-abacus>/**/node_modules in the tree (if you ran npm install in any individual module) 

npm install

# this step is new, got added yesterday as Babel is now run at build time
# needs to be added to the README or integrated in the post install
npm run babel

npm test
```

These are the steps run by [Travis](https://travis-ci.org/cloudfoundry-incubator/cf-abacus) (which starts with a clean node_modules directory).

**Comment by jsdelfino** [comment]
Did the steps above help?

The latest version of the master branch now has a new ```npm run clean``` task which can be used to clean the build artifacts (it does a git clean -df) and README.md has been updated to include ```npm run build``` (the same task that is used to build on Travis).

**Comment by maximilien** [comment]
Can we close this issue or is it still something you are seeing @rjain-pivotal?

**Comment by jsdelfino** [comment]
Will close this issue sometime tomorrow unless there's an update, as others are able to run the demo. We can always reopen it later if needed.

**Comment by jsdelfino** [comment]
No update so assuming there is no issue at this point. Please reopen if this is still a valid issue.
