### ISSUE TITLE
CPU Usage Reporting

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry-incubator/cf-abacus#60]
# CPU Usage Reporting

## Background

Currently we report two CF apps measurements - memory usage and instance number. CPU usage is usually tightly connected with memory usage. However the current CF bridge in Abacus does not provide CPU usage measurements.

This document reviews the existing solutions and proposes several approaches to add CPU usage measurements.

## Existing solutions overview

Existing PaaS offerings do not generally charge by CPU. IaaS Platforms like Amazon charge based on the instance size, which can include number of CPUs, but in the IaaS case these CPUs are committed to the customer.

[Google App Engine](https://cloud.google.com/appengine/pricing) charge based on number of instances, network traffic, API calls, and storage in GB per month.

[Heroku](https://www.heroku.com/pricing) base their pricing on container sizes but do not mention CPU.

[Pivotal Web Services](https://run.pivotal.io/pricing/) charge per instance per time based on memory quota.

[Engine Yard](https://www.engineyard.com/pricing) define several plans differing on number of instances allowed, support level and connectivity to your backend - no memory or CPU quotas are mentioned.

### Extend app metadata to include CPU limit that garden set on the container
Pros:
 - The CF Bridge will be able to get all apps with one request and report the CPU limit for each app

Cons:
- All apps now have the same CPU limit. If we want CPU to be meaningful CF will have to provide support for scaling the CPU limit

### Each app runner to regularly report current stats in an event queue/database
The runner (DEA or Diego) can report the stats to a dedicated queue or database.

Pros:
- Ease of use from the POV of CF Bridge
- Cheapness in terms of requests - the Bridge will be able to poll all apps usage with one request

Cons:
- An event queue with regular stats for each app will not scale well in terms of storage and connections
- The CF architecture may be misfit for this approach

### CF Bridge to regularly poll the stats for each application
Pros:
- Easy to implement

Cons:
- Does not scale in terms of number of requests

### Log CPU and memory usage
Log CPU and memory usage in special format. The usage stats can then be processed/parsed in loggregator and send the data to either CF-bridge or to Abacus directly.

Pros:
- Re-use existing log stream infrastructure

Cons:
- Connections intensive approach

### The stats endpoint

Currently CPU, memory and disk usage of an app at a given point in time can be obtained fro the `/v2/apps/<app_guid>/stats` endpoint. Here's an example response:

```
{
   "0": {
      "state": "RUNNING",
      "stats": {
         "name": "a7",
         "uris": [
            "a7.10.244.0.34.xip.io"
         ],
         "host": "10.244.0.26",
         "port": 61032,
         "uptime": 408282,
         "mem_quota": 268435456,
         "disk_quota": 1073741824,
         "fds_quota": 16384,
         "usage": {
            "time": "2015-09-28 08:57:50 +0000",
            "cpu": 0.00023182570557697148,
            "mem": 2600960,
            "disk": 0
         }
      }
   }
}
```

This endpoint is implemented in CC's [StatsController](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/controllers/runtime/stats_controller.rb#L10). The implementation basically retrieves the app's stats from the node(s) it is running on. This retrieval is delegated to one of two implementations - the [DEA](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/dea/instances_reporter.rb#L33) and [Diego cell](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/diego/instances_reporter.rb#L97) implementations.

### CC Database

The `events` or `app_usage_events` tables in CCDB could accommodate periodic events. However two things are missing in current implementation:
- an API in CC that writes stats events
- a component in the DEA/cell should be responsible for pushing these stats periodically to this API

### External stats database

The CPU stats will use a significant amount of storage. They will most probably consume a lot of connections as well. Therefore we might want to use a dedicated database such as Hadoop to handle big-scale CF deployments.

# Conclusion

All of the above approaches require a lot of connections or storage resources in order to provide CPU usage reports.

The CPU stats are vital part of the monitoring infrastructure since it helps the developers and operators to triage problems. It only makes sense to support CPU metrics if they are one of the most important components for billing. However since the applications are run in containers that effectively cap the CPU, this is rarely so, as also seen from the existing solutions.

**Comment by georgethebeatle** [comment]
This is the result of our latest [spike](https://www.pivotaltracker.com/n/projects/1385414/stories/104196628). Please comment.

**Comment by jsdelfino** [comment]
> The CPU stats are vital part of the monitoring infrastructure since it helps the developers and operators to triage problems. It only makes sense to support CPU metrics if they are one of the most important components for billing. However since the applications are run in containers that effectively cap the CPU, this is rarely so, as also seen from the existing solutions.

I think you summarized this pretty well. CPU is sometimes committed, usually capped, and factored in the plan (and corresponding pricing) that you pick for your app ahead of time, and that's one of the reasons it's not often used as a variable metric for billing.

**Comment by georgethebeatle** [comment]
Closing as we're obviously on the same page about CPU usage
