### ISSUE TITLE
Circular Dependency abacus-usage-schema and abacus-resource-config

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#61]
In the abacus-usage-schema module,  [Line 7](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/config/schemas/src/resource-usage.js#L7) of  lib/config/schemas/src/resource-usage.js imports the abacus-resource-config

In the abacus-resource-config module, the test file lib/config/resource/src/test/test.js imports the abacus-usage-schema module in [Line 9](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/config/resource/src/test/test.js#L9)

Why should the usage-schema module have a reference to the resource-config module?

**Comment by sasrin** [comment]
> In the abacus-usage-schema module,  [Line 7](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/config/schemas/src/resource-usage.js#L7) of  lib/config/schemas/src/resource-usage.js imports the abacus-resource-config

Usage schema is trying to validate _resource_id_ property when validating the usage JSON structure against its schema. If we follow this pattern for other properties at the usage JSON, then we would end up validating properties like _resource_instance_id_, _organization_id_, _plan_id_, etc. That sounds odd to do these kind of validations when validating a JSON structure against its schema. @georgethebeatle 
and @cloudfoundry-incubator/cf-abacus-team, thoughts?

> In the abacus-resource-config module, the test file lib/config/resource/src/test/test.js imports the abacus-usage-schema module in [Line 9](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/config/resource/src/test/test.js#L9)

As part of resource config unit tests, we need to validate the defined resources against its schema.

**Comment by georgethebeatle** [comment]
I added this validation because reporting usage to the usage collector did not error when I reported usage with invalid `resource_id`. It returned status code 201 and then the report was empty and it was hard to spot the error. By adding this validation I also changed the type of `resource_id` from `string` to `enum`. In my oppinion we should validate all `enum` values and we need not validate `string` values.

As for the circular dependency it can be removed by hardcoding all possible enum values on [Line 45](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/config/schemas/src/resource-usage.js#L45). However by doing so we'll have one more thing to update when configuring new resources.

**Comment by jsdelfino** [comment]
@rajkiranrbala, I agree with @georgethebeatle that including the resource_id validation in the schema was the right design when we were using a fixed, pre-determined set of resource configs.

Now, with the new capabilities we're adding under user story #101097454 \[1\] (also see commits 0ac7d24 and 99a660a and Github issue #58) the management of resource configs is becoming open ended as resource providers can add resource configs dynamically at any point in time without requiring any redeployment or restart of the Abacus services. This will allow us to offer self service resource on boarding to resource providers, as described in user story #101019374 [2].

To support that, the loading and validation of resource configs has been refactored and moved to the provisioning service (which will typically be implemented or customized by the integrators of Abacus). That resolved the circular dependency issue. The schemas do not depend on the resource config module anymore, as these schemas alone wouldn't be able to validate a dynamically evolving enumeration of resource_ids anyway.

The resource_id validation is now performed in the provisioning service along with the validation of org_id, space_id, region, etc, and will need to take into account more criteria than the availability of a resource config with the requested resource_id (e.g. the effective time set on the resource config, allowing a resource provider to define a resource config which will only be effective at some later point in time).

\[1\] https://www.pivotaltracker.com/story/show/101097454
\[2\] https://www.pivotaltracker.com/story/show/101019374
