### ISSUE TITLE
npm run demo -- --collector is not working

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry-incubator/cf-abacus#629]
I have deployed cf-abacus by referring https://github.com/cloudfoundry-incubator/cf-abacus .
After deploying, it is showing 10 apps running with the respective url.
Now I am trying to run the demo test with following command:

$ npm run demo -- --collector https://abacus-usage-collector.apps.mydomain.com --reporting https://abacus-usage-reporting.apps.mydomain.com

It's showing following error:
Child process exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! abacus-demo-client@0.0.6-dev.9 demo: `mocha --command "--collector" "https://abacus-usage-collector.apps.mydomain.com" "--reporting" "https://abacus-usage-reporting.apps.mydomain.com"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the abacus-demo-client@0.0.6-dev.9 demo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amit/.npm/_logs/2017-05-11T10_52_20_147Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cf-abacus@0.0.6-dev.9 demo: `bin/demo "--collector" "https://abacus-usage-collector.apps.mydomain.com" "--reporting" "https://abacus-usage-reporting.apps.mydomain.com"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cf-abacus@0.0.6-dev.9 demo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amit/.npm/_logs/2017-05-11T10_52_20_177Z-debug.log

**Comment by hsiliev** [comment]
Noticed the urls above use `https`. Do you run secured Abacus?

`demo` is part of our Travis validation, so I feel confident it works with unsecured Abacus.

**Comment by cfmagnum** [comment]
I tried with http url. Still getting same error.

**Comment by hsiliev** [comment]
Are you using bosh-lite or a CF on IaaS? 

Can you please `export DEBUG=e-abacus*,abacus-request*` and send the  logs (gist for example) from the demo?

**Comment by cfmagnum** [comment]
Have not started npm before. Started npm by "npm start". Now it's working.

**Comment by hsiliev** [comment]
Glad to hear it's working
