### ISSUE TITLE
Is there any update release?

### ISSUE THREAD

**Issue by mjsjinsu** [cloudfoundry-incubator/cf-abacus#630]
The current cf-abacus release v0.0.5
I wonder when it is next release come out?

**Comment by hsiliev** [comment]
We are preparing 0.0.6 release.

**Comment by mjsjinsu** [comment]
Can you share me of cf-abacus 0.0.6 release feature?

**Comment by maximilien** [comment]
@mjsjinsu it's pretty large. See DRAFT release of [Euro](https://github.com/cloudfoundry-incubator/cf-abacus/releases/tag/untagged-783a4c7f767c732834c3)

**Comment by mjsjinsu** [comment]
@maximilien Thank you I find docs
