### ISSUE TITLE
Reading documents with dbclient.allDocs

### ISSUE THREAD

**Issue by martin-d-aleksandrov** [cloudfoundry-incubator/cf-abacus#632]
Hi Colleagues,

When reading all documents stored in the database of the reporting app using dbclient.allDocs(), we are using partitioning function that has no "checkkey" param provided (actually it is the very same on all places I could found it). What is surprising for me is that the test that validates that functionality (lib/utils/mongoclient/src/test - 'range test') pass 'true' for that parameter... and in case it is changed the test stop pass.

Do you think it is OK, that the reporting does not pass that parameter? It looks like a bug for me?

Regards,
Martin

PS. One more point - the performance test is working perfectly fine... which is kind of confusing - I'd expect it would fail the same way as the unit test (it would not find all documents in all partitions of the database).

**Comment by hsiliev** [comment]
I can see that reporting uses allDocs with range here:
https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/aggregation/reporting/src/index.js#L508-L514

The DB is defined using dataflow's `db` function:
https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/aggregation/reporting/src/index.js#L80-L81

Which in turn does not define `checkkey`:
https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/utils/dataflow/src/index.js#L477-L483
