### ISSUE TITLE
404 error while calling /v1/metering/collected/usage using post method

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry-incubator/cf-abacus#635]
I am calling /v1/metering/collected/usage as below:

Url: http://abacus-usage-collector.apps.mydomain.com/v1/metering/collected/usage
Method: Post
Content-Type: application/json
Body: 
{
  "start": 1396421450000,
  "end": 1396421451000,
  "organization_id": "us-south:54257f98-83f0-4eca-ae04-9ea35277a538",
  "space_id": "d98b5916-3c77-44b9-ac12-04456df23eae",
  "consumer_id": "app:d98b5916-3c77-44b9-ac12-045678edabae",
  "resource_id": "object-storage",
  "plan_id": "basic",
  "resource_instance_id": "d98b5916-3c77-44b9-ac12-04d61c7a4eae",
  "measured_usage": [
    {
      "measure": "storage",
      "quantity": 10
    },
    {
      "measure": "api_calls",
      "quantity": 10
    }
  ]
}

I am sending same json as given in readme file. I am getting following response.
{
  "message": "no_db_file",
  "error": "not_found",
  "reason": "no_db_file",
  "name": "not_found",
  "status": 404,
  "noretry": true,
  "nobreaker": true
}

Why I am getting Not found error?

**Comment by hsiliev** [comment]
Usually the response above means that the Abacus apps do not know the DB URL

To configure DB you need to set environment variables `DB` and `DBCLIENT` as described here: https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/doc/conf.md#database

**Comment by hsiliev** [comment]
Any progress?

**Comment by cfmagnum** [comment]
@hsiliev It's worked. Thanks
