### ISSUE TITLE
Support node 8 and npm 5

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#651]
Abacus build fails with node 8 and npm 5. One of the reasons is that install saves by default and the other seems to be #647

We need to have Abacus running with node 8/npm 5 as this is the next LTS release.

**Comment by martinagalabova** [comment]
This seems to be related: https://github.com/cloudfoundry-incubator/cf-abacus/pull/729

**Comment by hsiliev** [comment]
Closing this as we have #729 for node and #771 for npm
