### ISSUE TITLE
Is there any user interface for the cf-abacus?

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry-incubator/cf-abacus#663]

**Comment by hsiliev** [comment]
You can check the cf-abacus-broker project that adds a broker and UI for creating new plans (and add metrics inside):
https://github.com/cloudfoundry-incubator/cf-abacus-broker

It's meant to be a drop-in replacement for some of the plugins Abacus defines.

You can create an issue there with requirements for UI focused at operator, end-user or plan/resource provider developer.

**Comment by hsiliev** [comment]
Closing the issue. If you have UI based questions or requests, please open an issue aginst the cf-abacus-broker repo.
