### ISSUE TITLE
"Cannot read property 'summarizefn' of undefined" 

### ISSUE THREAD

**Issue by rdejana** [cloudfoundry-incubator/cf-abacus#67]
abacus-usage-reporting returns the error "Cannot read property 'summarizefn' of undefined"  when running in a Cloud Foundry deployment while it works locally.  Not super strong with node so not exactly sure where to start on fixing this.

Node.js version: 0.12.7
Stack trace:
  OUT 2015-10-06T18:48:02.435Z abacus-express 44 Bailing out { message: 'Cannot read property \'summarizefn\' of undefined',
OUT   bailout: true } - TypeError: Cannot read property 'summarizefn' of undefined
OUT     at summarizefn (/home/vcap/app/lib/index.js:81:8)
 OUT     at summarizeMetric (/home/vcap/app/lib/index.js:248:29)
OUT     at _.map._.collect (/home/vcap/app/node_modules/underscore/underscore.js:172:24)

**Comment by sasrin** [comment]
Could you try adding Cloud Foundry application environment variable named DEBUG  with value abacus-usage-*,e-* , and that should give us more logs to look at.

**Comment by rdejana** [comment]
Updated DEBUG value and restaged.

OUT 2015-10-06T19:35:52.683Z abacus-usage-reporting 44 Retrieving rated usage for organization a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27 on 1435623000000
OUT 2015-10-06T19:35:52.686Z abacus-usage-reporting 44 Retrieving rated usage for k/a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27/t/0001435622400000
OUT 2015-10-06T19:35:53.093Z abacus-usage-reporting 44 Found rated usage { _id: 'k/a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27/t/0001435622400000',
OUT   _rev: '2-dedc0744eb80f26a7816addc99f89a5a',
OUT   organization_id: 'a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27',
OUT   start: 1435629465221,
OUT   end: 1435629465221,
OUT   resources: 
OUT    [ { resource_id: 'object-storage',
OUT        plans: 
OUT         [ { plan_id: 'basic',
OUT             aggregated_usage: 
OUT              [ { metric: 'storage', quantity: 1, cost: 1 },
OUT                { metric: 'thousand_light_api_calls', quantity: 2, cost: 0.06 },
OUT                { metric: 'heavy_api_calls', quantity: 200, cost: 30 } ] } ],
OUT        aggregated_usage: 
OUT         [ { metric: 'storage', quantity: 1 },
OUT           { metric: 'thousand_light_api_calls', quantity: 2 },
OUT           { metric: 'heavy_api_calls', quantity: 200 } ] } ],
OUT   spaces: 
OUT    [ { space_id: 'aaeae239-f3f8-483c-9dd0-de5d41c38b6a',
OUT        resources: 
OUT         [ { resource_id: 'object-storage',
OUT             plans: 
OUT              [ { plan_id: 'basic',
OUT                  aggregated_usage: 
OUT                   [ { metric: 'storage', q...
OUT 2015-10-06T19:35:53.187Z e-abacus-router 44 Route error - generator error - { message: 'Cannot read property \'summarizefn\' of undefined' } - TypeError: Cannot read property 'summarizefn' of undefined
OUT     at summarizefn (/home/vcap/app/lib/index.js:81:8)
OUT     at summarizeMetric (/home/vcap/app/lib/index.js:248:29)
OUT     at _.map._.collect (/home/vcap/app/node_modules/underscore/underscore.js:172:24)
OUT     at summarizeResource$ (/home/vcap/app/lib/index.js:257:37)
OUT     at tryCatch (/home/vcap/app/node_modules/babel-runtime/regenerator/runtime.js:67:40)
OUT     at GeneratorFunctionPrototype.invoke [as _invoke] (/home/vcap/app/node_modules/babel-runtime/regenerator/runtime.js:315:22)
OUT     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/vcap/app/node_modules/babel-runtime/regenerator/runtime.js:100:21)
OUT     at next (/home/vcap/app/node_modules/co/index.js:74:21)
OUT     at /home/vcap/app/node_modules/co/index.js:93:18
OUT     at Immediate._onImmediate (/home/vcap/app/node_modules/co/index.js:52:14)
OUT     at processImmediate [as _immediateCallback] (timers.js:367:17)

**Comment by jsdelfino** [comment]
This could be an issue when retrieving the resource configuration from the Abacus provisioning service.

Which version of Abacus are you running?

Does it have the following env variables in lib/aggregation/reporting/manifest.yml?
```
PROVISIONING: abacus-provisioning-stub
ACCOUNT: abacus-account-stub
```

**Comment by rdejana** [comment]
Yep, have both of those in the manifest.  I'm building from the master branch.

**Comment by jsdelfino** [comment]
This looks like a bug in the recent versions of the master branch. We'll look into it just after we resolve issue #69, which is currently breaking the reporting service even before hitting the issue you've reported... Stay tuned, will update here as soon as we have a resolution.

**Comment by jsdelfino** [comment]
@rdejana Looks like this is now fixed as we're able to run the demo again on CF with version Abacus version 2f55168. You'll need to get a clean build of that version with `npm run rebuild`, then `npm run cfpush` again. Can you let us know if that version works for you as well?

**Comment by rdejana** [comment]
Cool, I'll try later tonight or tomorrow AM.

thanks!
-r

**Comment by rdejana** [comment]
got past my error, so closing.  Still see some issues with the demo, but I'll poke around a bit more
