### ISSUE TITLE
Provisioning plugin do not have apis for mapping of metering, rating and pricing plans

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry-incubator/cf-abacus#686]
Can you please update the provisioning plugin as you did for cf-abacus-broker.

**Comment by hsiliev** [comment]
@cfmagnum The API defined in Abacus is a "Minimal example implementation"

As stated in its README:
> This minimal Abacus provisioning plugin example is provided only for demo and test purposes. An integrator of Abacus is expected to replace it with a real production implementation.

The broker project aims to incubate a possible extension of this API and if this proves successful we might bring back the changes into Abacus.

The broker version of the plugin is just a possible approach to this API. However you might want to hook a CRM system instead, a business process that will verify the legal aspects of the plans, or a automated validation of the plans. We wanted to play with all of these and to decide which of these  will work well. We also wanted to keep these 2 project separate to enable  innovation and experiments, while keeping the core stable, all at the same time.

Therefore I will close this issue. You can use the drop-in replacement of the provisioning from the broker, or (hopefully) even file a PR for changing it to fit your needs.
