### ISSUE TITLE
Getting error when I do "npm run cfpush"

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry-incubator/cf-abacus#690]
I am using following versions:
$ node -v
v7.10.1
$ npm -v
4.6.1

When I try to push using "npm run cfpush" I get follwing error. Please let me know which version I should use so this error will not appear.

Error:
-----> Restoring cache
       Skipping cache restore (disabled by config)
-----> Building dependencies
       Installing node modules (package.json + shrinkwrap)
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/cluster
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/debug
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/eureka
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/events
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/express
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/hystrix
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/launcher
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/lock
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/lrucache
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/moment
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/oauth
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/perf
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/rc
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/request
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/retry
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/router
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/transform
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/urienv
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/vcapenv
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/webapp
       npm ERR! addLocal Could not install /apps/cf-abacus/lib/utils/yieldable
       npm ERR! path /apps/cf-abacus/lib/utils/cluster
       npm ERR! code ENOENT
       npm ERR! errno -2
       npm ERR! syscall open
       npm ERR! enoent ENOENT: no such file or directory, open '/apps/cf-abacus/lib/utils/cluster'
       npm ERR! enoent This is most likely not a problem with npm itself
       npm ERR! enoent and is related to npm not being able to find a file.
       npm ERR! enoent

       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/app/.npm/_logs/2017-07-21T14_57_01_290Z-debug.log
-----> Build failed

       We're sorry this build is failing! You find more info about the nodejs buildpack here:
       https://docs.cloudfoundry.org/buildpacks/node/index.html

Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container

**Comment by hsiliev** [comment]
What's the version of the buildpack you are using? Does the problem reproduce with older buildpack?

**Comment by cfmagnum** [comment]
I am using nodejs-buildpack-v1.5.36.

**Comment by hsiliev** [comment]
We are using the same buildpack in our installation.

Do you have the project prepared for push as described in [step 2 on wiki](https://github.com/cloudfoundry-incubator/cf-abacus-broker/wiki/Deploying-the-Broker) ?

**Comment by hsiliev** [comment]
Any progress on this one? Did you tried running `npm build` or `npm run rebuild` and then pushing?

**Comment by cfmagnum** [comment]
I took fresh clone and tried again. It's worked fine. We can close this issue now. 

Thanks :)
