### ISSUE TITLE
test issue for Github <-> Tracker integration link

### ISSUE THREAD

**Issue by maximilien** [cloudfoundry-incubator/cf-abacus#71]
This is to test that a new story on the CF-Abacus Tracker is created from this issue.

**Comment by maximilien** [comment]
Yes. Seems it worked.

/cc @jsdelfino

**Comment by jsdelfino** [comment]
Woohoo!

**Comment by sasrin** [comment]
Nice... Now I do not need to worry about not creating corresponding work item at Pivotal Tracker.
