### ISSUE TITLE
How to count distinct measures?

### ISSUE THREAD

**Issue by micellius** [cloudfoundry-incubator/cf-abacus#715]
I have a requirement to measure distinct end-users of the SaaS application (Portal), and I'm wondering what would be the "Abacus"-way of doing this? I can think of several options, but non of them are supported by Abacus out-of-the-box.

* First option is to add configurable _filter_ phase to the pipeline in front of usage collector, where one can specify filter function that have access to all raw measures.
* Another option is to combine _filter_ functionality with one or several existing phases in pipeline. Similar to JavaScript's `map`, `reduce` and `filter` that pass the whole collection as the last argument of callback function. This will be not so efficient performance-wise.
* Alternatively, it may be metadata of metric or metering plan definition that specifies rules on which measures should be treated as duplicate. As far as I understand, Abacus already filters out duplicate measures, but it uses FNV Hash comparison implemented in `bloem` filters (that work with plain buffers). Using more "smart" hash implementations that take input semantics in account may probably solve the issue.
* By including user ID into `resource_instance_id` or `consumer_id` I can achieve aggregation on user-level. But still Abacus does not provide a way to aggregate across subset of resource instances or get number of consumers, and I'll need to have a custom aggregation sink to perform aggregation of aggregations.

_BTW, I thought about using Time-based metric type (since it is stateful), but it does not scale, when I need to keep track of tens of thousands of users._

So, what would be the recommended way to count distinct measures with Abacus?

**Comment by hsiliev** [comment]
Not so sure I fully understand your scenario, but if we consider something like:
```
{
  "start": 1396421450000,
  "end": 1396421451000,
  "organization_id": "us-south:54257f98-83f0-4eca-ae04-9ea35277a538",
  "space_id": "d98b5916-3c77-44b9-ac12-04456df23eae",
  "consumer_id": "app:d98b5916-3c77-44b9-ac12-045678edabae",
  "resource_id": "object-storage",
  "plan_id": "basic",
  "resource_instance_id": "user:ba4eae",
  "measured_usage": [
    {
      "measure": "visit",
      "quantity": 1
    }
  ]
}
```

This means Abacus would aggregate on user and space/org levels. If I understand correctly you also need to get a list of all consumers for a user, is this correct?

**Comment by micellius** [comment]
@hsiliev, thanks for proposal. The idea of what I'm trying to achieve is that if, for example, `user1` visited portal 3 times and `user2` visited 5 times, for each visit of each user measure is sent to Abacus, and at the end there should be a way to get aggregated value 2 as a number of unique users in the given time frame (for example, month).

By implementing your proposal (where user is part of `resource_instance_id`), it is possible to get all users as part of "Usage Summary Report", not number of them. Also, the list of resource instances is not time-framed. Therefore, to reason about number of resource instances used in certain period of time, there should be separate request to get "Resource Instance Report" for each user. Then all non-zero usages should be filtered out and summed. I would expect all logic above to be done inside Abacus, and the final result to be returned somehow in one report.

What I thought is to send something like:

```javascript
"measured_usage": [
    {
      "measure": "visit",
      "quantity": "user1"
    }
  ]
```

and in the _accumulate_ function, for example, to have

```javascript
(a, qty, start, end, from, to, twCell) => 
    end < to && start >= from ? Object.assign({}, a, {[qty]: true}) && a : a
```

and in _aggregate_ function to have

```javascript
(a, prev, curr, aggTwCell, accTwCell) => Object.keys(curr).length
```

but I'm not sure it will work fine for large numbers of unique users (object created during accumulation phase will be very large).

I'm not an Abacus guru, and for sure missing something, therefore looking forward for the guidelines how to make it right.

**Comment by KRuelY** [comment]
Assuming what you want is metering 2 metrics(The charge of the service would be based on 2): The first one is the number of unique visitor, and the second one is the number of visits.

There are some ways of doing this: 

1. Define unique visitor as a metric:

```
"resource_instance_id": "user1",
"measured_usage": [
  {
    "measure": "unique_visitor",
    "quantity": 1
  }, {
    "measure": "visit",
    "quantity": 3
  }]
```

For visitor, you will need to define the accumulate function as a Math.max function (the quantity 1 is treated like true -- so you can only submit quantity 1.). The aggregation would be just normal addition. 

Now if user2 submission come in:

```
"resource_instance_id": "user2",
"measured_usage": [
  {
    "measure": "unique_visitor",
    "quantity": 1
  }, {
    "measure": "visit",
    "quantity": 5
  }]
```

The aggregation would results in:

unique_visitor: 2
visit: 8.

---

You can also define metering plan this way if you don't want to submit 2 metrics:

```
{
  plan_id: 'test-metering-plan',
  measures: [
    {
      name: 'visit,
      unit: 'visit'
    }],
  metrics: [
    {
      name: 'visit',
      unit: 'visit',
      meter: ((m) => new BigNumber(m.visit).toNumber()).toString(),
      accumulate: addition
    },
    {
      name: 'unique_user',
      unit: 'user',
      meter: ((m) => m.visit ? 1 : 0).toString(),
      accumulate: ((a, qty, start, end, from, to, twCell) =>
        end < from || end >= to ? null : Math.max(a, qty)).toString()
    }]
}
```
The accumulate of unique user is basically always return 1 if there was a visit measure submitted during the month.

**Comment by micellius** [comment]
@KRuelY, thanks for proposal. However, uniqueness of the user may be calculated only relatively to certain time window that only Abacus knows. Therefore, service can't send `unique_user` measure. 

Consider the following case, where Usage Summary Report was requested for 5sec after `now`:

__Measures sent to collector__

> same: `organization_id`, `space_id`, `consumer_id`, `resource_id`, `plan_id`

| User (`resource_instance_id`) | Time (start === end - 1) |
|------|------|
| user1 | yesterday - 3 |
| user2 | yesterday - 2 |
| user2 | yesterday - 1 |
| user3 | now - 3 |
| user1 | now - 2 |
| user4 | now - 1 |

_Sample_

```Javascript
{
  start: 1504448430054,
  end: 1504448430055,
  organization_id: 'org:1',
  space_id: 'space:1',
  consumer_id: 'external:1',
  resource_id: 'portal',
  plan_id: 'basic',
  resource_instance_id: 'user1',
  measured_usage: [{
    measure: 'visits',
    quantity: 1
  }]
}
```

__Metering plan (meter, accumulate and aggregate functions as you propose)__

```Javascript
{
  plan_id: 'basic-visits',
  measures: [
    {
      name: 'visits',
      unit: 'USER'
    }],
  metrics: [
    {
      name: 'visits',
      unit: 'USER',
      type: 'discrete',
      meter: ((m) => m.visits ? 1 : 0).toString(),
      accumulate: ((a, qty, start, end, from, to, twCell) =>
          end < from || end >= to ? 0 : Math.max(a, qty)).toString(),
      aggregate: ((a, prev, curr, aggTwCell, accTwCell) => a + curr).toString()
    }]
}
```

__Usage summary result that I need__

| Window | Quantity/Cost/Summary/Charge |
|---------|----------|
| Month | __4__ |
| Day | 3, 2 |
| Hour | 3 |
| Minute | 3 |
| Second | null |

Since accumulation and aggregation in Usage Summary Report are for `resource_id` and not for `resource_instance_id` the actual result will be different.

__Actual result (tested by code)__

> BTW, the order in which results are present in report are reverse to what is stated in [wiki](https://github.com/cloudfoundry-incubator/cf-abacus/wiki/Time-Windows)

| Window | Quantity/Cost/Summary/Charge |
|---------|----------|
| Month | 6, null |
| Day | 3 |
| Hour | 3 |
| Minute | 3 |
| Second | null |

Report will contain 4 resource instances (=users), but 6 unique users in monthly summary, which is incorrect.

**Comment by KRuelY** [comment]
Hello,

The aggregation function generally should be a + curr - prev.

Aggregate: Org's total usage - instance's last accumulated usage + instance's new accumulated usage.

**Comment by micellius** [comment]
Thanks a lot @KRuelY !!!

Changing the aggregation function to 

```javascript
((a, prev, curr, aggTwCell, accTwCell) => a + curr - prev).toString()
```

indeed fixed the numbers in the report to what I expect.

Now I'll need some time to understand how it works under the hood... As for now, I think the most important missing point for me was that accumulation and aggregation is made on the __instance__ level, even when in the report it appears on the level of resource type.
