### ISSUE TITLE
Collector does not authorize deletion of error usages

### ISSUE THREAD

**Issue by momchil-sap** [cloudfoundry-incubator/cf-abacus#723]
Hi,

I notice that the Collector component does not specify a `dscope` for the error configuration:
https://github.com/cloudfoundry-incubator/cf-abacus/blob/800faab967a4d61ab7f7cd21017a8fb4bf72f08e/lib/metering/collector/src/index.js#L334-L345

However, the `dataflow` component skips authorization for deletion of error usages if the `dscope` configuration has not been specified:
https://github.com/cloudfoundry-incubator/cf-abacus/blob/800faab967a4d61ab7f7cd21017a8fb4bf72f08e/lib/utils/dataflow/src/index.js#L533-L537

We need to add a `dscope` field to the `error` configuration of the Collector component.

**Comment by hsiliev** [comment]
Fixed with https://github.com/cloudfoundry-incubator/cf-abacus/commit/bc24c208ed05f912317f9db7be66be92c13cf01b
