### ISSUE TITLE
Accumulated Usage Logs

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#75]
I am using the accumulated-usage-logs db to query for resource instance level accumulation for a given period of time. I see that there are two kind of docs in the database. The incoming data from the metering application and the processed accumulated usage doc. Though these two doc types have different key patterns, a range query returns both the docs. 

I thought these always occur in pairs, however they don't! This results in a problem while picking the processed accumulated usage from a result set of a range query. 

I have two suggestions to overcome this problem.

* Choosing a different key pattern for both the docs
```javascript
// Accumulated Log
'k/orgid/rid/plan/t/0001435629465220/0001444327281770-0-1-0' 
=> 'k/accumulated/orgid/rid/plan/t/0001435629465220/0001444327281770-0-1-0' 
// Metered Log
'k/orgid/rid/plan/t/000end/start/end' 
=> 'k/metered/orgid/rid/plan/t/000end/start/end'
```
* Using different database log databases for incoming and processed docs.

**Comment by jsdelfino** [comment]
@rajkiranrbala That log structure is probably going to change a bit anyway as I'm working on some changes to our DB handling and DB recovery code (see \[1\] for the related user story). I'll report back here when that's in place.

[1] https://www.pivotaltracker.com/story/show/101098214

**Comment by jsdelfino** [comment]
The pattern used for doc ids has changed in 0.0.2-rc.0 and subsequent versions. Can you check that the new pattern helps resolve your issues with range queries? Thanks

**Comment by jsdelfino** [comment]
Closing for now as the patterns are really different now and shouldn't confuse the range queries anymore. Please reopen if needed.
