### ISSUE TITLE
question about :t in abacus-usage-reporting API

### ISSUE THREAD

**Issue by eujungkim** [cloudfoundry-incubator/cf-abacus#781]
I try to use abacus-usage-reporting API (GET /v1/metering/organizations/:organization_id/spaces/:space_id/resource_id/:resource_id/resource_instances/:resource_instance_id/consumers/:consumer_id/plans/:plan_id/metering_plans/:metering_plan_id/rating_plans/:rating_plan_id/pricing_plans/:pricing_plan_id/t/:t/aggregated/usage/:time).
Would you explain the meaning of "t"? 
I don't know what value is suitable to :t and difference between :t and :time.

**Comment by hsiliev** [comment]
The consumer report API is meant to be used in conjunction with the org usage report. The flow envisioned is:
1. get org usage report
2. scan the org report 
3. get instance usage report for each consumer

`:time` provides Abacus with the month for which we return the report
`:t` is the time for which the usage was submitted (`end` field of the usage report)

**Comment by eujungkim** [comment]
Thank you for your quick answer.
Can I get some example value for :time and :t to retrieve usage report for September 2017?

**Comment by hsiliev** [comment]
To be sure you'll get the data for the whole of September you might specify the end of the month for `time`:
```bash
node -p "new Date('Oct 2017').valueOf() - 1"
1506805199999
```

The value of `t` can be obtained from the org report. For example in my local environment:
```bash
npm start
npm run demo

#
# Get org report from the start of the month to the current moment (omitting :time = now)
#
curl -H 'Content-Type: application/json' http://localhost:9088/v1/metering/organizations/us-south:a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27/aggregated/usage

...
... <report output> ...
                  "resource_instances": [
                    {
                      "id": "0b39fa70-a65f-4183-bae8-385633ca5c87",
                      "t": "0001509008400000",
                      "p": 1509010714980
                    }
                  ],
...
```

So here we have one resource instance with `t` that equals `0001509008400000`

**Comment by hsiliev** [comment]
Updated wiki with the info above https://github.com/cloudfoundry-incubator/cf-abacus/wiki/Usage-Reports

I'll close the issue, but feel free to reopen it if you have more questions
