### ISSUE TITLE
question for multi cf service metering

### ISSUE THREAD

**Issue by eujungkim** [cloudfoundry-incubator/cf-abacus#782]
I want to meter 2 services. (for example, p-mysql-shared and p-rabbitmq).
So I worked like this...

1) I added plans like belows,
        lib/plugins/provisioning/src/plans/metering/standard-p-mysql-shared.js
        lib/plugins/provisioning/src/plans/metering/standard-p-rabbitmq.js
        lib/plugins/provisioning/src/plans/pricing/p-mysql-shared-pricing-standard.js
        lib/plugins/provisioning/src/plans/pricing/p-rabbitmq-pricing-standard.js
        lib/plugins/provisioning/src/plans/rating/p-mysql-shared-rating-standard.js
        lib/plugins/provisioning/src/plans/rating/p-rabbitmq-rating-standard.js        
        
2) I added plan mappings in lib/config/mappings/src/plans/metering.json like below
{
  ...
  "p-rabbitmq": {
    "standard": "standard-p-rabbitmq"
  },
  "p-mysql-shared": {
    "standard": "standard-p-mysql-shared"
  }
}
and similar things to 
        lib/config/mappings/src/plans/pricing.json
        lib/config/mappings/src/plans/rating.json

3) I created UAA clients
uaac client add abacus-cf-services --name abacus-cf-services --authorized_grant_types client_credentials --scope abacus.usage.p-rabbitmq.read,abacus.usage.p-rabbitmq.write,abacus.usage.p-mysql-shared.read,abacus.usage.p-mysql-shared.write --authorities abacus.usage.p-rabbitmq.read,abacus.usage.p-rabbitmq.write,abacus.usage.p-mysql-shared.read,abacus.usage.p-mysql-shared.write --secret secret

4) I modified lib/cf/services/manifest.yml
    SERVICES: '{
      "p-rabbitmq": {
        "plans": ["standard"]
      },
      "p-mysql-shared": {
        "plans": ["standard"]
      }
    }'
    CLIENT_ID: abacus-cf-services

But the metering datas of p-mysql-shared did not come in.
Can you check what is my mistake?

**Comment by hsiliev** [comment]
@eujungkim What is the version (commit id) of the service bridge you have? Any logs?

Is your `SERVICES` variable multiline (http://yaml-multiline.info/)? It doesn't look like this from what you pasted above.

**Comment by eujungkim** [comment]
I used commit id 1648da09fb4bf322ce363ddfa490b82f8dafe21e.
There is no special logs in abacus-cf-services.

Before doning with 2 services(p-rabbitmq, p-mysql-shared), I worked with only 1 service(p-rabbitmq) and it worked well.
I could find collection datas of p-rabbitmq in MongoDB.
But after I applied 2 services no data comes from either p-rabbitmq nor p-mysql-shared.

Differences between 2 cases are like below

<1 service : p-rabbitmq>
1. UAA client
  abacus-p-rabbitmq
    scope: abacus.usage.p-rabbitmq.read abacus.usage.p-rabbitmq.write
    resource_ids: none
    authorized_grant_types: client_credentials
    autoapprove:
    authorities: abacus.usage.p-rabbitmq.read abacus.usage.p-rabbitmq.write
    name: abacus-p-rabbitmq
2. /cf/services/manifest.yml
    SERVICES: '{
      "p-rabbitmq": {
        "plans": ["standard"]
      }
    }'
    **CLIENT_ID: abacus-p-rabbitmq**
    
<2 services : p-rabbitmq and p-mysql-shared>
1. UAA client
  abacus-cf-services
    scope: abacus.usage.p-mysql-shared.write abacus.usage.p-rabbitmq.read
        abacus.usage.p-mysql-shared.read abacus.usage.p-rabbitmq.write
    resource_ids: none
    authorized_grant_types: client_credentials
    autoapprove:
    authorities: abacus.usage.p-mysql-shared.write abacus.usage.p-rabbitmq.read
        abacus.usage.p-mysql-shared.read abacus.usage.p-rabbitmq.write
    name: abacus-cf-services

2. /cf/services/manifest.yml
    SERVICES: '{
      "p-rabbitmq": {
        "plans": ["standard"]
      },
      "p-mysql-shared": {
        "plans": ["standard"]
      }
    }'
    **CLIENT_ID: abacus-cf-services**
    
Are there something wrong in my setting?

**Comment by PlamenDoychev** [comment]
You can use UAA client (for example with id `abacus-service-bridge`) with [system scope](https://github.com/cloudfoundry-incubator/cf-abacus/wiki/Security#system-token) to avoid adding multiple scopes.

In this way your client will have only `abacus.usage.write,abacus.usage.read` and you don't need to add more as your service numbers increase.

**Comment by eujungkim** [comment]
Sorry!!!! It was my mistakes.
Second service was not metered because the plan of service instance and metering plan did not match.
Thank you for your kind and quick response.
I'll close this issue.
I'm sorry and thank you again.

**Comment by hsiliev** [comment]
Glad to hear the bridge is working!
