### ISSUE TITLE
question for accumulate function

### ISSUE THREAD

**Issue by eujungkim** [cloudfoundry-incubator/cf-abacus#785]
I use commit version 1648da09fb4bf322ce363ddfa490b82f8dafe21e now.
In your /cf-abacus/lib/plugins/provisioning/src/plans/metering/standard-linux-container.js, 
you multiply each consuming and previous_consuming by (past + future) .
--------------------------------------------------------------------------
        const past = from - start;
        const future = to - start;
        const td = past + future;
        return {
          // Keep the consuming & since to the latest value
          consuming: a && a.since > start ? a.consuming : qty.consuming,
          consumed: new BigNumber(qty.consuming).mul(td)
            .add(new BigNumber(qty.previous_consuming).mul(td))
            .add(a ? a.consumed : 0).toNumber(),
          since: a && a.since > start ? a.since : start
        };
--------------------------------------------------------------------------
In this case, if future = 300, past = 100, start = 200 for example, consumed equals to a.consumed. (no value added)

But I think, my accumulate function for linux-container should be like below. (pseudo code)
    consumed : a.consumed + (from - start) * qty.previous_consuming + (to - start) * qty.consuming

Can you explain why you use td?
(If I mis-understand your intension in formular, I'm sorry In advance.)

**Comment by hsiliev** [comment]
Hi @eujungkim,

In short `td` is the direction we use to calculate the usage delta `consumed`.  We store this delta to help with events that are recieved out-of-order in the pipeline (app stop, then start).

I know that this does not make much sense alone, but there is a description of the linux-container: https://github.com/cloudfoundry-incubator/cf-abacus/wiki/Metric-Types#sample-time-based-metric to get you into the details.

HTH

**Comment by eujungkim** [comment]
Thank you @hsiliev 
I'll read the document. I think cf-abacus team works very hard because documents are updated very quickly and frequently. WOW
