### ISSUE TITLE
question about scaling running abacus

### ISSUE THREAD

**Issue by eujungkim** [cloudfoundry-incubator/cf-abacus#797]
I pushed Abacus to CF and all applications of Abacus had single instance for each.
And it worked well, I checked charge value of some organization is fine(plus value) in abacus-usage-reporting.

After then I just scaled Abacus to profile small.
When I retrieved report from abacus-usage-reporting, the charge value of same organization was minus value.

Is there any step should I follow when I try to scale Abacus to profile small or large?

I read Scaling Abacus document (https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/doc/conf.md#scaling-abacus) and undertand well.
But it does not explain how to scale Abacus running already.

**Comment by hsiliev** [comment]
@eujungkim Do you use persistent DB or the pouchdb test server we provide in Abacus by default?

**Comment by eujungkim** [comment]
@hsiliev No. I use standalone MongoDB.

**Comment by hsiliev** [comment]
The negative value can happen if Abacus got only stop without start for an application. 

Do you run purge between the first and second cf push?

**Comment by eujungkim** [comment]
Because I want to test what happen to already made MongoDB collections and weather metering data is retained, so I did not run below purge between the first and second cf push.
  "/v2/app_usage_events/destructively_purge_all_and_reseed_started_apps"
  "/v2/service_usage_events/destructively_purge_all_and_reseed_existing_instances"
  
I want to rewrite my question like below.
-------------------------------------------------

My working procedure according to time is as follows.

1. deploy CF
2. run purge of app_usage_events and service_usage_events
3. push Abacus in single profile (single instance)
4. collect metering data for a certain period of time.
5. Abacus need more resources.
6. TODO __________________________
7. delete Abacus(single profile) & push Abacus(large profile : 4 instance per each)
8. collect metering data for a certain period of time.
9. Abacus does not need much resources.
10. TODO __________________________
11. delete Abacus(large profile) & push Abacus(small profile : 2 instance per each)
12. collect metering data for a certain period of time.

My questions are
- What should I do at 6 or 10 process?
  example) nothing, purge app and service events, backup and drop MongoDB collections, etc
- When is the proper time to do 6, 10 process? 
  example) start of month, anytime ok, etc
- What should I do about my MongoDB? 
  example) nothing, backup and drop MongoDB collections, etc
- What dose happen to old metering data?
  When scale in from 4 to 2, what dose happen to old collections?

And another question is, is this issue board proper channel for question like this?
If you let me know another, I'll use it.

Thank you for your kind and quick answer.

**Comment by hsiliev** [comment]
@eujungkim I created a page with the info we have scattered around the repo in this page:
https://github.com/cloudfoundry-incubator/cf-abacus/wiki/Scale

Can you please review it and post comments and more questions here or in Slack (whatever works for you best)?

**Comment by eujungkim** [comment]
Thank you. I'll read it carefully and post comments later.

**Comment by eujungkim** [comment]
1. When I applied small profile, two abacus-usage-meter application were made like below. (not 2 instances)
 - abacus-usage-meter-0
 - abacus-usage-meter-1
 
 In /lib/metering/meter/.apprc, metering service is written as stateful application, too.
small:
  APPS: 2
  INSTANCES: 1
  DB_PARTITIONS: 2
  ACCUMULATOR_APPS: 2
 
But in your wiki page, metering service is described as "Stateless".
https://github.com/cloudfoundry-incubator/cf-abacus/wiki/Scale#metering-service

Would you check which one is correct? Is metering service stateful or stateless?

2. I read wiki page of scale and conclude like below.
1) Scale-out is possible anytime.
2) If I scale-in cf-abacus in the middle of a month, some data can be omitted from accumulation and aggregation.
   (If DB_PARTITION is changed from 4 to 2, collections in index 2 and 3 can be omitted after scale-in.)
   So do scale-in in the start of a month.

Please review that my rules are appropriate.

**Comment by hsiliev** [comment]
Hi @eujungkim,

Thanks for reviewing the wiki. Your feedback is much appreciated.

You're right - the `meter` is scaled via apps, instead of instances. It maintains a lock per document, so it has a state. However I don't think there is a good reason to not scale it via instances, since it also does duplicate detection, and we can handle conflicts due to retries. We need to check this and update the profile. I'll leave this issue open until we double check it.

Reducing partitions is indeed dangerous since you lose access to data. Added it to the wiki. We consider DB scaling as one-time operation. You don't gain much by reducing the number of partitions, since the data size remains the same. It simply logical separation. On the other side if you use our pseudo-sharding, reducing the number of services bound to Abacus apps can save you quite some costs.

**Comment by hsiliev** [comment]
I'm closing the issue, but feel free to reopen it in case you need help or have additional questions
