### ISSUE TITLE
OAuth bearer access token validation failed, invalid signature

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry-incubator/cf-abacus#823]
I m trying to authenticate the reporting URL using user-specific token documentation, and my manifest file configuration is : 

    AUTH_SERVER: https://api.<CF domain>:443
    CLIENT_ID: abacus-linux-container
    CLIENT_SECRET: secret
    JWTKEY: |
      -----BEGIN PUBLIC KEY-----
      
      -----END PUBLIC KEY-----
    JWTALGO: RS256
    THROTTLE: 2

When I hit the URL from postman plugin and passing the token in header to access the reporting URL , it is giving me error of invalid signature, and i use these command to generate public key :   

ssh-keygen -t rsa -b 4096 -f jwtRS256.key
openssl rsa -in jwtRS256.key -pubout -outform PEM -out jwtRS256.key.pub  

So please tell me where I am going wrong, and if you have any proper documentation for authorization
of reporting URL , please provide on cf-abacus.

**Comment by hsiliev** [comment]
Hi @cfmagnum,

You should use the UAA public key and algorithm used to encrypt it. These can be found in the BOSH manifest:
https://github.com/cloudfoundry-incubator/cf-abacus/wiki/Authentication-and-Authorization#cf-uaa

**Comment by cfmagnum** [comment]
Hi @hsiliev i have used the public key in JWTKEY , and i have already mentioned the command in the issue which I have used to generate the key.  
It is like this,
 
    SECURED: true
    AUTH_SERVER: https://api.<CF domain>:443 
    CLIENT_ID: abacus-linux-container
    CLIENT_SECRET: Secret
    JWTKEY: |
      -----BEGIN PUBLIC KEY-----
      MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAu/6yqviWvR1MdyTL44eb
      o4F8IZenKFDt6z6N+Hq6/mu8+E28KqitAyiluRtlkyBsDMy7Wn+UcN4CrEmRebyM
      r6iPlXkyXzzkl4StFnup5uQOznfhhMKaezM+J0DKc9WKZHqGrceRlf16YrKDnlD1
      XkO9qWKeuyeflCoDhWGd0urKrx4Yt+nvaFL0+GeXbLnbzZFuia42f73tr8SuyGBg
      94vLuj6pRu5bs2Fpyd3KhEQkHY3nkps+UtOyZ8GsOQyuv4ODnpFMa6Jiu7RAC+39
      iu48Zu2yWB2+bt+zfPNL4ebuVKDvgSp15xM9qmSvNz8+VdtU+WB3J8d1uZvUqQEA
      lPH1SE0O6sf+FvZj9IvUmOe+VZR/zdiNAdz/XACpfmH5RRaotqe6gwHphMgnSZSh
      yZurru4QV2Z2XpgPQY6UToMDDBz94jERS0o81SkAAgRHmjOCg3CH/W83KOaGIgJB
      w26bQl7DcNRcVnYWuvP0fgh2oaRSvB4LWoesQmOcC1+J1DHw0kRJuSG3Y49r4EWq
      kdKKlC3EXKVvqHiMnavGNaasqJrv1iKaNYCRnvWDrypWHrVVZJsRfd96VfQPH7IV
      as4TvpfdyaFHrJH3MPREJmxTj5fzBTKRV3p4wozY4MT/fQRckJyGuq2yuQ8PWjQ4
      h3QhEMwOOvq59IK9R9HaGusCAwEAAQ==
      -----END PUBLIC KEY-----
    JWTALGO: RS256
    THROTTLE: 2

**Comment by hsiliev** [comment]
@cfmagnum Here is the manifest we use (cf env output):
```
ACCOUNT: abacus-account-plugin
API: https://api.<domain>:443
AUTH_SERVER: https://api.<domain>:443
BATCH_SIZE: 50
CLIENT_ID: abacus
CLIENT_SECRET: <secret>
CLUSTER_HEARTBEAT: 120000
CLUSTER_WORKERS: calculate
CONF: large
DBALIAS_ACCUMULATOR: db-common
DBALIAS_AGGREGATOR: db-aggregator
DBCLIENT: abacus-mongoclient
DEBUG: e-abacus-*
EUREKA: abacus-eureka-plugin
EUREKA_PASSWORD: <secret>
EUREKA_USER: abacus-hystrix
EVAL_TIMEOUT: 2000
EVAL_VMTYPE: vm2
JWTALGO: RS256
JWTKEY: -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy1Jr7/BFnTUbVOOgDVyg
yQlm1oStUkDXhXHOA2EJxvwQT4NGNB4zD0Nyr1K5mEQVSq7/kL0ha7CbGkBy1y0I
gZjEktsK1qoxOnlAQstFz1DR453KqwL4sqQKIphFcyOv7qTUfcbjc8kIS/fKbzKU
UWD8rz0ULJyhj2/My1uwwRK1qwtI10FLBVV/IO1ADSK+7Z+6NAya+7eqvJ9vTKoT
O3ZUzrEeGZSOYmdV01d0jtpDtYmaspoP/xbnNSFR7yyCZprlsvNSlHiYgKu8WTXQ
uRVnLASulhcDb+4ud89yHKFAlLQbw4U2caWSzAAPUGhICYljFtzlIG8qwuRGHbpM
swIDAQAB
-----END PUBLIC KEY-----

NODE_MODULES_CACHE: false
NODE_OPTS: --max_old_space_size=1536
PRIMARY_DOMAIN: <domain>
PROVISIONING: abacus-provisioning-plugin
REPLAY: 1800000
SECURED: true
SKIP_SSL_VALIDATION: false
SLACK: 32D
THROTTLE: 100
```

Do you have API set in your reporting app manifest?

**Comment by cfmagnum** [comment]
@hsiliev Hey I have used UAA Public key, earlier i was using wrong public key so now it is working.
Thank you for the help. you can close this issue

**Comment by hsiliev** [comment]
Glad it is working :)
