### ISSUE TITLE
12 usage submissions to Usage Collector takes more than 22 seconds

### ISSUE THREAD

**Issue by sasrin** [cloudfoundry-incubator/cf-abacus#84]
> abacus-usage-collector-itest@0.0.1-dev.3 itest /Users/developer/work/cf-abacus/node_modules/abacus-usage-collector-itest
> mocha --command "-o" "1" "-i" "4" "-u" "3"

Testing...

  abacus-usage-collector-itest

> abacus-dbserver@0.0.1-dev.3 start /Users/developer/work/cf-abacus/node_modules/abacus-dbserver
> ./dbserver start

> abacus-usage-collector@0.0.1-dev.3 start /Users/developer/work/cf-abacus/node_modules/abacus-usage-collector
> webapp start --port 9080

> abacus-provisioning-stub@0.0.1-dev.3 start /Users/developer/work/cf-abacus/node_modules/abacus-provisioning-stub
> webapp start --port 9380

    1) collect measured usage submissions

  0 passing (22s)
  1 failing

 1) abacus-usage-collector-itest collect measured usage submissions:
     Error: timeout of 22000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by sasrin** [comment]
Before the latest updates we were able to handle 125 usage submissions in 9 seconds.

> abacus-usage-collector-itest@0.0.1-dev.3 itest /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-usage-collector-itest
> mocha --command "-o" "5" "-i" "5" "-u" "5"

Testing...

[0m[0m
[0m  abacus-usage-collector-itest[0m

> abacus-provisioning-stub@0.0.1-dev.3 start /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-provisioning-stub
> webapp start --port 9380


> abacus-dbserver@0.0.1-dev.3 start /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-dbserver
> ./dbserver start


> abacus-usage-collector@0.0.1-dev.3 start /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-usage-collector
> webapp start --port 9080


  [32m  âœ“[0m[90m collect measured usage submissions[0m[31m (9114ms)[0m


[92m [0m[32m 1 passing[0m[90m (9s)[0m


Run time 9988ms

**Comment by sasrin** [comment]
> abacus-usage-collector-itest@0.0.1-dev.3 itest /Users/developer/work/cf-abacus/node_modules/abacus-usage-collector-itest
> mocha --command "-o" "1" "-i" "3" "-u" "3"

Testing...


  abacus-usage-collector-itest

> abacus-dbserver@0.0.1-dev.3 start /Users/developer/work/cf-abacus/node_modules/abacus-dbserver
> ./dbserver start


> abacus-provisioning-stub@0.0.1-dev.3 start /Users/developer/work/cf-abacus/node_modules/abacus-provisioning-stub
> webapp start --port 9380


> abacus-usage-collector@0.0.1-dev.3 start /Users/developer/work/cf-abacus/node_modules/abacus-usage-collector
> webapp start --port 9080

  abacus-provisioning-stub 35621 Retrieving info for resource instance { region: 'us-south',
  org_id: 'a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27-1',
  space_id: 'aaeae239-f3f8-483c-9dd0-de5d41c38b6a-1',
  consumer_id: 'bbeae239-f3f8-483c-9dd0-de6781c38bab-1',
  resource_id: 'test-resource',
  plan_id: 'basic',
  resource_instance_id: '0b39fa70-a65f-4183-bae8-385633ca5c87-1-1',
  time: 1435629465220 } +0ms
  abacus-provisioning-stub 35621 Finding resource config for resource id test-resource at time 1435629465220 +3ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465220 in local resources +1ms
  abacus-provisioning-stub 35621 Retrieving info for resource instance { region: 'us-south',
  org_id: 'a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27-1',
  space_id: 'aaeae239-f3f8-483c-9dd0-de5d41c38b6a-1',
  consumer_id: 'bbeae239-f3f8-483c-9dd0-de6781c38bab-1',
  resource_id: 'test-resource',
  plan_id: 'basic',
  resource_instance_id: '0b39fa70-a65f-4183-bae8-385633ca5c87-1-1',
  time: 1435629465220 } +251ms
  abacus-provisioning-stub 35621 Finding resource config for resource id test-resource at time 1435629465220 +0ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465220 in local resources +1ms
  abacus-provisioning-stub 35621 Retrieving info for resource instance { region: 'us-south',
  org_id: 'a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27-1',
  space_id: 'aaeae239-f3f8-483c-9dd0-de5d41c38b6a-1',
  consumer_id: 'bbeae239-f3f8-483c-9dd0-de6781c38bab-1',
  resource_id: 'test-resource',
  plan_id: 'basic',
  resource_instance_id: '0b39fa70-a65f-4183-bae8-385633ca5c87-1-2',
  time: 1435629465220 } +114ms
  abacus-provisioning-stub 35621 Finding resource config for resource id test-resource at time 1435629465220 +0ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465220 in local resources +0ms
.....
......

... 

 abacus-provisioning-stub 35621 Finding resource config for resource id test-resource at time 1435629465222 +0ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465222 in local resources +0ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465220 in database +13s
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465221 in database +1ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465220 in database +0ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465220 in database +10ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465220 in database +5ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465220 in database +0ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465221 in database +5ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465221 in database +0ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465222 in database +0ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465222 in database +0ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465222 in database +0ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465221 in database +0ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465222 in database +0ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465222 in database +1ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465221 in database +1ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465220 in database +1ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465221 in database +1ms
  abacus-provisioning-stub 35621 No resource config found for id test-resource at time 1435629465222 in database +1ms

**Comment by jsdelfino** [comment]
Looks like problems with @rajkiranrbala's provisioning service implementation. The resource validation logic fails to find our test-resource so issues a ton of db queries to attempt to find it in the provisioning db.

**Comment by jsdelfino** [comment]
Looking into the issues caused by that provisioning service...
