### ISSUE TITLE
Is there a reason to delete the org in cf-test-infra? 

### ISSUE THREAD

**Issue by findneville** [cloudfoundry-incubator/cf-abacus#852]
I want to submit a pull request to fix some of the pipeline issues with https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/etc/concourse/test-pipeline.yml but want to check before submitting. 

Is there a reason why you are deleting the org and recreating it in the cf-test-infra script 
https://github.com/cloudfoundry-incubator/cf-abacus/blob/252467b2283f238db942aa11b5aba9ad7b691b55/etc/concourse/scripts/cf-test-infra#L16

If people use an existing org, they are in for a surprise and there are no warnings in the vars file about the deletion/recreation of the org. 

Let me know if there was a logic behind this and I will submit corrections accordingly

**Comment by findneville** [comment]
I have submitted a PR to fix some issues with the test pipeline

**Comment by hsiliev** [comment]
Merged the request.

The delete was part of an effort to allow parallel execution of tests. We wanted to have tests run in short-living orgs/spaces to make testing easier.
