### ISSUE TITLE
How can I increase the request timeout of abacus-usage-reporting?

### ISSUE THREAD

**Issue by eujungkim** [cloudfoundry-incubator/cf-abacus#871]
For large organization when I request '/v1/metering/organizations/:organization_id/aggregated/usage' to abacus-usage-reporting, 504 gateway time-out is occurred sometimes.
It seems that the request timeout of abacus-usage-reporting is set as 30 seconds.
How can I increase its request timeout?

**Comment by hsiliev** [comment]
You need to set for reporting:
```
# default 30 sec
CLUSTER_HEARTBEAT=120000
# default 60 sec
BREAKER_TIMEOUT=120000
```

The cluster module will kill reporting if it occupied the event loop for more than 30 seconds (default). I guess this is the problem you face now. If this succeeds, we have breaker in place that will cut the connection after 60 seconds. So you need both to go up to get a slow response working.

Even so this might be killed by OS or router in case there is no response on the line for 30 seconds.

The correct way to fix this would be to:
* use GraphQL to minimize the response
* improve reporting

**Comment by hsiliev** [comment]
The real issue here is #646 and we're still working on it, so I'll close this as a duplicate
