### ISSUE TITLE
Pipelines failing with yarn error

### ISSUE THREAD

**Issue by findneville** [cloudfoundry-incubator/cf-abacus#877]
Both my test and deployment pipelines are failing today with the error below

>> Deploying Abacus ...
yarn run v1.3.2                                                                
$ bin/cfstage medium                                                           
Using 4 parallel processes
/tmp/build/b0d51b9f/abacus /tmp/build/b0d51b9f/abacus
/bin/bash: -c: option requires an argument
error Command failed with exit code 123.                                       
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by findneville** [comment]
Did not help.. Same error

>> Deploying Abacus ...
yarn run v1.3.2                                                                
$ bin/cfstage medium                                                           
Using 4 parallel processes
/tmp/build/b0d51b9f/abacus /tmp/build/b0d51b9f/abacus
/bin/bash: -c: option requires an argument
error Command failed with exit code 123.                                       
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by hsiliev** [comment]
The old pipeline is no-longer supported and we want to replace it with a new one with #1057 

This issue is now obsolete after we removed the old scripts and definitions, so I'm closing it
