### ISSUE TITLE
Benefit of the OSBAPI v2.13 schema field

### ISSUE THREAD

**Issue by denicaM** [cloudfoundry-incubator/cf-abacus#886]
According to [v2.13](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md) of the spec schema object for the parameters provided on create or update should be supported. The abacus service broker could delegate to the platform that validation instead of manually doing it in the code.

_* The issue originally was reported in the deprecated cf-abacus-broker repo: https://github.com/cloudfoundry-incubator/cf-abacus-broker/issues/206_

**Comment by hsiliev** [comment]
Implemented with https://github.com/cloudfoundry-incubator/cf-abacus/commit/b8782680318a7162df9b2d39e094b977444411cf
