### ISSUE TITLE
Some tests use timers and randomly break when Travis-CI gets slower

### ISSUE THREAD

**Issue by jsdelfino** [cloudfoundry-incubator/cf-abacus#89]
A number of tests use timers and randomly break the build when Travis-CI gets slower at certain times of the day. No test should use real timers (if timers are needed then mocked clock timers should be used instead) as this makes them unreliable.

**Comment by hsiliev** [comment]
Do you think that using [eventually](http://chaijs.com/plugins/chai-as-promised) from chai-as-promised will help to solve some of the timer uses?

**Comment by hsiliev** [comment]
We stubbed timers with immediate in the cf-bridge tests in https://github.com/cloudfoundry-incubator/cf-abacus/pull/92

Although this speeds up the tests significantly this does not solve the problem completely. The tests still have 20-50ms timeout to enable the stubbed get&post requests to complete. Without this the tests fail even on non-loaded environment (our local machine) and this will be worse on Travis.

Perhaps we should use callbacks or promises in the tested methods to be able to solve this. Any advice is welcome.

**Comment by jsdelfino** [comment]
I've gone through a number of unit tests and fixed their timing issues. I've also changed a number of calls to process.nextTick to setImmediate as process.nextTick was not the best way to trigger async processing and was also causing IO starvation issues under load.

Generally I think we need to implement the test checks in callbacks when the processing is asynchronous.

That's usually easy to do in unit tests, as we can use the callbacks usually offered by the tested modules, or hook callbacks into them.

It'll be more difficult to do in some of the integration tests, so there we may still need to continue to regularly poll for results.

In the future we may want to think about instrumenting our services with test callback hooks or maybe write the results to a socket connection that integration tests will then be able to use to detect when the results are ready.

**Comment by jsdelfino** [comment]
This is now fixed. Please reopen if needed.
