### ISSUE TITLE
bin/update-locks file does not exist.

### ISSUE THREAD

**Issue by eujungkim** [cloudfoundry-incubator/cf-abacus#891]
I checkout v1.1.0 and try to update dependencies to execute below as the guide.
$ cd cf-abacus
$ bin/update-locks`

But in cf-abacus release, bin/update-locks file does not exist. 
And many files in bin directory still use npm, not yarn.
Can I get bin files for yarn?

**Comment by hsiliev** [comment]
You are right the correct script is `bin/update-dependencies` and README still has this wrong.

With 1.1.0 we introduced yarn as development mechanism. We still need to migrate the cfpush mechanism to deal with private packages and our monorepo. The next version will have this unified so we can get rid of npm.

**Comment by hsiliev** [comment]
Changed readme with https://github.com/cloudfoundry-incubator/cf-abacus/commit/7fdfa17efa4a8bbfe43548dea1ce1c89202fe6f8

**Comment by eujungkim** [comment]
Thank you for your reply and changing readme.
It works well.
