### ISSUE TITLE
How to meter active users count? 

### ISSUE THREAD

**Issue by iihero** [cloudfoundry-incubator/cf-abacus#892]
I have a requirement to meter the active registered user count in our application.   Just need a way to configure the metering plan (configuration) to make it work.  But still there is not a clear way. 

Each time,  we send the usage data to the collector.  Its content looks like: 

{
  "start": 1520836632038,
  "end": 1520836632038,
  "consumer_id": "app:test100",
  "space_id": "4a5e51a3-1af8-4f5d-b70c-d40aead41060",
  "organization_id": "1070e5be-6b4d-4ae1-928b-75c5e909e9d2",
  "resource_id": "b0688bce-ee73-4134-a022-fbd2c1647388",
  "plan_id": "standard",
  "resource_instance_id": "<resource_instance_id>",
  "measured_usage": [
    {
      "measure": "active_users",
      "quantity": "100"
    }
  ]
}

Here the quantity 100 is the real total count at the time.

We just updated the metering plan like:
{
	"plans": [{
			"plan": {
				"plan_id": "active_users",
				"measures": [{
						"name": "active_users",
						"unit": "active_users"
					}
				],
				"metrics": [{
						"name": "active_users",
						"unit": "active_users",
						"type": "discrete",
						"meter": "((m) => new BigNumber(m.active_users).toNumber()).toString()",
						"accumulate": "((a, qty, start, end, from, to, twCell) => end < from || end >= to ? 0 : Math.max(a, qty)).toString()"
						
					}
				]
			}
		}
	]
}

But we can't  get any expected result from the report. 
In the metering report,  we just need the maximum value for each month, each day etc.

**Comment by hsiliev** [comment]
Your accumulate function converts the result to string. I don't think that's intended, so can you please modify it to:
`(a, qty) => end < from || end >= to ? 0 : Math.max(a, qty)`

You can use the plan-tester tool to check what would be the output of our plan:
https://github.com/cloudfoundry-incubator/cf-abacus/tree/master/lib/config/plan-tester

**Comment by hsiliev** [comment]
Closing this issue, but feel free to reopen it if you have more questions or issues with defining a plan
