### ISSUE TITLE
Usages with different end time years have issues

### ISSUE THREAD

**Issue by AzureEnigma** [cloudfoundry-incubator/cf-abacus#90]
If you submit usage with different years in their end time to the collector, the report will not be generated. Example that causes it:

{
   "usage":[
      {
         "start":1416441600000,
         "end":1417392000000,
         "region":"us",
         "organization_id":"a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf17",
         "space_id":"aaeae239-f3f8-483c-9dd0-de5d41c38b6a",
         "consumer":{
            "type":"EXTERNAL",
            "consumer_id":"bbeae239-f3f8-483c-9dd0-de6781c38bab"
         },
         "resource_id":"object-storage",
         "plan_id":"basic",
         "resource_instance_id":"0b39fa70-a65f-4183-bae8-385633ca5c87",
         "measured_usage":[
            {
               "measure":"ScalingActivities",
               "quantity":2
            },
            {
               "measure":"UsedTime",
               "quantity":1000000
            }
         ]
      },
      {
         "start":1435629365220,
         "end":1435639465220,
         "region":"us",
         "organization_id":"a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf17",
         "space_id":"aaeae239-f3f8-483c-9dd0-de5d41c38b6a",
         "consumer":{
            "type":"EXTERNAL",
            "consumer_id":"bbeae239-f3f8-483c-9dd0-de6781c38bab"
         },
         "resource_id":"object-storage",
         "plan_id":"basic",
         "resource_instance_id":"0b39fa70-a65f-4183-bae8-385633ca5c87",
         "measured_usage":[
            {
               "measure":"ScalingActivities",
               "quantity":2
            },
            {
               "measure":"UsedTime",
               "quantity":1000000
            }
         ]
      }
   ]
}

**Comment by sasrin** [comment]
> the report will not be generated. 
Could you provide details on how you are checking/retrieving the usage report?

**Comment by AzureEnigma** [comment]
I am using the endpoint: http://localhost:9088/v1/metering/organizations/a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf17/aggregated/usage/1435639465220. This endpoint is not grabbing the report. However, one of the dates is in 2014. That might be the problem.
