### ISSUE TITLE
Abacus never receives 'SIGTERM' and 'SIGINT' events

### ISSUE THREAD

**Issue by svgradev** [cloudfoundry-incubator/cf-abacus#908]
All listeners registered on `process.on('SIGTERM')` and `process.on('SIGINT')` are never called on cf environment. On one hand `npm stop` script is not called by cf, and on the other, termination signals sent by cf are lost and never received by node process(es). 

If we use `exec` instead of `launch` in start script the issue seems to be solved. 
Example:
```
"scripts": {
    "start": "exec webapp start"
}
```
This is caused by change in started processes' hierarchy. According to cf [documentation](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#start-commands) this is recommended approach to solve similar issue.

**Comment by hsiliev** [comment]
Cluster module was removed with 04c10f9ba17aebea7e647ea4e4a891098562ce38

**Comment by hsiliev** [comment]
Closed via https://github.com/cloudfoundry-incubator/cf-abacus/commit/cf885799ffc3b058d6290846c14dfc708c0422ba
