### ISSUE TITLE
Build error while building abacus-price-config

### ISSUE THREAD

**Issue by piotrprzybylski** [cloudfoundry-incubator/cf-abacus#93]
The npm test of abacus-price-config fails with the following error 

> abacus-price-config@0.0.2-rc.0 test /Users/piotrp/tmp/node_modules/abacus-price-config
> eslint && mocha

/Users/piotrp/tmp/node_modules/abacus-price-config/src/index.js
  75:9  error  Expected indentation of 6 space characters but found 8  indent
  79:9  error  Expected indentation of 6 space characters but found 8  indent
  80:7  error  Expected indentation of 4 space characters but found 6  indent

**Comment by jsdelfino** [comment]
Looks like eslint v1.7.0 got pushed to npm 2 hours and (conveniently on our release v0.0.2 day) broke our builds... Fixed this for now by setting our eslint dependency version back to 1.6.0.
