### ISSUE TITLE
GraphQL consumers field always has null values

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#96]
I was trying to get a report where I wanted the hierarchy spaces -> consumers and spaces -> resources.
I used the following query on the data that was generated by the demo-client
```javascript
{ 
	organizations(organization_ids: ["a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27"], time: 1445272416655) { 	
		organization_id, 
		spaces { 
			space_id, 
			consumers { 
				consumer { 
					consumer_id 
				} 
			}, 
			resources { 
				resource_id, 
				plans { 
					plan_id 
				} 
			} 
		}
	}
}
```
and i got the following response
```javascript
{
    "organizations": [
        {
            "organization_id": "a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27",
            "spaces": [
                {
                    "space_id": "aaeae239-f3f8-483c-9dd0-de5d41c38b6a",
                    "consumers": [
                        null
                    ],
                    "resources": [
                        {
                            "resource_id": "object-storage",
                            "plans": [
                                {
                                    "plan_id": "basic"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

If I queried with 
```javascript
{ 
	organizations(organization_ids: ["a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27"], time: 1445272416655) { 	
		organization_id, 
		spaces { 
			space_id, 
			consumers { 
				consumer_id 
			}, 
			resources { 
				resource_id, 
				plans { 
					plan_id 
				} 
			} 
		}
	}
}
```

i get 

```javascript
{
    "error": "Cannot read property '_id' of undefined"
}
```

How do I get the list of all consumers?

**Comment by jsdelfino** [comment]
The problem is in the aggregator service, which stores consumer ids as strings instead of the proper consumer object. I will take a look at fixing this.

**Comment by jsdelfino** [comment]
After reviewing that consumer/consumer_id object I'm thinking that it'll be much simpler to just have a string for this consumer id instead of an object.

That string can be a uri and still distinguish between different consumer id namespaces (apps, external etc) like this for example: `app/app1`, `'user/bob@foo.org`, 'external/somethingelse` or `unknown` for example. This will also make it simpler for GraphQL requests to select a particular consumer in a report.

This will be a simple change for resource providers, they will just submit that consumer_id string instead of a consumer object.

**Comment by jsdelfino** [comment]
Actually, let me take that back... It'll be cleaner to keep two separate fields for consumer_type and consumer_id. A notation with / in the consumer ids would also confuse the REST APIs as '/' is a URI path separator.

**Comment by sasrin** [comment]
> That string can be a uri and still distinguish between different consumer id namespaces (apps, external etc) like this for example: app/app1, 'user/bob@foo.org, 'external/somethingelseorunknown` for example. This will also make it simpler for GraphQL requests to select a particular consumer in a report.

+1

**Comment by jsdelfino** [comment]
You're correct that we don't have such a structure for other ids... With that idea in mind, I'm not thinking that we could just use a URN format with ':' as a separator, for example `app:app1` and 'external:foo` would be consumer ids from the app and external 'namespaces'.

**Comment by jsdelfino** [comment]
So I think you've convinced me, changing the consumer id to a string following a URN format everywhere for consistency.
