### ISSUE TITLE
Tests need to adapt with and test the slack window logic.

### ISSUE THREAD

**Issue by BetaFood** [cloudfoundry-incubator/cf-abacus#97]
Currently, only a few tests(like the accumulator) have been adjusted to work with the new slack window logic. All the tests need to work correctly with this logic.

Additionally, tests need to be able to test the actual slack window logic without any dependencies on what time/date the test is run.

**Comment by jsdelfino** [comment]
@BetaFood is that still an issue or can we close this one? Thanks

**Comment by BetaFood** [comment]
The unit tests have adapted to working with the slack window logic.
Currently, only the accumulator and aggregator are missing from this since they're still not verifying the end result.

**Comment by BetaFood** [comment]
Commits 3e6ea259476c3f674364bd1f2809edc900a3a642 and d75ec5c77a72314d58f08becacf60b6c5c3c579a finish the last tests that need to be adapted, so this issue can be closed now.
